wcc CLI design proposal
wasmCloud/wash-archive pull request #1
Opened 2020-10-05 19:53 UTC by brooksmtownsend

This PR includes the client libraries for the cli utilities and mocks out the usage of `wcc` as a cli tool. This PR is meant to be a discussion space before merging (unless this is a solid mockup of the commands/)

2020-10-06 12:25 UTC, autodidaddict requested changes

2020-10-06 12:25 UTC, autodidaddict commented on README.md
> +    wcc keys jwt <keytype>
Maybe calling this sub-command `claims` is a better, more descriptive option? `keys` above makes sense, but feels like conflation to put the claims and keys functionality in the same sub-command.

2020-10-06 12:25 UTC, autodidaddict commented on README.md
> +Note: this combines the functionality of `nkeys` and `wascap` for generating keys & generating JWTs. Depending on the needs of the tool, these could potentially be combined to abstract the need for t
Let's avoid mentioning which individual crates are responsible for this functionality.

2020-10-06 12:25 UTC, autodidaddict commented on README.md
> +Handles signing actor modules, previously handled by the `wascap` cli
See previous comment -  let's not reference which previous CLI tools or which crates we get the functionality from.

2020-10-06 12:25 UTC, autodidaddict commented on README.md
> +    wcc keys jwt <keytype>
let's change `jwt` to `token` , so `wcc claims token ....` produces a new token.

Below, let's change the `caps` command to `claims inspect ...` where we pass the filename of a wasm file to inspect.

2020-10-06 12:25 UTC, autodidaddict commented on README.md
> +### caps
Let's move `caps` into the `claims` sub-command and call the individual action `inspect`, e.g. `wcc claims inspect ./foo.wasm`

2020-10-06 12:25 UTC, autodidaddict commented on README.md
> +Handles interrogating the lattice, previously handled by the `latticectl` cli
let's drop the references to previous CLIs/crates

2020-10-06 13:44 UTC, autodidaddict commented on README.md
>      <keytype>    The type of jwt to generate. May be Account, Actor, or Operator.
`keytype` should probably be something like `token_type` since we're not generating a key here.

2020-10-06 13:45 UTC, autodidaddict commented on README.md
> +Depending on the needs of the tool, these could potentially be combined to abstract the need for the user to manage the public key & seeds and instead just provide users with JWTs.
We need the ability to create/manage the seed keys because those are required for signing actor modules.

2020-10-06 14:08 UTC, brooksmtownsend commented on README.md
> +Depending on the needs of the tool, these could potentially be combined to abstract the need for the user to manage the public key & seeds and instead just provide users with JWTs.
Is there value in providing the `gen` functionality at all if `wcc` is primarily concerned with creating signed tokens? What if we only provide the `claims token` subcommand and hide the keypair gen from the user, outputting keypairs to disk in order to sign subsequent actors, or allowing for an argument for module / account keys for signing?

2020-10-06 19:27 UTC, autodidaddict requested changes

2020-10-06 19:27 UTC, autodidaddict commented on README.md
> +Depending on the needs of the tool, these could potentially be combined to abstract the need for the user to manage the public key & seeds and instead just provide users with JWTs.
If you're going to construct an operator hierarchy, like you would do for Gantry, then you'll need the ability to create freestanding JWTs that aren't being used for embedding. Gantry requires operator JWTs and account JWTs that aren't embedded in actors.

we should have:
`wcc keys gen` (generate a key for Account, Module, Provider (new), Operator
`wcc claims inspect ...`
`wcc claims token` (required for building operator hierarchies in Gantry)
`wcc sign ...`

We need to allow the ability to explicitly generate keys because when constructing robust hierarchies (provenance chains), we support the notion of using multiple signing keys for a single entity. In other words, operators and accounts have a unique public key, but they also have secondary public keys that correspond to private keys... tl;dr a single account or operator can have multiple private keys for signing. Since keys and JWTs aren't always 1:1, we need this flexibility.

2020-10-07 13:39 UTC, brooksmtownsend commented on README.md
> +Depending on the needs of the tool, these could potentially be combined to abstract the need for the user to manage the public key & seeds and instead just provide users with JWTs.
Makes sense. I think we also can't fully abstract keys away because when signing subsequent wasm files, you will want to re-use your account / operator to do so and not only use your own key. During implementation I want to do some planning and some real-world tests to figure out how we can make this experience better and easier for a user to generate their own keys, but I'll update README accordingly then

2020-10-07 13:44 UTC, autodidaddict approved these changes
LGTM

2020-10-07 13:53 UTC, merged