No lattice repl
wasmCloud/wash-archive pull request #107
Opened 2021-03-05 17:24 UTC by brooksmtownsend

Working on #92 

Initial PoC of what this may look like, channels are used to accomplish sending operations and output back and forth to the REPL contained host. There's still some work to be done refactoring and ironing out the channel logic but this works for `ctl get hosts` at the moment.

Weekend safety draft PR 🙂

2021-03-05 21:44 UTC, autodidaddict commented
Safe? You think the weekend makes you safe?
![image](https://user-images.githubusercontent.com/13748641/110176923-168ee600-7dd2-11eb-8945-85b8018346d3.png)

2021-03-10 13:49 UTC, autodidaddict commented
Maybe the diff isn't showing it, or I'm confused. I was looking for the code that uses channels to send commands either to the control interface or to the managed host.. is that somewhere else?

2021-03-10 13:51 UTC, brooksmtownsend commented
@autodidaddict Yeah it's just moved around because I restructured the project a bit to clean up the code, check `src/up/mod.rs` https://github.com/wasmCloud/wash/pull/107/files#diff-dcf780801376c219d3b5d7f2f9a5a2745c5ccb124b8c621281e13d3c775ed9f3

2021-03-10 14:01 UTC, autodidaddict commented
Thanks for the link.. though it's still not in the diff, this is what I was looking for:

https://github.com/wasmCloud/wash/blob/dd0540b3e56891689a10ac8274591948794c8920/src/up/mod.rs#L642

2021-03-10 14:10 UTC, autodidaddict approved these changes, later dismissed

2021-04-13 21:00 UTC, brooksmtownsend commented
As of my latest commit:
- Fixed bug where characters would show vertically across output window
- Implemented the above three functions, which now brings standalone mode to full parity with lattice connected mode

There are only a few more areas where I need to implement functionality `wasmcloud-host`:
- [ ]  Need a way to get the provider link name for host inventory
- [ ]  Need a way to update the OCI mapping when an actor is updated (currently if I update `echo:0.2.0` to `echo:0.2.1`, the OCI mapping still contains the echo public key and `echo:0.2.0`)
- [ ]  Need to have connection parameters provided for update actor, currently they are just defaults (no latest tags, secure connection, no user/pass)

2021-04-15 18:24 UTC, brooksmtownsend commented
All functionality has been implemented and `wash` no-nats (standalone) mode has exact parity with nats (lattice) mode. The build is going to fail because of relative path dependencies and that can be remedied once https://github.com/wasmCloud/wasmCloud/pull/163 is ready

2021-04-16 13:52 UTC, brooksmtownsend commented
REVIEWER'S GUIDE TO SOME OF THE BIG CHANGES (@autodidaddict )

I've refactored the `ctl` and `up` modules so they appear to have been deleted and written. The `ctl` module has been refactored into `mod` and `output`, where `mod` is the functionality of the `ctl` module and `output` is where all of the helper functions exist to translate the CTL resources into a String for output in the terminal. The neat thing about this is that I'm using these helper functions with the standalone mode as well, that way there will be no difference between what the user sees in either mode.

`up` was refactored as well, mostly to pull some of the large parts of standalone mode types into another file. I'd like to continue to refactor this a bit as `up` and `ctl` are approaching 1000 lines but for now this is enough change.

2021-04-16 14:00 UTC, autodidaddict requested changes
LGTM once clippy has been placated.

2021-04-16 15:47 UTC, autodidaddict approved these changes

2021-04-16 15:55 UTC, merged