Truncate id and add name to inventory output
wasmCloud/wash-archive pull request #145
Opened 2021-06-14 19:03 UTC by frigus02

Hi again. I started to play with truncating the actor/provider id and adding a name column. It feels tricky to strike the right balance here. I think ideally we don't truncate the id if there is enough space. This  seems okay to me.

- Truncate actor/provider id in host inventory to fit into one column

  - We use the available column width to truncate the id and add an ellipsis
  - Truncation only happens if the output width is restricted, which is currently only the case in the REPL
  - The flag `--output wide` also sets the output width to be unrestricted

- Add actor/provider name column to host inventory

Fixes #114

![](https://user-images.githubusercontent.com/3579251/121944321-d5a05900-cd52-11eb-9f15-a66e72a53662.png)

What do you think?

2021-06-14 19:37 UTC, brooksmtownsend requested changes
This is a great iteration on the previous PR, good thinking to source the width of the column to the minimum size of the other fields, like the label key. Just a few minor comments.

IMO, the `--output wide` is enough for us to proceed with this PR without having the tab autocomplete, I will just have to take down a note to mention it in the `0.5.0` release.

2021-06-14 19:37 UTC, brooksmtownsend commented on src/util.rs
> +    let padding_width = if padding { 2 } else { 0 };
I think the `padding` argument here could be renamed to something like `paddingOffset` or similar, to avoid this if statement which feels a bit hardcoded. It looks like you're only using it in one place, so you can simply pass 2 in as an adjustment value for that function call, and this lets us potentially change padding later.

2021-06-14 19:37 UTC, brooksmtownsend commented on src/util.rs
> +            "wide" => Ok(OutputKind::Text { max_width: 0 }),
I believe your logic further in the code will assign `usize::MAX` in the case where the `max_width` is 0, but I think it would be more clear if you go ahead and assign that value here, in case the logic changes in the `configure_table_style` function

2021-06-16 19:10 UTC, frigus02 commented on src/util.rs
> +            "wide" => Ok(OutputKind::Text { max_width: 0 }),
Yeah, I made `0` mean "no max width". I copied this from clap:

> Sets the max terminal width at which to wrap help messages. Using 0 will ignore terminal widths and use source formatting.
> -- https://docs.rs/clap/2.33.3/clap/struct.App.html#method.max_term_width

It made sense to be because what else would 0 mean.

That said, using `usize::MAX` might make this more obvious. And `term_table` uses `usize::MAX` as their default values as well:

> The maximum width of all columns. Overridden by values in column_widths. Defaults to std::usize::max
> -- https://docs.rs/term-table/1.3.1/term_table/struct.Table.html#structfield.max_column_width

I going to change this to use `usize::MAX` and get rid of `0`.

2021-06-16 19:16 UTC, frigus02 commented on src/util.rs
> +    let padding_width = if padding { 2 } else { 0 };
Yeah. This is a bit awkward. The padding comes from `TableCell::pad_content` in `term_table`, which is a boolean. I wanted to give this parameter the same name (i.e. "pad_content") but messed it up somewhere along the way and used "padding" 🤦.

I wonder if there is a way to make this relation more obvious. Maybe it's best to remove the parameter entirely and do `- 2` where we call the function.

2021-06-16 19:37 UTC, frigus02 commented
Thanks for the quick review @brooksmtownsend and sorry for the slow turnaround on my side. Please let me know if this looks okay now.

2021-06-16 19:56 UTC, brooksmtownsend requested changes
Only one small request to reflect what we discussed in the PR, otherwise LGTM 👍🏻

2021-06-16 19:56 UTC, brooksmtownsend commented on src/ctl/output.rs
> +
Final request here, perhaps just add a quick note in a comment like "From term_table::TableCell::pad_content" just to show where you got the value from

2021-06-16 20:15 UTC, frigus02 commented on src/ctl/output.rs
> +
I think it might be nice if `term_table` would support different ways to deal with cell content that is too wide. At the moment it always wraps. If it supported truncation (with ellipsis), we wouldn't have to know about the internal padding calculation here. Maybe that's something for later, though 🙂

2021-06-16 20:19 UTC, brooksmtownsend approved these changes

2021-06-16 20:27 UTC, merged