Otp changes (march toward 0.6.0)
wasmCloud/wash-archive pull request #153
Opened 2021-08-06 03:18 UTC by stevelr

- create LatticeClient to hold two nats clients: control interface and rpc interface.
- use wasmcloud-control-interface 0.5.0 that has smithy-generated data structures
- disabled some unused and deprecated code (wash up, etc.) 
- all tests except for control interface tests pass. control interface tests should be updated after jetstream/events settle down

2021-08-06 18:48 UTC, brooksmtownsend requested changes
Just a couple of requests, largely looks good 🙂

2021-08-06 18:48 UTC, brooksmtownsend commented on Cargo.toml
> +#wasm3 = ["wasmcloud-host/wasm3", "tui/termion", "termion"]
No issues with leaving this for now, but we should go through and clean up all the unused things like these dependencies, up code, etc

2021-08-06 18:48 UTC, brooksmtownsend commented on src/ctl/mod.rs
> +const FAKE_WASH_KEY: &str = "__WASH__";
This is just a nitpick but I think we can call this `WASH_ORIGIN_KEY` without too much miscommunication, just feels like temporary code to call it a fake key

2021-08-06 18:48 UTC, brooksmtownsend commented on src/ctl/mod.rs
> +const FAKE_WASH_KEY: &str = "__WASH__";
I do like the comment though denoting that it's not a valid public key

2021-08-06 18:48 UTC, brooksmtownsend commented on src/main.rs
> +#[allow(clippy::large_enum_variant)]
Did another variant get flagged as large? I think I handled this by boxing `ClaimsCli` before

2021-08-06 18:48 UTC, brooksmtownsend commented on tests/integration.rs
> +    //assert!(output.contains("ctl"));
I think we should still assert that it contains `ctl`

2021-08-06 18:48 UTC, brooksmtownsend commented on src/ctl/mod.rs
> +        })
For here we will need to support two different nats connections for rpc and ctl, they are OK being the same in the local development environment but will likely be different past local dev

2021-08-09 04:16 UTC, stevelr commented on Cargo.toml
> +#wasm3 = ["wasmcloud-host/wasm3", "tui/termion", "termion"]
I wanted to hold off on the major shredding until the new features were working, just to make sure I didn't delete something that was going to be needed.

2021-08-09 05:03 UTC, stevelr commented on src/main.rs
> +#[allow(clippy::large_enum_variant)]
Clippy warned that Ctl(CtlCli) is 296 bytes and the second-largest, Keys(KeysCli) is 72 bytes. It's not a real problem since there's only one, so I disabled the clippy warning.

2021-08-09 05:22 UTC, stevelr commented on tests/integration.rs
> +    //assert!(output.contains("ctl"));
fixed

2021-08-10 12:35 UTC, autodidaddict requested changes
Few minor nitpicks, also need to fix the build (clippy and cargo check failures)

2021-08-10 12:35 UTC, autodidaddict commented on Cargo.toml
> +#wasmtime = ["wasmcloud-host/wasmtime", "tui/termion", "termion"]
If we don't need these, delete rather than comment out

2021-08-10 12:35 UTC, autodidaddict commented on src/ctl/mod.rs
> +const WASH_ORIGIN_KEY: &str = "__WASH__";
historically whenever the origin is a non-developer actor we send the actor ID of `system`. Is there a need to use this here instead of that?

2021-08-10 12:35 UTC, autodidaddict commented on src/ctl/mod.rs
> +const WASH_ORIGIN_KEY: &str = "__WASH__";
In other words, is there anything elsewhere that looks for this particular magic string?

2021-08-10 12:35 UTC, autodidaddict commented on src/ctl/mod.rs
> +        })
Seconded, the RPC and Ctl clients can't re-use the same nats connection.

2021-08-10 12:35 UTC, autodidaddict commented on src/main.rs
> +//#[cfg(feature = "termion")]
please delete rather than comment out

2021-08-10 12:35 UTC, autodidaddict commented on tests/integration.rs
> +    //assert!(output.contains("up"));
see previous notes re: comments vs. deletion

2021-08-10 12:45 UTC, brooksmtownsend commented
@autodidaddict @stevelr just for clarity, I'll be working on this PR now so I can address those comments

2021-08-10 20:27 UTC, brooksmtownsend commented
Depends on https://github.com/wasmCloud/control-interface/pull/1

2021-08-12 17:06 UTC, autodidaddict requested changes
LGTM, just remove a couple comments that look like they're no longer needed.

2021-08-12 17:06 UTC, autodidaddict commented on src/call.rs
> +    fn test_rpc_comprehensive() -> Result<()> {
I love tests like this.

2021-08-12 17:06 UTC, autodidaddict commented on tests/integration_ctl.rs.broken
> +//use wasmcloud_host::HostBuilder;
as usual, remove commented out things that aren't going to come back from the dead.

2021-08-12 17:06 UTC, autodidaddict commented on tests/integration_ctl.rs.broken
> +/*
as with other comment - can this be deleted?

2021-08-12 18:58 UTC, brooksmtownsend commented on tests/integration_ctl.rs.broken
> +//use wasmcloud_host::HostBuilder;
went ahead and removed the entire file, we can go back and be inspired by test cases but by and large the structure will need to change as we no longer have an embedded host to run

2021-08-12 18:58 UTC, brooksmtownsend commented on tests/integration_ctl.rs.broken
> +/*
went ahead and removed the entire file, we can go back and be inspired by test cases but by and large the structure will need to change as we no longer have an embedded host to run

2021-08-16 16:08 UTC, autodidaddict approved these changes

2021-08-16 17:54 UTC, brooksmtownsend approved these changes

2021-08-16 17:54 UTC, merged