add flags to call actor so it can call a test actor
wasmCloud/wash-archive pull request #156
Opened 2021-08-17 07:38 UTC by stevelr

Signed-off-by: steve <dev@somecool.net>

New options for `wash call actor`:

 `--data`  allows using a json file for the parameter instead of key-value. This flag isn't necessarily test-specific. It could be used for anyone that uses `wash call actor`.
 `--test`  enables attempting to interpret the results as a Vec<TestResult> (defined by the wasmcloud-test-utils crate).
(I initially tried to add a variant to OutputKind, adding `-o test` instead of `--test`, but it would have affected more than six files, since OutputKind is used everywhere, but TestResult only applies to call actor, so it seemed cleaner to not add an enum variant).

2021-08-17 15:17 UTC, brooksmtownsend requested changes
small suggestion for help text, otherwise LGTM

2021-08-17 15:17 UTC, brooksmtownsend commented on src/call.rs
> +    pub(crate) data: Option<std::path::PathBuf>,
I think we should indicate that the data is used for the operation, e.g. 
```
Optional JSON file to send as the operation payload
```

2021-08-20 16:59 UTC, brooksmtownsend requested changes

2021-08-20 16:59 UTC, brooksmtownsend commented on src/util.rs
> +}
Does this... really work? I'm not accusing you of not testing it, I'm just really glad if you found the right way to deserialize arbitrary msgpack bytes since @autodidaddict and I spent hours trying to find the right way to do that in Rust

2021-08-20 16:59 UTC, brooksmtownsend commented on src/util.rs
> +}
edit: I tried it out, unfortunately looks like it's the same issue as we were running into before where the nested byte array messed with deserialization (this is the echo actor.)
```
➜ cargo run -- call MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5 HandleRequest '{"method": "GET", "path": "/mycounter", "body":"", "queryString":"", "header":{}}' -o json
    Finished dev [unoptimized + debuginfo] target(s) in 0.29s
     Running `target/debug/wash call MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5 HandleRequest '{"method": "GET", "path": "/mycounter", "body":"", "queryString":"", "header":{}}' -o json`
{"error":"deserialization: invalid type: byte array, expected any valid JSON value"}
```

Unless you have some ideas for the deserialization, I think you may have to revert to the lossy response for `json` as well

2021-08-20 19:57 UTC, stevelr commented on src/util.rs
> +}
fixed - see update

2021-08-20 20:05 UTC, brooksmtownsend approved these changes
Someone get @stevelr a 🏅 for the fix of the century

2021-08-20 20:21 UTC, autodidaddict commented
This is that moment from a sci-fi movie when everyone says it can't be done and @stevelr whips something together with bubble gum and a pine cone and saves the planet.

2021-08-20 21:17 UTC, stevelr commented
Those kinds of problems are my specialty!

2021-08-21 00:59 UTC, merged