add new project generation capability
wasmCloud/wash-archive pull request #161
Opened 2021-08-30 03:44 UTC by stevelr

Signed-off-by: stevelr <steve@cosmonic.com>

2021-08-30 10:55 UTC, stevelr commented
I know about the integration_drain test failing - still working on it. In the meantime, I'll mark the PR as draft.

2021-08-30 19:04 UTC, stevelr commented
This PR adds three new top-level wash commands
`wash new [actor|interface|provider` - create a new project from a template
`wash lint` - run lint checks on a smithy model
`wash validate` - run validation checks on a smithy model

over time, we'll probably add more rules for both lint and validation.

There's one more command needed to be on-par with the `weld` binary - a way to trigger code/documentation generation for any codegen.toml file.  I'll do that as a separate PR.

2021-08-30 19:10 UTC, stevelr commented
PR ready for review @brooksmtownsend @autodidaddict

2021-08-31 00:23 UTC, brooksmtownsend requested changes
A couple requests, and I'm still kinda confused about the "Favorites" topic so perhaps you can explain it in the next build call (or here, either one works)

Overall looks great, and I can't wait to try it out. If you have any suggestions I'll give it a shot from this branch

2021-08-31 00:23 UTC, brooksmtownsend commented on src/generate/config.rs
> +        file.write_all(
You may want to reference the integration tests, but I was using a tempdir in the test fixtures directory which worked pretty well. No obligation to change, just a comment

2021-08-31 00:23 UTC, brooksmtownsend commented on src/generate/emoji.rs
> +//pub(crate) static DIAMOND: Emoji<'_, '_> = Emoji("🔸  ", "");
Looks like the diamond can be removed but wow I ❤️ emojis in code

2021-08-31 00:23 UTC, brooksmtownsend commented on src/generate/favorites.rs
> +//! git = "optional github url. Either github or path must be provided"
nitpick: is `Either github or path must be provided` saying you have to provide a path or a git reference? if so, maybe just change `either github or path` to `either git or path` to match the toml fields

2021-08-31 00:23 UTC, brooksmtownsend commented on src/generate/favorites.rs
> +//! Favorites
Is this another way to declare defaults for a generate file?

2021-08-31 00:23 UTC, brooksmtownsend commented on src/generate/git.rs
> +        // https://stackoverflow.com/questions/41233684/why-does-my-canonicalized-path-get-prefixed-with
`#[cfg(windows)]`
`not a bug...`
LOL

2021-08-31 00:23 UTC, brooksmtownsend commented on src/generate/git.rs
> +*/
Was going to comment to remove this, but if it's in the near future I'm fine with this. Only thing I'd request is a bit more information saying that it's a planned feature and will be added

2021-08-31 00:23 UTC, brooksmtownsend commented on src/generate/mod.rs
> +//! ## Project generation from templates
Great writeup here re: `cargo generate`

2021-08-31 00:23 UTC, brooksmtownsend commented on src/generate/mod.rs
> +//use cargo::core::GitReference;
can be removed

2021-08-31 00:23 UTC, brooksmtownsend commented on src/generate/mod.rs
> +}
I think these comments can be removed

2021-08-31 00:23 UTC, brooksmtownsend commented on src/util.rs
> +            /*'b'|*/ _ => JV::Array(v.into_iter().map(JV::from).collect::<Vec<_>>()),
can the `/* 'b' | */` be removed?

2021-08-31 00:23 UTC, brooksmtownsend commented on src/generate/template.rs
> +}
How do you like this crate? we should consider it as an alternative for `Spinners` re: #57

2021-08-31 15:28 UTC, stevelr commented on src/generate/config.rs
> +        file.write_all(
it seems like there's enough of a use for a shared temp folder for integration tests that it makes sense to consolidate. This is a quick test and I have a slight preference for the simplicity of creating a tempdir here this test case.

2021-08-31 15:35 UTC, stevelr commented on src/generate/favorites.rs
> +//! Favorites
Favorites are a list of "favorite" project templates, grouped by type (actor/interface/provider). When there are more than one of a particular type, you get a menu to select (there are two choices for interfaces now). There's a compiled-in toml file that contains the favorites, but in the near future, wash will be able to pull the list from github, so we can add to or refine the list without changing the binary (and revert to the compiled-in list if it can't find the online version)

2021-08-31 15:36 UTC, stevelr commented on src/generate/favorites.rs
> +//! Favorites
there is a way to declare default values for a generated project - that's the values file. I could provide a separate readme file that goes into more detail on all the options.

2021-08-31 15:40 UTC, stevelr commented on src/generate/template.rs
> +}
I've used indicatif in other projects. I like it.

2021-08-31 15:44 UTC, stevelr commented on src/util.rs
> +            /*'b'|*/ _ => JV::Array(v.into_iter().map(JV::from).collect::<Vec<_>>()),
I left it there as documentation so it's easy to see what happens to the 'b' option.

2021-08-31 15:46 UTC, stevelr commented on src/generate/git.rs
> +*/
updated comment

2021-08-31 15:49 UTC, stevelr commented
Thanks for the review! I addressed  your comments in the latest commits. There's a note addressing the question about 'favorites' above. I'll write a separate documentation file (in a separate PR)  to explain all the project-generation options.

2021-09-01 00:11 UTC, brooksmtownsend approved these changes

2021-09-01 16:50 UTC, merged