GitHub Action update + Brew automation
wasmCloud/wash-archive pull request #190
Opened 2021-10-04 19:42 UTC by jordan-rash

Update action to build OS specific artifacts while supporting automated Brew releases for OSX installation

Requires: https://github.com/wasmCloud/homebrew-wasmcloud/pull/6

2021-10-04 19:57 UTC, jordan-rash commented on .github/workflows/release.yml
> +        token: ${{ secrets.HOMEBREW_TOKEN }}
This needs to have access to the `wasmcloud/homebrew-wasmcloud` repo

2021-10-12 14:27 UTC, autodidaddict commented
@jordan-rash can you please follow the instructions you get from clicking the [details](https://github.com/wasmCloud/wash/pull/190/checks?check_run_id=3795755191) button on the DCO check?

2021-10-12 14:27 UTC, autodidaddict commented
@brooksmtownsend have you reviewed this?

2021-10-12 14:30 UTC, jordan-rash commented
> @jordan-rash can you please follow the instructions you get from clicking the [details](https://github.com/wasmCloud/wash/pull/190/checks?check_run_id=3795755191) button on the DCO check?

Sorrrrryyyyy @autodidaddict .... 😓

2021-10-12 14:31 UTC, autodidaddict commented
No worries it's just PRs can't be merged w/out it.

2021-10-12 14:49 UTC, brooksmtownsend requested changes
This all looks good, only request would be to add a windows zip (rather than targz) and sha256 since we have the prebuilt release in wasmCloud-otp for windows. You should be able to take advantage of the windows runner

2021-10-25 12:59 UTC, autodidaddict approved these changes

2021-11-16 16:36 UTC, autodidaddict commented
@jordan-rash what's the status of this? Is this still active or should it be closed?

2021-11-16 16:43 UTC, jordan-rash commented
It probably still *should* be done, I have just ran out of cycles lately with #dayjob.  I will try and get this all caught up as soon as I can.

2021-11-22 14:46 UTC, jordan-rash commented
Closing in favor of more research.

2021-11-22 14:46 UTC, closed without merging