[FEATURE] wash Context
wasmCloud/wash-archive pull request #196
Opened 2021-11-04 15:48 UTC by brooksmtownsend

Fixes #194 

This is a draft so far, as I'd like to get some feedback on the context command before implementing context across the CLI.

I've implemented the following commands:
1. `new`
2. `default`
3. `edit`
4. `del`
5. `list`

TODO:
- [ ] Ensure context can be loaded correctly from other modules in the CLI
- [ ] Use context values to connect with `ctl` if present
- [ ] Use context values to connect with `call` if present
- [ ] Add prompts to `new` to allow user to supply values interactively (?)
- [ ] Write some tests

2021-11-04 21:24 UTC, thomastaylor312 reviewed
Functionality and structure looks pretty good with my first pass. Left random, hopefully helpful, notes along the way as I read through the code

2021-11-04 21:24 UTC, thomastaylor312 commented on src/ctx/mod.rs
> +    f.read_to_end(&mut buf)?;
Nit: `serde_json` has a Reader type you can use rather than reading into memory: https://docs.rs/serde_json/1.0.68/serde_json/fn.from_reader.html

2021-11-04 21:24 UTC, thomastaylor312 commented on src/ctx/mod.rs
> +/// Takes an absolute path to a JSON file and returns an IndexJson object
Nit: This doc comment should say that it takes a path to a _directory_ containing an index.json

2021-11-04 21:24 UTC, thomastaylor312 commented on src/ctx/context.rs
> +    pub fn default(&self) -> &String {
Rather than this being an accessor (that shares a name with a "reserved" function in Rust), I'd just recommend making the `default` data member `pub`

2021-11-04 21:24 UTC, thomastaylor312 commented on src/ctx/context.rs
> +pub(crate) struct IndexJson {
Ok, this name is suuuuuuuper confusing. It took me a couple of minutes to figure out what this was doing (and that it is related to a specific file name). Maybe something like `DefaultContext`

2021-11-04 21:24 UTC, thomastaylor312 commented on src/ctx/context.rs
> +fn default_nats_host() -> String {
These should all be `const` unless you actually need to do some lookups or manipulation. The `String`s you need can be converted from the `&str` when used in the default

2021-11-04 21:24 UTC, thomastaylor312 commented on src/ctx/mod.rs
> +    directory: Option<PathBuf>,
Can structopt do global flags? This is in every subcommand

2021-11-04 21:24 UTC, thomastaylor312 commented on src/ctx/mod.rs
> +/// Lists all JSON files found in the context directory, with the exception of `index.json`
This help text should definitely be part of the command

2021-11-04 21:24 UTC, thomastaylor312 commented on src/ctx/mod.rs
> +fn get_index(context_dir: PathBuf) -> Result<IndexJson> {
Nit: I'd recommend `&Path` so callers don't have to clone. You end up allocating a new `PathBuf` anyway with `.join` below

2021-11-04 21:24 UTC, thomastaylor312 commented on src/ctx/mod.rs
> +fn get_index(context_dir: PathBuf) -> Result<IndexJson> {
Pretty much anywhere you take a `PathBuf` you can use this, as all of the `io` functions take `AsRef<Path>`

2021-11-04 21:24 UTC, thomastaylor312 commented on src/ctx/mod.rs
> +    let contexts: Vec<String> = context_filestems_from_path(get_contexts(dir.clone())?);
Super Nit: shouldn't need a hardcoded type here

2021-11-04 21:24 UTC, thomastaylor312 commented on src/ctx/mod.rs
> +            .iter()
Nit: `IntoIter` to consume the data that you are dropping anyway in here

2021-11-04 21:24 UTC, thomastaylor312 commented on src/ctx/mod.rs
> +/// Load a file and return a Result containing the WashContext object. The `context_path` arg must be an absolute path
Does it have to be absolute? I don't think `open` requires that

2021-11-05 12:17 UTC, brooksmtownsend commented on src/ctx/mod.rs
> +            .iter()
Wow I was looking for this to avoid the `f.to_owned()` there, nice.

2021-11-05 12:19 UTC, brooksmtownsend commented on src/ctx/mod.rs
> +/// Load a file and return a Result containing the WashContext object. The `context_path` arg must be an absolute path
I'm not exactly sure what I was thinking here after re-reading it. I might've been confused about passing the name of a context rather than the path to it...

Regardless, I'll remove that :)

2021-11-05 12:26 UTC, brooksmtownsend commented on src/ctx/mod.rs
> +    directory: Option<PathBuf>,
I've looked at putting it on the parent `Struct` `CtxCli` before, since the command is a field there, however this requires you to specify the flag _before_ the subcommand.

e.g. instead of `wash ctx list --directory $HOME/.wash/contexts` you'd have to do `wash ctx --directory $HOME/.wash/contexts list`

2021-11-05 12:27 UTC, brooksmtownsend commented on src/ctx/mod.rs
> +    directory: Option<PathBuf>,
And IMO one of the biggest pain points of CLIs are positional arguments or flags that need to be in the correct place, so I figured a bit of copy-paste saves the user the pain

2021-11-05 18:37 UTC, thomastaylor312 commented on src/ctx/mod.rs
> +    directory: Option<PathBuf>,
Yeah, that sounds fine to me

2021-11-08 15:43 UTC, brooksmtownsend commented
With the 2 recent commits, `wash ctx` now attempts to find the host configuration file in `~/.wash/host_config.json` and transform it into a context named `host_config`. This context will be set as the default if there is not already one present _and_ will be updated each time the user runs a control interface/RPC command to ensure that `wash` always connects to the local host by default and responds to any configuration changes.

So, to recap, the user launches an OTP host with custom configuration using `./bin/wasmcloud_host start`. Since this is the first run, a `host_config.json` file is created in the same directory the user ran that command, as well as in `~/.wash/` for later usage.

Now, once the host is running, the user runs `wash ctl get hosts` in order to find the host ID. Because no contexts exist, we find the `host_config.json` in `~/.wash/host_config.json` and create a context from the values there and immediately use it for that command. The net result here that anytime a local user changes the host configuration and launches a local host, `wash` is immediately configured to interact with that host.

As mentioned above, `wash ctx` also has the ability to manage different contexts for remote clusters of hosts, and those can be managed manually with the other subcommands.

2021-11-08 16:26 UTC, brooksmtownsend commented
Converting this back to draft as there are some more kinks to work out

2021-11-10 03:15 UTC, stevelr commented
will this work in the use case where you want to run more than one host on the same machine - simultaneously?

2021-11-10 14:59 UTC, stevelr commented
Based on the order of precedence defined in https://github.com/wasmCloud/wasmcloud-otp/issues/245 multiple hosts should work. If they are read only.

If the home dir file is overwritten, it doesn't work.

2021-11-10 22:28 UTC, brooksmtownsend commented
> will this work in the use case where you want to run more than one host on the same machine - simultaneously?

@stevelr It will work if you want to run more than one host on the same machine, if they have the same config. There's nothing stopping you from launching multiple hosts with different configurations, however the `wash ctx` managed `host_config` context will always be pointing to the _latest_ launched host configuration. In this case I'd recommend the user managing contexts on their own rather than using the managed one

2021-11-12 20:15 UTC, autodidaddict requested changes
Just to avoid deserialization warnings, can you add the `js_domain` field to your context struct?

2021-11-12 20:18 UTC, brooksmtownsend commented
> Just to avoid deserialization warnings, can you add the `js_domain` field to your context struct?

@autodidaddict I certainly can, it won't be needed for any connectivity configurations will it? I did test that the Context struct would be able to deserialize from the `host_config.json` even if it included extra fields, e.g. `allowed_insecure`

2021-11-12 20:26 UTC, autodidaddict commented
Ok if it deserializes fine then no need. That field is not needed to contact hosts

2021-11-12 20:48 UTC, autodidaddict approved these changes

2021-11-12 22:30 UTC, merged