Adopt common naming convention with OTP host
wasmCloud/wash-archive pull request #198
Opened 2021-11-11 04:55 UTC by byblakeorriver

Changes the environment variable names in the wash CLI to match the ones that would be set in OTP host. 
Also, variable names with more than a prefix change had their underlying struct fields changed to match their new names.
Also changed the timeout conventions to use milliseconds instead of seconds.

Should resolve: https://github.com/wasmCloud/wash/issues/195

2021-11-11 04:59 UTC, byblakeorriver commented on src/call.rs
> +        short = "x",
Used `x` here. I still need to verify that `l` cannot be used. I saw that it was used here: https://github.com/wasmCloud/wash/blob/main/src/ctl/mod.rs#L193

2021-11-11 12:22 UTC, brooksmtownsend requested changes
This code LGTM, though you'll have to sign the DCO for checks to pass. @byblakeorriver the instructions for how to do this can be found in the `Details` section of the DCO check

2021-11-11 13:10 UTC, autodidaddict commented
LGTM as well, just waiting for the DCO check

2021-11-11 17:28 UTC, byblakeorriver commented
Cool, got that part fixed. Are you all ok with using x as the short code for lattice-prefix?

2021-11-12 02:02 UTC, brooksmtownsend commented
> Cool, got that part fixed. @brooksmtownsend, are you all ok with using x as the short code for lattice-prefix?

Yeah X is fine with me, as far as I know it's only used on the "claims" subcommand so you should be good there

2021-11-12 13:42 UTC, brooksmtownsend approved these changes

2021-11-12 13:43 UTC, merged