Continued CLI design
wasmCloud/wash-archive pull request #2
Opened 2020-10-07 17:57 UTC by brooksmtownsend

This PR moves the `sign` subcommand under `wcc claims`, as well as specifies more defaults for `wcc claims sign` to enable an easier initial onboarding to signing `wasm` files in wascc projects.

2020-10-07 22:49 UTC, autodidaddict approved these changes

2020-10-07 22:49 UTC, autodidaddict commented on README.md
> +    -i, --issuer <issuer-key-path>      Issuer seed key path (usually a .nk file). If this option is left off, `wcc` will attempt to locate an account key at `$HOME/.wcc/keys/<project_name>_account.n
I think we decided instead of using the project name it would be the name of the wasm file being signed, with either an account or module suffix

2020-10-07 22:49 UTC, autodidaddict commented on README.md
> +    -d, --directory <keysdirectory>     The directory where keys are stored for listing. Defaults to `$HOME/.wcc/keys`, and can be overwritten by setting the WCC_HOME environment variable.
If the directory is either the default or something overridden by an environment variable then we probably don't need a separate flag for this option?

2020-10-07 23:26 UTC, brooksmtownsend commented on README.md
> +    -d, --directory <keysdirectory>     The directory where keys are stored for listing. Defaults to `$HOME/.wcc/keys`, and can be overwritten by setting the WCC_HOME environment variable.
Hm, I want the experience to be consistent across the different commands. I think I see two options here for all the commands:

1. Allow the `WCC_HOME` environment variable to override the directory and document accordingly
2. Provide the `-d, --directory` option on all subcommands that would make use of generated keys

Thoughts on either?

2020-10-07 23:48 UTC, autodidaddict commented on README.md
> +    -d, --directory <keysdirectory>     The directory where keys are stored for listing. Defaults to `$HOME/.wcc/keys`, and can be overwritten by setting the WCC_HOME environment variable.
WWKCD? What would kubectl do? I think it uses an environment variable to choose which context you're working with.

How about this:
Use the WCC_HOME directory if it's supplied 
Use HOME/.wcc if that variable isn't set
Override that location if the directory flag is passed.

So its an order if precedence,  with the -d flag trumping all?

?

2020-10-09 15:45 UTC, thomastaylor312 commented on README.md
> +    -d, --directory <keysdirectory>     The directory where keys are stored for listing. Defaults to `$HOME/.wcc/keys`, and can be overwritten by setting the WCC_HOME environment variable.
FWIW in Helm we eventually decided to use the [XDG directory spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) as it is fairly standard across all platforms. You can take a look at how we did it in Helm if you are interested

2020-10-09 15:45 UTC, thomastaylor312 commented on README.md
> +    -i, --issuer <issuer-key-path>      Issuer seed key path (usually a .nk file). If this option is left off, `wcc` will attempt to locate an account key at `$HOME/.wcc/keys/<project_name>_account.n
I feel like that could get cluttered real fast. Is it best practice to have a different key for each wasm file?

2020-10-09 15:48 UTC, thomastaylor312 approved these changes
I think this arrangement is much better logical grouping. This looks good to me, but please see the comment in response to @autodidaddict about using the XDG spec

2020-10-09 16:05 UTC, autodidaddict commented
I'll take a look at the XDG spec.

Also - yes every wasm file requires two keys to sign - one for the issuer and one for the subject. Every wasm module has a globally unique public key. If you signed multiple modules with the same key, they would have the same identity and would appear as the same entity to a host runtime.

2020-10-13 14:02 UTC, brooksmtownsend commented on README.md
> +    -i, --issuer <issuer-key-path>      Issuer seed key path (usually a .nk file). If this option is left off, `wcc` will attempt to locate an account key at `$HOME/.wcc/keys/<project_name>_account.n
I can see the argument from the security perspective that we wouldn't want one set of keys to sign many different projects... You could always override it with your own account and module keys if you dislike the clutter but the average user wouldn't need to interact with their `~/.wcc` directory if they didn't want to.

2020-10-13 14:06 UTC, brooksmtownsend commented on README.md
> +    -d, --directory <keysdirectory>     The directory where keys are stored for listing. Defaults to `$HOME/.wcc/keys`, and can be overwritten by setting the WCC_HOME environment variable.
Do we want to mention the `WCC_HOME` env var in the CLI as well? I don't mind having multiple ways to override the directory and the documentation can reference relevant environment variables, but assuming we want `wcc` to be usable in scripting the `-d` flag is nice to have to not deal with environment

2020-10-13 14:07 UTC, brooksmtownsend commented
@autodidaddict Do we want to remove the `gantry` section of the CLI specification? We can replace it with a subcommand that interacts with an OCI compliant registry, but I'm not sure what that would look like atm

2020-10-13 14:22 UTC, autodidaddict commented
Remove references to gantry and we can maybe just use oci push and pull

2020-10-14 14:03 UTC, brooksmtownsend commented
@autodidaddict please review latest changes for wash and OCI

2020-10-14 14:06 UTC, autodidaddict requested changes

2020-10-14 14:06 UTC, autodidaddict commented on README.md
> +    wash oci <SUBCOMMAND> <artifact>
Maybe this is more friendly as `registry` or `reg` for short. `oci` is a technical distinction that might add learning friction to developers?

2020-10-14 14:07 UTC, brooksmtownsend commented on README.md
> +    wash oci <SUBCOMMAND> <artifact>
Good call, renamed

2020-10-14 14:10 UTC, autodidaddict approved these changes

2020-10-14 14:13 UTC, merged