Initial Implementation of OCI push and pull commands
wasmCloud/wash-archive pull request #20
Opened 2020-11-19 21:58 UTC by brooksmtownsend

This currently depends on a relative path to the `oci-distribution` crate as the `push` PR has not been merged and released yet.

This PR contains an implementation of `wash reg push` and `wash reg pull`, two commands for interacting with OCI compliant registries. As this tool is the `waSCC Shell`, I have restricted `push` and `pull` operations to only work for `waSCC` provider archives (with claims) and `waSCC` signed actors. You can read more about this decision in the proposed PR to our ADR [here](https://github.com/wascc/adr/pull/1/files#diff-caa31b5aee04ae6b39babdc1381aa6fff44281e23408d99838ecb5ac819644f7).

You can test pulling an artifact simply with:
```
wash reg pull wascc.azurecr.io/test/hello:v1
```
This syntax for the tag supports image tag, digest, or both. `latest` is not allowed unless you supply the `--allow-latest` flag.

You can test pushing an artifact (as long as you have credentials) with:
```
export WASH_REG_USER=<username>
export WASH_REG_PASSWORD=<password>
wash reg push wascc.azurecr.io/test/hello:v2 ./hello_signed.wasm
```

Tests forthcoming, I wanted to publish this PR for initial comments before I spent too much time there.

Fixes #19

🚿

2020-11-19 22:18 UTC, autodidaddict requested changes
Just one suggested change to extract the common options from push and pull and move them up to `reg`

2020-11-19 22:18 UTC, autodidaddict commented on src/reg.rs
> +    user: Option<String>,
If you move the user and password, insecure, and allow latest up to the `RegCliCommand` struct then they'll show up as options for `reg` rather than having to duplicate them for each of the reg commands. It's not a huge deal, but it makes the help output and bad syntax error messages a little easier to read, and saves you a little on destructuring.

2020-11-19 22:18 UTC, autodidaddict commented on src/reg.rs
> +        SHOWER_EMOJI,
:heart:

2020-11-20 12:55 UTC, brooksmtownsend commented
Due to the dependency on `krustlet`, marking this as `do not merge` until the oci-distribution crate has the `push` functionality released. If we merge before then, users will not be able to install wash via `cargo install wash-cli` due to the relative dependency

2020-12-02 19:06 UTC, brooksmtownsend commented
@autodidaddict @billyoung @ChrisRx Any other remaining concerns? I'd like to have `wash` pointing to the main krustlet repo, but as `wash up` and other issues get fixed I can see merge conflicts getting harder to diagnose, so I'm settling for pointing to my `krustlet` repo for now

2020-12-03 16:13 UTC, merged