introduce ClusterSeed
wasmCloud/wash-archive pull request #202
Opened 2021-11-19 11:04 UTC by StuartHarris

This PR implements some more of https://github.com/wasmCloud/wash/issues/192 by introducing `ClusterSeed` for the `wash call` command args and interactive input.

Note there is a remaining question about what a default ClusterSeed should be (if anything), as this was previously an empty string (which won't parse now).

- [x] introduce `ClusterSeed`
- [ ] write some unit tests for `Id` and `Seed` parsing
- [ ] revisit `ClusterSeed::default()` (should probably use `None`)

2021-11-19 14:59 UTC, StuartHarris commented
Accidentally pulled some older commits onto this branch. Ooops! Just trying to fix it now :-)

2021-11-22 11:33 UTC, StuartHarris commented
@brooksmtownsend opening this up for review, but would love to get your opinion on what `ClusterSeed::default()` should be. Before, it was an empty string (although not in a happy code path), so it may not matter what it is in reality (but I had to make it something that would now parse, so I made is `SC` + 54 x `0` :-)

2021-11-22 14:46 UTC, autodidaddict submitted a review, later dismissed
LGTM, though I'd like @brooksmtownsend to double-check this to make sure it works fine in conjunction with the automatic configuration reading `~/.wash/host_config.json`

2021-11-23 00:59 UTC, brooksmtownsend requested changes
As far as I can tell this looks good with `wash ctx`. Turns out seed keys are 58 characters so valid keys won't parse with this iteration. After doing some testing I found a few more requests.

2021-11-23 00:59 UTC, brooksmtownsend commented on src/id.rs
> +    }
I did a bit of investigating while testing, looks like the seed keys are 58 characters and the public keys are 56 characters. You may need to define the count as separate constants and create that after reading the prefix

2021-11-23 00:59 UTC, brooksmtownsend commented on src/id.rs
> +mod tests {
You'll probably need to add 2 more `0`s here for the proper test after making the above change

2021-11-23 00:59 UTC, brooksmtownsend commented on src/call.rs
> +                    ClusterSeed::default()
Weirdly enough, this makes actor calls without a cluster seed give me this error:
```
Error invoking actor: Invalid seed length: Bad seed length: 56
```

This is an error from the NATS client when providing the seed, I don't have a particularly strong preference if you want to handle that as an error or simply use the blank string instead.

2021-11-23 08:33 UTC, StuartHarris commented on src/id.rs
> +    }
Thanks for catching this @brooksmtownsend! This should be fixed now.

2021-11-23 10:50 UTC, StuartHarris commented on src/call.rs
> +                    ClusterSeed::default()
This should be 58 now, so I'd be interested in what the NATS error becomes (I wasn't sure how to test this).

2021-11-24 01:31 UTC, brooksmtownsend commented on src/call.rs
> +                    ClusterSeed::default()
The error shown now is:
```
Error invoking actor: Codec failure: Data encoding failure: invalid symbol at 2
```

Which is unfortunately not very descriptive, and I believe due to the `0` in the default cluster seed 🤔 
Why don't we just change the `ClusterSeed::default()` to be a legitimate cluster seed, that doesn't really correspond to anything. That way we can get down to handling and displaying actual errors, and if the user disables antiforgery checks (e.g. if they are writing their own host runtime) then it shouldn't matter anyways.

Here's a legitimate, but just generated by my CLI and unused, cluster seed:
```
SCAMSVN4M2NZ65RWGYE42BZZ7VYEFEAAHGLIY7R4W7CRHORSMXTDJRKXLY
```

I'd be interested to know if @autodidaddict thinks differently about this problem

2021-11-24 09:35 UTC, StuartHarris commented on src/call.rs
> +                    ClusterSeed::default()
Also interested in your opinion @autodidaddict. I don't think there's a nice solution. Ideally, since it wraps a String, the Seed's default should wrap String's default. But that won't parse, and if we went that way we'd be losing some of the safety that the type provides. I've made the change that @brooksmtownsend suggested, but we can revert that commit if you think there's a better way.

2021-11-30 14:37 UTC, autodidaddict commented on src/call.rs
> +                    ClusterSeed::default()
I think `ClusterSeed::default()` should be the same as string default.. and then code elsewhere can/should validate empty/improperly formed seeds.

2021-11-30 15:08 UTC, autodidaddict approved these changes

2021-11-30 15:22 UTC, brooksmtownsend approved these changes

2021-11-30 15:23 UTC, merged