feat(*): fetch from wasmcloud cache on inspect commands
wasmCloud/wash-archive pull request #204
Opened 2021-11-21 19:05 UTC by matthewtgilbride

2021-11-21 19:54 UTC, brooksmtownsend reviewed
Great stuff @matthewtgilbride, really only had one nit comment here.

2021-11-21 19:54 UTC, brooksmtownsend commented on src/claims.rs
> +                from_cache.read_to_end(&mut buf).unwrap();
Definitely a nit, but I think I'd prefer this variable to be called something like `cached_artifact` since `from` is a Rust keyword

2021-11-21 19:54 UTC, brooksmtownsend commented on src/par.rs
> +                from_cache.read_to_end(&mut buf).unwrap();
Same `from` nit here

2021-11-21 21:52 UTC, matthewtgilbride commented
> Great stuff @matthewtgilbride, really only had one nit comment here.

Thanks @brooksmtownsend - renamed things to "local_artifact" and "cached_artifact - along moving the local/cache/remote helper to `reg.rs`.  I'm wondering what the best way to test this is?  I was thinking of jamming the `echo.wasm` file into the cache directory similarly to how it's added to the local directory [here](https://github.com/wasmCloud/wash/blob/a9f980c71a9f9e62ab53ab031ddf2a3a34889b53/tests/integration_claims.rs#L16).  Then I was going to add a call with a bogus registry host e.g. `foobar:5000` to see if it would get pulled from the cache.  Feels a bit awkward...thoughts?

2021-11-22 17:26 UTC, brooksmtownsend commented
> Thanks @brooksmtownsend - renamed things to "local_artifact" and "cached_artifact - along moving the local/cache/remote helper to `reg.rs`.
> 
> I'm wondering what the best way to test this is? I was thinking of jamming the `echo.wasm` file into the cache directory similarly to how it's added to the local directory [here](https://github.com/wasmCloud/wash/blob/a9f980c71a9f9e62ab53ab031ddf2a3a34889b53/tests/integration_claims.rs#L16). Then I was going to add a call to get the remote actor before the `push` command to see if it would get pulled from the cache. Feels a bit awkward...thoughts?

I think that's a good idea, a good baseline would be a unit test just to verify:
```
should produce a file like wasmcloud_azurecr_io_kvcounter_v1.bin
```

One great way you could test this is exactly what you suggested, throw the `echo.wasm` in the temp directory under a name like `fakeoci_io_echo_v1.bin` and then try to inspect `faceoci.io/echo:v1` and even though that doesn't exist, the cached file should be retrieved instead

2021-11-22 22:35 UTC, brooksmtownsend requested changes
This LGTM @matthewtgilbride, just need the DCO fix 😄 If you check the workflow details it'll tell you the command you can run

2021-11-22 23:03 UTC, matthewtgilbride commented
👍 think I'm ready

2021-11-23 00:30 UTC, brooksmtownsend requested changes
I thought of one more request... could you also add a test for the provider so that we test that works as well? I figure having a `wash claims inspect` + `wash par inspect` would be great

2021-11-25 13:37 UTC, matthewtgilbride commented
> I thought of one more request... could you also add a test for the provider so that we test that works as well? I figure having a `wash claims inspect` + `wash par inspect` would be great

🦃 done

Interestingly the `wash par inspect` integration tests are _really_ slow.  Way slower than it should take to download/push the httpclient provider a couple of times.  🤔

2021-11-25 14:30 UTC, brooksmtownsend commented
> Interestingly the `wash par inspect` integration tests are _really_ slow.  Way slower than it should take to download/push the httpclient provider a couple of times.  🤔 

That's a fun one actually that we worried about as we started, turns out the whole compress/decompress part of the gzip library we use is SUPER slow in debug mode, so hopefully if we try with release mode that doesn't reproduce

2021-11-29 22:47 UTC, brooksmtownsend approved these changes
This LGTM, and should be ready to merge as soon as the tests run and pass 🚀

2021-11-29 23:45 UTC, merged