remove billyoung from CODEOWNERS
wasmCloud/wash-archive pull request #206
Opened 2021-11-22 03:52 UTC by stevelr

Signed-off-by: stevelr <steve@cosmonic.com>

2021-11-22 11:20 UTC, brooksmtownsend requested changes
We can probably remove ChrisRX too, and add you and @thomastaylor312

2021-11-22 14:24 UTC, autodidaddict submitted a review, later dismissed
Remove ChrisRx and add Taylor

2021-11-24 12:29 UTC, brooksmtownsend approved these changes

2021-11-30 17:07 UTC, stevelr commented
LGTM, but I can't approve this since I created this pr

2021-11-30 17:08 UTC, merged