feat(ctl): warning if contract ID looks like an nkey
wasmCloud/wash-archive pull request #214
Opened 2021-12-08 22:32 UTC by matthewtgilbride

2021-12-09 23:13 UTC, brooksmtownsend requested changes

2021-12-09 23:13 UTC, brooksmtownsend commented on src/ctl/mod.rs
> +    }
I like the idea of this, though I think that this will never actually work because one string couldn't be `Ok(_)` parsed to be a module ID, service ID, or serverId

You could restructure this just a bit though, you could do a simple `if ModuleId::from_str().is_ok() || ServiceId::from_str().is_ok() || ...` in order to just check if any of them parse correctly and that would work. Though honestly, I think a fine amount of rigor here is checking if the contract ID is a 56 character alphanumeric uppercase string. Contract IDs are a convention to be something like `wasmcloud:httpserver`, and I think it's highly unlikely anyone seriously uses a contract ID of `THISISASQLDBPROVIDERANDITSTHEFIRSTVERSIONOFMANYTOCOMEHAH` as a contract ID.

TL;DR, I think you'd be fine just asserting that it's not a 56 length string with all uppercase letters and numbers.

2021-12-12 17:31 UTC, matthewtgilbride commented on src/ctl/mod.rs
> +    }
Agreed.  Take a look now...sorry for the delay 👍

2021-12-12 18:04 UTC, matthewtgilbride commented on src/ctl/mod.rs
> +    }
Added a validation of the `ctl stop` command as well...two questions:

1. Am I handling sending output to the user how we want to?  The `link_del_output` and `link_put_output` commands format the json message under an `error` key...maybe it should be `warning`?
2. Are there any other validations we wanted to handle as part of #192?

2021-12-13 14:59 UTC, brooksmtownsend requested changes

2021-12-13 14:59 UTC, brooksmtownsend commented on src/ctl/mod.rs
> +            .all(|c| char::is_alphanumeric(c) && char::is_uppercase(c))
I think here we probably _technically_ want [is_ascii_alphanumeric](https://doc.rust-lang.org/std/primitive.char.html#method.is_ascii_alphanumeric), though I'm not sure if we'd ever hit that edge case.

2021-12-13 14:59 UTC, brooksmtownsend commented on src/ctl/mod.rs
> +fn validate_contract_id(contract_id: &str) -> Option<&str> {
I'd suggest making the return type of this function a `Result<()>`, using the `crate::util::Result`. That way, you can either return `Ok(())` if it's a valid contract ID, and then `Err("It looks like you ...")` if not.

Doing this lets you do simple things like:
```
validate_contract_id("wasmcloud:httpserver")?;
// do a link put
```

which will then bubble up the error if it exists, or otherwise validate the contract ID and continue execution

2021-12-13 14:59 UTC, brooksmtownsend commented on src/ctl/mod.rs
> +    });
See suggestion about `validate_contract_id` returning `Result<()>`, that way you can just call the function and use `?` to bubble up the error. You don't actually need the `format_output` thing here, we don't currently consistently return json output for errors and should make another issue for that

2021-12-13 14:59 UTC, brooksmtownsend commented on src/ctl/mod.rs
> +            });
See suggestion about validate_contract_id returning Result<()>, that way you can just call the function and use ? to bubble up the error. No need for `link_put_output` here as it only returns a formatted string

2021-12-13 14:59 UTC, brooksmtownsend commented on src/ctl/mod.rs
> +            validate_contract_id(&cmd.contract_id).map(|message| {
Same comments as above, this can just be a `validate_contract_id` call without the `link_del_output` call

2021-12-13 15:06 UTC, brooksmtownsend commented on src/ctl/mod.rs
> +    });
https://github.com/wasmCloud/wash/issues/217 (other issue that I wrote up)

2021-12-13 15:22 UTC, brooksmtownsend commented on src/ctl/mod.rs
> +    }
1. I think I addressed this in the comments, but I don't believe you need to use the `link___output` functions for your error formatting and a `?` will suffice just fine
2. I think that the only other change I'd want to see for #192 is validating the actor ID for `wash call`

2021-12-14 22:59 UTC, stevelr commented on src/ctl/mod.rs
> +            .all(|c| char::is_alphanumeric(c) && char::is_uppercase(c))
is_uppercase('1') would return false
so you probably need something like
```contract_id.chars().all(|c| c.is_ascii_digit() || c.is_ascii_uppercase());```

2021-12-27 21:01 UTC, matthewtgilbride commented
@brooksmtownsend apologies for the holiday delay 🌲 - have a look when you have another chance.

2021-12-27 21:03 UTC, matthewtgilbride commented on src/call.rs
> +    pub(crate) actor_id: ModuleId,
Is this all that's necessary?  I'm presuming the `structopt` crate will throw an error if the argument can't be parsed to a `ModuleId`? Clever indeed...

2021-12-27 21:10 UTC, autodidaddict commented on src/call.rs
> +    pub(crate) actor_id: ModuleId,
Yeah this works because of trait magic. Since `ModuleId` implements `from_str`, structopt automatically knows how to parse it from the command line: https://github.com/wasmCloud/wash/blob/cf6126436301f943a58a6dbc778014c093988307/src/id.rs#L22

2021-12-27 21:13 UTC, autodidaddict commented
Current build failure (test fail):
```
```

2021-12-28 17:39 UTC, matthewtgilbride commented
> Current build failure (test fail):
> 
> ```
>     --> src/call.rs:399:17
>     |
> 399 |                 assert_eq!(actor_id, ACTOR_ID);
>     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `Id`, found `&str`
>     |
>     = note: expected struct `Id<'M'>`
>             found reference `&str`
>     = note: this error originates in the macro `assert_eq` (in Nightly builds, run with -Z macro-backtrace for more info)
> ```

fixed

2022-01-04 13:46 UTC, autodidaddict approved these changes

2022-01-04 15:48 UTC, brooksmtownsend approved these changes

2022-01-04 15:48 UTC, merged

2022-01-04 15:48 UTC, brooksmtownsend commented
Thanks @matthewtgilbride !