use lattice controller client & wasmbus linked to nats-aflowt
wasmCloud/wash-archive pull request #226
Opened 2022-01-13 06:32 UTC by stevelr

2022-01-13 14:19 UTC, autodidaddict submitted a review, later dismissed

2022-01-13 14:32 UTC, brooksmtownsend requested changes, later dismissed
just a request to bump to `0.8.0` as we've had breaking changes make it into main

2022-01-13 14:32 UTC, brooksmtownsend commented on Cargo.toml
> +version = "0.7.3"
Let's go ahead and bump this to `0.8.0`. This itself isn't really a breaking change, BUT there have been breaking changes since `0.7.2` and we need to release `0.8.0` to compensate

2022-01-13 14:32 UTC, brooksmtownsend commented on src/ctl/mod.rs
> +    let timeout_ms = match (opts.timeout_ms, opts.timeout) {
we're bumping to `v0.8.0` here, I don't have a preference if we push the deprecation back to `v0.9.0` or just remove it now

2022-01-13 20:05 UTC, stevelr commented on Cargo.toml
> +version = "0.7.3"
done

2022-01-14 01:32 UTC, stevelr commented on src/ctl/mod.rs
> +    let timeout_ms = match (opts.timeout_ms, opts.timeout) {
removed deprecated timeout flags

2022-01-14 14:42 UTC, brooksmtownsend approved these changes
Big fan of the structopt -> clap changes with subcommand

2022-01-14 17:09 UTC, merged