Issue 57 - Use indicatif instead of spinners library for command line waiting spinner
wasmCloud/wash-archive pull request #246
Opened 2022-03-07 05:20 UTC by byblakeorriver

Signed-off-by: bwilloughby <bwilloughby@demark.com>

2022-03-07 05:45 UTC, byblakeorriver commented
@brooksmtownsend I think this one is ready to go. Let me know if you have any concerns with the way I did it.

2022-03-07 15:06 UTC, brooksmtownsend requested changes
Overall this looks awesome! Cleans up the code and our dependencies 😄 

I did notice one quirk about using the `reg` functions, it looks like there is an extra line with one dot that gets printed, see picture.
<img width="471" alt="image" src="https://user-images.githubusercontent.com/12040685/157055498-b36956db-2b21-47ee-b990-ea296ff04d9a.png">

I don't see the same thing with the `ctl` commands, perhaps it's due the the info log that I reference in my review?

I also tested this on Windows in Powershell and it worked well, just see my comment around the blue spinner.

2022-03-07 15:06 UTC, brooksmtownsend commented on src/reg.rs
> +    info!("{}", msg);
I think this can be removed and might be causing the issue I can reproduce

2022-03-07 15:06 UTC, brooksmtownsend commented on src/reg.rs
> +    info!("{}", msg);
I think this can be removed and might be causing the issue I can reproduce

2022-03-07 15:06 UTC, brooksmtownsend commented on src/appearance/spinner.rs
> +                    .template("{spinner:.blue} {msg}");
The blue looks great in my terminal, but on Windows Powershell the default background color is blue so it's mostly invisible. I think a mid-gray might be a better option so that it shows on all colors including light themes

2022-03-07 18:39 UTC, byblakeorriver commented on src/appearance/spinner.rs
> +                    .template("{spinner:.blue} {msg}");
Gotchya!

2022-03-07 18:40 UTC, byblakeorriver commented on src/reg.rs
> +    info!("{}", msg);
I thought these might cause some trouble. I didn't know if the logging was there for any particular reason so I kept them. I will get it cleaned up.

2022-03-08 02:26 UTC, byblakeorriver commented
@brooksmtownsend can you give this last commit a try when you get a chance? I tried to recreate your issue, but was not able to get it to occur. I tried on two terminals (alacritty and the default pop_os terminal). I also tried both of those using the fish shell to see if that could maybe reproduce it. 

I did however find an issue if the terminal window is really small. It would print the message over and over again. I fixed that using the wide_msg template setting in the indicatif lib. Maybe that could have something to do with it.

I did get the color changed. I couldn't find a specific option for the gray, but I did find a way to make it bold and dim. Let me know what you think. I also added a prefix of (>>>) not sure if that is ok with you. It could be anything. An emoji or just a couple spaces.

2022-03-08 02:37 UTC, byblakeorriver commented
I was able to find a way to choose any of these colors: https://www.ditig.com/256-colors-cheat-sheet

If you don't like the bold dim version, I change the colors, just need some artistic advice on which one to choose.

2022-03-08 13:17 UTC, autodidaddict approved these changes

2022-03-08 19:09 UTC, brooksmtownsend approved these changes
This is great, and I didn't even know we could fix the printing over and over again issue 😄

2022-03-08 19:09 UTC, merged