Added support for oci manifest annotations
wasmCloud/wash-archive pull request #257
Opened 2022-04-22 21:43 UTC by brooksmtownsend

Certain registries, like [GHCR](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) depend on OCI manifest annotations in order to perform special actions. In Github's case, adding an annotation of `org.opencontainers.image.source=<your_repo>` will automatically associate a package (actor/provider) with a github repository.

I think this is _technically_ a minor bump but I left it as a patch since it's so small. Feel free to request that I change that, and I can change to `0.11.0-alpha.1` instead to indicate new features

Signed-off-by: Brooks Townsend <brooks@cosmonic.com>

2022-04-25 20:41 UTC, thomastaylor312 requested changes
LGTM.

However, I think we should make sure we follow strict semver here (even though it is annoying) as it is a feature add. Although it probably doesn't _actually_ matter here, it does give future users confidence that they know what they are getting with each version

2022-04-25 20:41 UTC, thomastaylor312 commented on src/reg.rs
> +/// Modified version of oci_distribution::generate_manifest to support additional annotations
Might just want to upstream this change to oci-distribution as we can't be the only one wanting to add multiple annotations

2022-04-26 13:07 UTC, brooksmtownsend commented on src/reg.rs
> +/// Modified version of oci_distribution::generate_manifest to support additional annotations
I'm down to contribute upstream and then remove this function once it is released 👍🏻

2022-04-26 13:14 UTC, brooksmtownsend commented on src/reg.rs
> +/// Modified version of oci_distribution::generate_manifest to support additional annotations
re-reading upstream, I actually don't think that this belongs in `oci_distribution`. I'm really just reusing some of the logic since I need to generate my own manifest, `oci_distribution` will call `generate_manifest` if you haven't supplied one.

2022-04-26 23:10 UTC, thomastaylor312 approved these changes

2022-04-27 14:04 UTC, merged