add codegen for TinyGo actors
wasmCloud/wash-archive pull request #272
Opened 2022-05-23 01:48 UTC by stevelr

Signed-off-by: stevelr <steve@cosmonic.com>

Updates dependency on weld-codegen to 0.4.4 which is in PR https://github.com/wasmCloud/weld/pull/100

2022-05-23 11:49 UTC, autodidaddict commented
Will review this when the relative path dependency is gone

2022-05-23 20:53 UTC, stevelr commented
Build checks won't pass until  https://github.com/wasmCloud/weld/pull/100 is merged. Then, we can remove the relative path and re-trigger the build checks.

2022-05-24 14:56 UTC, autodidaddict approved these changes, later dismissed

2022-05-24 15:11 UTC, brooksmtownsend approved these changes, later dismissed
Good to go once weld-codegen is released

2022-05-24 19:47 UTC, brooksmtownsend requested changes
only a little nit

2022-05-24 19:47 UTC, brooksmtownsend commented on .rustfmt.toml
> +#imports_granularity = "Crate"
Let's just remove this if we don't want it

2022-05-24 19:52 UTC, stevelr commented on .rustfmt.toml
> +#imports_granularity = "Crate"
Deleted. 
(I like it, but on rust stable it isn't supported and unrecognized options cause a hard fail)

2022-05-24 20:04 UTC, brooksmtownsend approved these changes

2022-05-24 20:24 UTC, merged