Initial implementation of experimental wadm client
wasmCloud/wash-archive pull request #285
Opened 2022-06-10 12:02 UTC by autodidaddict

Signed-off-by: Kevin Hoffman <autodidaddict@users.noreply.github.com>

2022-06-10 12:13 UTC, autodidaddict commented
Note: normally I'd put in unit tests that verify that the command line goes to the right place, but since this is so early and experimental, I figure the commands will be changing drastically enough that it made sense to hold off on that until the interface stabilizes a bit.

2022-06-10 20:42 UTC, connorsmith256 requested changes
Looks good, with a couple suggestions for `mod.rs`:
- group helper functions in order, preferably following the order in the `handle_command` match block. I had to jump around a bit
- there's a lot of repeated code in setting up for a call to `json_request`. Could `json_request` take a `ConnectionOpts` and extract that info itself, similar to how we construct a client in `call`/`ctl`?

2022-06-10 20:42 UTC, connorsmith256 commented on src/app/mod.rs
> +    source: PathBuf,
Does this need a `clap` attribute?

2022-06-13 17:30 UTC, thomastaylor312 approved these changes, later dismissed
All nits since this is an initial implementation

2022-06-13 17:30 UTC, thomastaylor312 commented on src/app/mod.rs
> +            sp.update_spinner_message(" Querying app spec list ...".to_string());
Nit: Unintentional extra space at the beginning?

2022-06-13 17:30 UTC, thomastaylor312 commented on src/app/mod.rs
> +    let timeout = Duration::from_millis(cmd.opts.ack_timeout_ms);
Nit: I see this and the prefix unwrap in almost every function. Perhaps you could have the nats client function return a tuple with the client and timeout

2022-06-13 17:30 UTC, thomastaylor312 commented on src/app/mod.rs
> +    let topic = format!("wadm.api.{}.model.undeploy.{}", prefix, cmd.model_name);
Nit: Consider creating a `generate_topic` function that just takes the prefix, noun, and model name to avoid similar copy/pastes

2022-06-13 17:30 UTC, thomastaylor312 commented on src/app/mod.rs
> +    if res.is_some() {
Can be shortened to `Ok(res.is_some())`.

2022-06-13 17:30 UTC, thomastaylor312 commented on src/app/mod.rs
> +    let json_path = Path::new(&json_filename);
These are unnecessary as `String` implements `AsRef<Path>`

2022-06-13 17:30 UTC, thomastaylor312 commented on src/app/mod.rs
> +    let json_path = Path::new(&json_filename);
Super nit: You could create these as `PathBuf`s and then return them as you are representing a filepath (rather than just a string). Basically it would more clearly express intent

2022-06-13 17:30 UTC, thomastaylor312 commented on src/app/mod.rs
> +    let ctl_jwt = if opts.ctl_jwt.is_some() {
All of these blocks could be written more cleanly like this:

```rust
let ctl_jwt = opts.ctl_jwt.unwrap_or_else(|| ctx.as_ref().map(|c| c.ctl_jwt.clone()).unwrap_or_default())
```

There might be a way to use `and_then` as well, but you get the point

2022-06-13 17:30 UTC, thomastaylor312 commented on src/app/mod.rs
> +        bail!("{}", env.message.unwrap_or("".to_string()))
Should be `unwrap_or_else`

2022-06-30 13:23 UTC, autodidaddict commented on src/app/mod.rs
> +    source: PathBuf,
no. by leaving it off it defaults to a positional argument called `source`

2022-07-07 12:14 UTC, autodidaddict commented on src/app/mod.rs
> +    let ctl_jwt = if opts.ctl_jwt.is_some() {
going to save this for another time as when I tried to implement this, the end result ended up looking more bloated than my actual code because functions later on require an `Option<String>` and the new ctl_jwt is a string.

2022-07-07 14:17 UTC, brooksmtownsend approved these changes
This looks good for experimental 👍🏻

2022-07-07 14:47 UTC, autodidaddict commented
@connorsmith256 the latest version of this PR contains changes per your suggestion. Review blocked on your approval so where should I send the bribes?

2022-07-07 16:53 UTC, connorsmith256 approved these changes

2022-07-07 16:54 UTC, connorsmith256 commented
Damn, I should have read the comments before reviewing again. Missed opportunity for a jet ski.

2022-07-07 22:43 UTC, merged