[WIP] [FEATURE] Adding `wash-lib`, implementing `start` functionality
wasmCloud/wash-archive pull request #292
Opened 2022-07-19 21:09 UTC by brooksmtownsend

Will fix #266

This PR implements the functionality in the new `wash-lib` crate to download and start NATS and the wasmCloud host. This PR will only contribute the library functionality, tests, doctests, etc and will not actually add the functionality in the wash CLI.

The eventual goal of the `wash-lib` crate is to contain all of the library functionality that `wash` uses so that it can be re-used in other Rust projects in the wasmCloud ecosystem. We'll likely gate modules behind feature flags so that consumers of the crate can pull in only the functionality they need.

The ideal usage, from the CLI point of view, of the `wash start` command is basically that a developer using `wash` can simply run `wash start` and not worry about downloading NATS or wasmCloud, and once the command completes a local wasmCloud host will be running on `http://localhost:4000` alongside a NATS server. Flags will be provided to allow users to connect to existing NATS clusters, specify parameters to a wasmCloud host, etc.

2022-07-21 15:42 UTC, brooksmtownsend commented
Had to deal with a few last-second failures on windows (`.\bin\wasmcloud_host ping` always returns a zero exit code so I had to check for the `pong` existence) and pinging without running the script first always times out, but those should be fixed now

2022-07-21 17:01 UTC, autodidaddict submitted a review, later dismissed
:clap:

2022-07-21 19:02 UTC, thomastaylor312 requested changes
This is excellent! Very flexible and ergonomic. Just a few minor changes with some blocking things on async functions

2022-07-21 19:02 UTC, thomastaylor312 commented on .github/workflows/washlib.yml
> +    runs-on: ubuntu-latest
We should use the rust setup thing from actions-rs to make sure we have the latest version and all necessary components

2022-07-21 19:02 UTC, thomastaylor312 commented on Makefile
> +	rustfmt --edition 2021 --check src/*.rs src/*/*.rs crates/*/**/*.rs
Nit: I think we should prefer cargo fmt rather than rustfmt. It is the same thing, but I rarely see other projects use it directly

2022-07-21 19:02 UTC, thomastaylor312 commented on crates/wash-lib/Cargo.toml
> +tokio = {version = "1", features = ["full"]}
So we probably shouldn’t do full here. Because this is a library, We’re not actually starting the tokio  run time. So we should only pull in the absolutely necessary and anyone consuming the crate can enable the full tokio feature in their main cargo file

2022-07-21 19:02 UTC, thomastaylor312 commented on crates/wash-lib/src/lib.rs
> +#[cfg(feature = "start")]
Any reason to put this behind a feature flag?

2022-07-21 19:02 UTC, thomastaylor312 commented on crates/wash-lib/src/start/mod.rs
> +//!     let nats_log_file = std::fs::File::create(&nats_log_path)?;
This should be using the tokio file type since it is in an async function

2022-07-21 19:02 UTC, thomastaylor312 commented on crates/wash-lib/src/start/nats.rs
> +pub fn start_nats_server<P, T>(bin_path: P, stderr: T, port: u16) -> Result<Child>
I know that we don’t technically need this to be async, but it will almost certainly be used in an async context. The tcp connection is blocking IO and could deadlock the async stuff so this function and the stuff in it should probably use the async stuff

2022-07-21 19:02 UTC, thomastaylor312 commented on crates/wash-lib/src/start/nats.rs
> +    metadata(dir.as_ref().join(NATS_SERVER_BINARY))
Nit: you may want to check that it is actually a file as well

2022-07-21 19:02 UTC, thomastaylor312 commented on crates/wash-lib/src/start/wasmcloud.rs
> +pub async fn ensure_wasmcloud<P>(os: &str, arch: &str, version: &str, dir: P) -> Result<PathBuf>
Super Nit: the most common usage here will likely be the os and arch it is running on. What if for both here and in nats we made these parameters optional and defaulted them to the os/arch combo it is running on? Actually, an even better idea would be to have this be the “with specific os/arch” function and have another one without the os/arch that defaults to the current os/arch of the system

2022-07-21 19:02 UTC, thomastaylor312 commented on crates/wash-lib/src/start/wasmcloud.rs
> +    use futures::future::join_all;
Please put imports in the top section and not in functions pretty please

2022-07-21 19:02 UTC, thomastaylor312 commented on crates/wash-lib/src/start/wasmcloud.rs
> +
Please move up top

2022-07-21 19:02 UTC, thomastaylor312 commented on crates/wash-lib/src/start/wasmcloud.rs
> +pub fn start_wasmcloud_host<P, T, S>(
Same comment here as the function in nats. Should probably be async

2022-07-21 19:04 UTC, brooksmtownsend commented on crates/wash-lib/src/lib.rs
> +#[cfg(feature = "start")]
The idea was that each "module" of the library could be behind a feature flag, all of them are enabled by default but this would let consumers of the library choose which parts to pull in. If this is excessive optimization then I can remove that part 😄

2022-07-21 19:06 UTC, brooksmtownsend commented on crates/wash-lib/src/start/wasmcloud.rs
> +pub async fn ensure_wasmcloud<P>(os: &str, arch: &str, version: &str, dir: P) -> Result<PathBuf>
I like that second idea, it would be an uncommon use case to download for a different OS and ARCH for sure and I'd be happy to have this function use the OS/ARCH of the host, then have another helper that uses this "with specific os/arch" logic

2022-07-21 19:06 UTC, brooksmtownsend commented on crates/wash-lib/src/start/wasmcloud.rs
> +    use futures::future::join_all;
Only because you asked nicely

2022-07-21 19:08 UTC, autodidaddict commented on crates/wash-lib/src/lib.rs
> +#[cfg(feature = "start")]
I'd assumed that this let ad hoc consumers choose which pieces of wash-lib they wanted, whereas the official `wash` binary would grab all the thingz

2022-07-21 19:08 UTC, thomastaylor312 commented
Oh also, I don’t think is is breaking current wash functionality is it? Just wanted to confirm we actually needed the breaking label

2022-07-21 19:09 UTC, autodidaddict commented on crates/wash-lib/src/lib.rs
> +#[cfg(feature = "start")]
I actually like this plan of categorizing the lib by feature

2022-07-21 19:09 UTC, thomastaylor312 commented on crates/wash-lib/src/lib.rs
> +#[cfg(feature = "start")]
Ok sweet. That is what I was thinking but wanted to confirm

2022-07-21 19:10 UTC, brooksmtownsend commented
> Oh also, I don’t think is is breaking current wash functionality is it? Just wanted to confirm we actually needed the breaking label

Oh very true! I'll remove that since this is in the lib

2022-07-21 19:10 UTC, brooksmtownsend commented on Makefile
> +	rustfmt --edition 2021 --check src/*.rs src/*/*.rs crates/*/**/*.rs
Oh yeah, good call

2022-07-21 19:43 UTC, brooksmtownsend commented on crates/wash-lib/src/start/nats.rs
> +pub fn start_nats_server<P, T>(bin_path: P, stderr: T, port: u16) -> Result<Child>
Since downloading the NATS server / wasmCloud is an async context, I think that makes sense

2022-07-21 21:12 UTC, brooksmtownsend commented on crates/wash-lib/src/start/mod.rs
> +//!     let nats_log_file = std::fs::File::create(&nats_log_path)?;
I _can_ use the tokio file type, but then I have to pass in something that implements `Into<Stdio>` for the output redirecting. So this would have to look like
```rust
//!     let nats_log_file = tokio::fs::File::create(&nats_log_path).await?.into_std();
```

2022-07-21 21:21 UTC, thomastaylor312 commented on crates/wash-lib/src/start/mod.rs
> +//!     let nats_log_file = std::fs::File::create(&nats_log_path)?;
Yeah it isn’t ideal but I do know that we should try to make sure it is non-blocking. We can look if there is an async equivalent that we could use instead and do the std conversion in the function.

2022-07-21 22:10 UTC, brooksmtownsend commented on crates/wash-lib/src/start/nats.rs
> +    metadata(dir.as_ref().join(NATS_SERVER_BINARY))
`map_or` worked great for this but I wanted to use https://doc.rust-lang.org/std/result/enum.Result.html#method.is_ok_and :(

2022-07-22 18:55 UTC, thomastaylor312 requested changes
Just a few more teensy changes

2022-07-22 18:55 UTC, thomastaylor312 commented on crates/wash-lib/src/start/wasmcloud.rs
> +    if std::net::TcpStream::connect(format!("127.0.0.1:{}", port)).is_ok() {
This should use the TCP stream from tokio

2022-07-22 18:55 UTC, thomastaylor312 commented on crates/wash-lib/src/start/nats.rs
> +    if std::net::TcpStream::connect(format!("127.0.0.1:{}", port)).is_ok() {
You'll need to use the tokio one here as you are async

2022-07-22 18:55 UTC, thomastaylor312 commented on crates/wash-lib/src/start/wasmcloud.rs~
> +use anyhow::{anyhow, Result};
Looks like this file is a possible `cp` failure/artifact?

2022-07-23 02:52 UTC, brooksmtownsend commented on crates/wash-lib/src/start/wasmcloud.rs~
> +use anyhow::{anyhow, Result};
yep, editing in windows :(

2022-07-23 04:25 UTC, thomastaylor312 approved these changes

2022-07-23 22:52 UTC, merged

2022-09-22 09:22 UTC, williamdes commented on .github/workflows/rust.yml
> +        uses: sudo-bot/action-docker-compose@latest
Thank you for using my action !
Feel free to ping me if there is an incident with it