feature: shell completions
wasmCloud/wash-archive pull request #301
Opened 2022-08-30 02:43 UTC by stevelr

Signed-off-by: stevelr <steve@cosmonic.com>

2022-08-30 11:12 UTC, stevelr commented
Todo:
 - [ ] document where to install the generated files so they can be used.

2022-08-30 14:06 UTC, brooksmtownsend requested changes
I think you have a TODO for this, just asking for more information on what to do with the completion file. It generated a file for me though 👍🏻

2022-08-30 14:06 UTC, brooksmtownsend commented on src/completions.rs
> +                format!("Generated completion file: {}", path.display()),
What do I do with it though 😄

2022-09-01 19:56 UTC, brooksmtownsend reviewed
Worked great for me in zsh, but I couldn't get this to work in Warp or in PowerShell... @thomastaylor312 have you set up a PS profile before?

2022-09-01 23:29 UTC, thomastaylor312 commented
Yes, but I have to google it every time and it is never in the place I expect

2022-09-02 20:06 UTC, stevelr commented
I had tested it in zsh, bash, and fish, but have not yet tested PowerShell.

2022-09-30 01:52 UTC, ricochet commented on Cargo.toml
> +clap_complete = "3.2.4"
Be sure to update this to the v4 version once #317 is merged.

2022-11-10 14:55 UTC, brooksmtownsend commented
@stevelr would suggest that we either wrap this up once we can verify that it works in powershell, or close this issue.

2022-11-11 03:58 UTC, stevelr commented
We should try to get it tested on PowerShell but I don't think that needs to be a blocker.

If we can't find someone to test PowerShell,  I think it's still worth releasing. It provides additive benefit for at least three other shells.

2022-11-15 15:53 UTC, brooksmtownsend commented
@stevelr sounds good, I'll give it a shot on my Windows box later, if you're able to fix the conflicts I can 👍🏻 it

2023-02-24 21:16 UTC, vados-cosmonic commented
Close in favor of https://github.com/wasmCloud/wash/pull/392 ?

2023-02-27 16:59 UTC, brooksmtownsend commented
Closing in favor of #392

2023-02-27 16:59 UTC, closed without merging