Apdated wash-lib to use mix releases and 0.57
wasmCloud/wash-archive pull request #303
Opened 2022-08-30 18:30 UTC by brooksmtownsend

Signed-off-by: Brooks Townsend <brooks@cosmonic.com>

2022-08-30 22:26 UTC, connorsmith256 commented on crates/wash-lib/src/start/wasmcloud.rs
> +    match Command::new(bin_path.as_ref()).arg("pid").output().await {
This probably doesn't matter for the majority of use cases, but I do wonder about users who want to `wash up` when a host is already runnning

2022-08-31 13:54 UTC, brooksmtownsend commented on crates/wash-lib/src/start/wasmcloud.rs
> +    match Command::new(bin_path.as_ref()).arg("pid").output().await {
Are you suggesting to add the feature to start multiple hosts, or to add better log verbosity telling the user what host is running?

2022-09-01 19:47 UTC, mattwilkinsonn reviewed
Could you change the title of the PR slightly, I thought using mix releases was the primary change, but really it is setting a version requirement at 0.57 which then runs mix releases

2022-09-01 19:47 UTC, mattwilkinsonn commented on src/up/mod.rs
> +    //TODO: evaluate necessity
Is this needed still?

2022-09-01 20:43 UTC, brooksmtownsend commented on src/up/mod.rs
> +    //TODO: evaluate necessity
I don't think so! 😄

2022-09-01 23:35 UTC, thomastaylor312 requested changes, later dismissed

2022-09-01 23:35 UTC, thomastaylor312 commented on crates/wash-lib/src/start/wasmcloud.rs
> +    if version < MINIMUM_WASMCLOUD_VERSION {
This will fail if we end up at a `0.100` version. Highly recommend we use the `semver` crate instead. 

Example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=06bdf7e362d503a1393f259d2c6689af

2022-09-02 13:57 UTC, brooksmtownsend commented on crates/wash-lib/src/start/wasmcloud.rs
> +    if version < MINIMUM_WASMCLOUD_VERSION {
Interesting! Good call

2022-09-07 15:01 UTC, ghost commented on crates/wash-lib/src/start/wasmcloud.rs
> +            // Stderr will include :nodedown if no other host is running, otherwise
I might be misreading this but isn't this code reversed? It reads to me like:
if `:nodedown` is returned, then a wasmCloud host is already running

2022-09-07 15:01 UTC, mattwilkinsonn commented on src/up/mod.rs
> +        .output()
Do we want to check the output here to make sure it stopped successfully?

2022-09-07 15:27 UTC, brooksmtownsend commented on crates/wash-lib/src/start/wasmcloud.rs
> +            // Stderr will include :nodedown if no other host is running, otherwise
It's a little weird, but the scenario is
- If a wasmCloud host is running with that node name (defaults to wasmcloud_host@localhost or similar), return a PID
- If a wasmCloud host is not running with that node name, return an RPC error containing `:nodedown`

What I want to check here is that the response does not contain `:nodedown`, which means that a PID came back instead. I did it this way instead of trying to regex for a pid.

To be fair, this block should go away soon entirely, I want to add multiple host support so that `wash up` can handle more than one mix release running at a time

2022-09-07 15:28 UTC, brooksmtownsend commented on src/up/mod.rs
> +        .output()
Let me check on what all this output contains and if I can simulate a failure, I've never seen the `stop` command fail or give back information other than `ok`

2022-09-07 16:44 UTC, brooksmtownsend commented on src/up/mod.rs
> +        .output()
Good call, I can at least check for a non-zero exit status

2022-09-08 16:05 UTC, connorsmith256 approved these changes

2022-09-08 16:05 UTC, connorsmith256 commented on crates/wash-lib/src/start/wasmcloud.rs
> +        Ok(parsed_version) if !version_req.matches(&parsed_version) => Err(anyhow!(
TIL about this crate. Cool!
https://docs.rs/semver/1.0.13/semver/struct.VersionReq.html

2022-09-08 16:05 UTC, connorsmith256 commented on crates/wash-lib/src/start/wasmcloud.rs
> +            assert_eq!(e.to_string(), "wasmCloud version v0.56.0 is earlier than the minimum supported version of v0.57.0");
Nit: I wouldn't couple tests passing to matching on this specific error message. If we tweak the error message, this test would need to be updated, which shouldn't be necessary

2022-09-09 18:27 UTC, mattwilkinsonn commented on crates/wash-lib/src/start/wasmcloud.rs
> +            // Stderr will include :nodedown if no other host is running, otherwise
Sg

2022-09-09 18:27 UTC, mattwilkinsonn approved these changes

2022-09-09 19:28 UTC, merged