add artifact not found error
wasmCloud/wash-archive pull request #305
Opened 2022-09-01 09:40 UTC by Mo-Fatah

relates to #273 

I think this can be a temporary fix to indicate that the artifact couldn't be found locally or from a registry.

2022-09-01 14:46 UTC, mattwilkinsonn commented
Hi @Mo-Fatah, thanks for contributing! From reading the code I think your changes would fix #273, although I haven't tested it yet. Not sure why you closed the PR, but if you need any help with this feel free to reach out. We often discuss changes and ask for advice on the wasmCloud Slack, here is the [link](https://slack.wasmcloud.com/).

2022-09-01 16:41 UTC, Mo-Fatah commented
Thanks @mattwilkinsonn !! I thought that my fix solves the issue. But after I filed the PR , I ran the tests and I had a failed test case 
```
test integration_claims_inspect ... FAILED
```
This why I closed my PR thinking that my fix is causing the test failure.

But I noticed something now, this test case also fails on `main upstream`. Is this issue known for you or I am missing something here ? 
I am using `Ubuntu 20.04.4 LTS`

2022-09-01 17:47 UTC, thomastaylor312 commented
@Mo-Fatah I didn't see any failing tests in main (we had a failed build of a docker image, but nothing from tests). Let's see how the PR tests do because perhaps it could be local.

Also, you'll need to sign off your commit! Details instructions can be found by clicking the "Details` link on the failed DCO check

2022-09-02 06:27 UTC, Mo-Fatah commented
> @Mo-Fatah I didn't see any failing tests in main (we had a failed build of a docker image, but nothing from tests). Let's see how the PR tests do because perhaps it could be local.
> 
> Also, you'll need to sign off your commit! Details instructions can be found by clicking the "Details` link on the failed DCO check

Yeah, all the checks here have passed, apparently this is a local failure. 

I have singed of commit, Thank you!

2022-09-02 14:29 UTC, brooksmtownsend requested changes

2022-09-02 14:29 UTC, brooksmtownsend commented on src/reg.rs
> +        bail!("Artifact not found");
Just to give the user a better sense for what went on, it might be better to phrase this as 
```
Artifact not found in registry, please ensure {} exists and is a valid OCI reference
```
Or something like that, so that users can see what reference they are trying to download. Thank you for submitting this!

2022-09-02 14:44 UTC, brooksmtownsend commented
This also seems to still reproduce the same issue, likely because the image tag doesn't exist so it's unwrapping to `latest` as a fallback 
```
> wash claims inspect example_policy_s.wasm

Pulling artifacts with tag 'latest' is prohibited. This can be overriden with the flag --allow-latest
```

2022-09-03 07:20 UTC, Mo-Fatah commented
Yes you are right.
I thought of it as: when the user enter a not-found artifact, they will be prompted to try the `--allow-latest` flag. When they try again with the flag, they will get a not-found error. A kind of: try everything before getting a final not-found error. 

Not very accurate. Do you have suggestions ? besides a more detailed message.

2022-09-06 13:23 UTC, brooksmtownsend commented
> Do you have suggestions ? besides a more detailed message.

So what we're really trying to do here is provide a useful error message for people when they try to inspect a local file but they type in the name wrong. Here's what I think would be a good solution:

- If the user types in an OCI reference we require a tag (e.g. you can't just do `wasmcloud.azurecr.io/echo`, you have to type out `wasmcloud.azurecr.io/echo:latest` to use the `latest` tag)
    - I know this isn't what Docker does, but we have explicit `latest` checks so I think it would be better to explicitly require that tag.
- If the user doesn't include a tag, then assume it's a file, and if it's not found then we return an error message about the file not being found
- If the user includes the `latest` tag, then we can do any checks for the `--allow-latest` flag

Thoughts @mattwilkinsonn / @thomastaylor312 ?

2022-09-19 16:28 UTC, thomastaylor312 commented
> If the user doesn't include a tag, then assume it's a file, and if it's not found then we return an error message about the file not being found

This error should probably say something about file not found and then 

```
(Were you specifying an image? Image tags are required for wasmCloud)
```

2022-11-10 14:55 UTC, brooksmtownsend commented
@Mo-Fatah I'm going to close this as it seems to have gotten a little stale, please feel free to re-open once you've added a few changes or want to re-approach this PR

2022-11-10 14:55 UTC, closed without merging