Feat/wash down
wasmCloud/wash-archive pull request #327
Opened 2022-11-04 15:11 UTC by brooksmtownsend

Fixes #322

2022-11-08 03:13 UTC, thomastaylor312 requested changes
Only one blocking semver violation and a few other nits/ramblings

2022-11-08 03:13 UTC, thomastaylor312 commented on crates/wash-lib/Cargo.toml
> +version = "0.3.2"
You are adding new functionality (and constants) to wash-lib, so this should be a 0.4. Also, might want this to be an alpha until we cut a new wash release

2022-11-08 03:13 UTC, thomastaylor312 commented on src/down/mod.rs
> +use std::collections::HashMap;
Nit: please put `std` imports up top, separated from imported crates

2022-11-08 03:13 UTC, thomastaylor312 commented on src/down/mod.rs
> +                    "🤔 Host did not appear to be running, assuming it's already stopped\n",
A+ emoji usage

2022-11-08 03:13 UTC, thomastaylor312 commented on src/down/mod.rs
> +    out_json.insert("success".to_string(), json!(true));
Out of scope comment for future discussion: I think it might be better to just have a `serde_json::Value` that we use instead of a `HashMap` just to make all of this read easier

2022-11-08 03:13 UTC, thomastaylor312 commented on src/down/mod.rs
> +        .map_err(|e| anyhow!(e))
Nit: Might be cleaner to just do `.map_err(anyhow::Error::from)`

2022-11-08 03:13 UTC, thomastaylor312 commented on src/down/mod.rs
> +        let _ = tokio::fs::remove_file(&pid_file).await;
Any need for a warning if remove file fails? I don't think so but wanted to check

2022-11-08 14:42 UTC, brooksmtownsend commented on src/down/mod.rs
> +        let _ = tokio::fs::remove_file(&pid_file).await;
I don't think so, if we fail to remove it for some reason the next time we run `wash up` we'll just overwrite it. Only thing I could think of is, in the future, if we supported multiple `wash up`'s in a row to "smart" check for a running NATS server 🤔 

For now I think I'll leave it off and we can approach that when it comes time

2022-11-10 14:29 UTC, autodidaddict submitted a review, later dismissed

2022-11-10 14:29 UTC, autodidaddict commented on src/down/mod.rs
> +pub(crate) fn nats_pid<P>(install_dir: P) -> PathBuf
super ultra nit: I assume a function called `nats_pid` returns a number/string with the actual pid in it, not a pathbuf.

2022-11-10 15:00 UTC, brooksmtownsend commented on src/down/mod.rs
> +pub(crate) fn nats_pid<P>(install_dir: P) -> PathBuf
It's a super ultra nit sir, but it checks out

2022-11-10 15:00 UTC, brooksmtownsend commented
Waiting on #329 to merge only because that modifies the `up` test to not infinite hang

2022-11-10 20:50 UTC, thomastaylor312 approved these changes

2022-11-10 21:25 UTC, merged