Moved project build functionality to wash-lib
wasmCloud/wash-archive pull request #353
Opened 2022-12-06 17:52 UTC by brooksmtownsend

Signed-off-by: Brooks Townsend <brooks@cosmonic.com>

2022-12-06 20:43 UTC, connorsmith256 commented on crates/wash-lib/src/build.rs
> +    no_sign: bool,
Nit: `skip_signing`? `build_only`?

2022-12-06 20:43 UTC, connorsmith256 commented on crates/wash-lib/src/build.rs
> +        Ok(destination_file?)
Should we check that `destination_file` is `Ok` before trying to sign, rather than down here?

2022-12-06 20:43 UTC, connorsmith256 commented on crates/wash-lib/src/build.rs
> +        bail!("Compiling actor failed: {}", result.to_string())
Should a library `bail!`? Feels a bit extreme. Why not return an error and let the caller handle it?

2022-12-07 23:18 UTC, connorsmith256 commented on crates/wash-lib/src/build.rs
> +pub fn build_project(config: ProjectConfig) -> Result<PathBuf> {
Could this take a ref instead of moving the struct?

2022-12-08 14:28 UTC, brooksmtownsend commented on crates/wash-lib/src/build.rs
> +        bail!("Compiling actor failed: {}", result.to_string())
That's what this does 😄 https://docs.rs/anyhow/1.0.66/anyhow/macro.bail.html super useful from `anyhow`

2022-12-08 16:23 UTC, connorsmith256 commented on crates/wash-lib/src/build.rs
> +        bail!("Compiling actor failed: {}", result.to_string())
🤦 I totally thought this was essentially a prettier panic. TIL

2022-12-08 20:32 UTC, brooksmtownsend commented on crates/wash-lib/src/build.rs
> +pub fn build_project(config: ProjectConfig) -> Result<PathBuf> {
Definitely, I'll throw some references around

2022-12-08 20:33 UTC, brooksmtownsend commented on crates/wash-lib/src/build.rs
> +    no_sign: bool,
Yeah I like affirmative instead of the double negative. Will reword to something

2022-12-08 20:33 UTC, brooksmtownsend commented on crates/wash-lib/src/build.rs
> +        Ok(destination_file?)
Yeah that's pretty fair, I was thinking that if I failed to create the pathbuf no need to prevent me from signing the file, but I'll just move the `?` upwards 😄

2022-12-14 18:51 UTC, connorsmith256 requested changes
Just a couple nits and questions

2022-12-14 18:51 UTC, connorsmith256 commented on crates/wash-lib/src/build.rs
> +    /// Path to issuer seed key (account). If this flag is not provided, the will be sourced from $WASH_KEYS ($HOME/.wash/keys) or generated for you if it cannot be found.
Nit: typo in "the will be"? Same with the comment on `subject`

2022-12-14 18:51 UTC, connorsmith256 commented on crates/wash-lib/src/build.rs
>  /// * `no_sign`: If `true`, build the actor but don't sign. Useful for just checking build status without needing signing keys or fully referenced capabilities
Nit: this comment needs to be updated

2022-12-14 18:51 UTC, connorsmith256 commented on crates/wash-lib/src/parser/mod.rs
> +    } else if path.is_file() {
Do we need to double-check that this file is a `wasmcloud.toml` ?

2022-12-14 18:51 UTC, connorsmith256 commented on src/build.rs
> -    pub(crate) push: bool,
Is this a breaking change, or was this functionality not implemented yet?

2022-12-14 18:51 UTC, connorsmith256 commented on src/build.rs
> +                ("signed".to_string(), json!(true)),
Just double-checking I understand this: now `wash build` will always sign actors, though wash-lib supports not signing (by passing None for the signing config to `build_project`)?

2022-12-14 18:51 UTC, connorsmith256 commented on src/build.rs
> +                ("signed".to_string(), json!(true)),
Looks like the integration test failed due to something around `no-sign`, but idk if that was on outdated code, since I see you did update the test...

2022-12-14 18:51 UTC, thomastaylor312 approved these changes, later dismissed
All good pending passing tests

2022-12-14 18:51 UTC, thomastaylor312 commented on crates/wash-lib/src/build.rs
> +//!
Super nit: Trailing empty comment

2022-12-14 18:51 UTC, thomastaylor312 commented on crates/wash-lib/src/build.rs
> +// This struct requires the `cli` feature, which this whole module is gated by. If that changes,
Did we want to move over all of these `clap` things before we test out whether we can configure `env` variable names?

2022-12-14 18:51 UTC, thomastaylor312 commented on crates/wash-lib/tests/parser/main.rs
> +                .canonicalize()
Nit: Do you need canonicalize since this is a test?

2022-12-14 19:05 UTC, brooksmtownsend commented on crates/wash-lib/tests/parser/main.rs
> +                .canonicalize()
Actually, yeah, but the real reason why I do it is to turn this into the absolute path instead of `./tests/...`

2022-12-14 19:06 UTC, brooksmtownsend commented on crates/wash-lib/src/build.rs
> +// This struct requires the `cli` feature, which this whole module is gated by. If that changes,
I don't think so, I'm going to move them into the CLI section and transform this struct into something that doesn't have the derive macros

2022-12-14 19:11 UTC, brooksmtownsend commented on src/build.rs
> +                ("signed".to_string(), json!(true)),
Yeah I did unintentionally remove that ability, adding back in a `--build-only` flag

2022-12-14 19:12 UTC, brooksmtownsend commented on src/build.rs
> -    pub(crate) push: bool,
This functionality wasn't implemented yet, so I figured that implementing it was going to be a breaking change anyways and it was better to be left off. There are plenty of other breaking changes here, though!

2022-12-14 19:13 UTC, brooksmtownsend commented on crates/wash-lib/src/parser/mod.rs
> +    } else if path.is_file() {
I don't think so, we wouldn't want to enforce it needing to be called `wasmcloud.toml` (though I think that's fine.) IMO failing here at the parse step is more appropriate

2022-12-14 19:29 UTC, brooksmtownsend commented on crates/wash-lib/src/build.rs
> +// This struct requires the `cli` feature, which this whole module is gated by. If that changes,
Moved in latest commit

2022-12-14 19:55 UTC, thomastaylor312 submitted a review, later dismissed

2022-12-14 22:29 UTC, mattwilkinsonn submitted a review, later dismissed
LGTM with one nit and one question

2022-12-14 22:29 UTC, mattwilkinsonn commented on src/build.rs
> +                if command.build_only {
Could you set this second param to a variable first? Gets a bit nested here inside the function call

2022-12-14 22:29 UTC, mattwilkinsonn commented on crates/wash-lib/src/build.rs
> +}
Should this be a part of `wasmcloud.toml`?

2022-12-14 22:36 UTC, brooksmtownsend commented on crates/wash-lib/src/build.rs
> +}
I don't think so, I think this is just part of runtime command line flags for when you are building the actor in CI and you don't want autogenerated keys, but I could be convinced otherwise if you have a use case in mind

2022-12-14 22:50 UTC, connorsmith256 approved these changes

2022-12-14 22:57 UTC, merged