[WIP] Refactoring gen to wash-lib
wasmCloud/wash-archive pull request #355
Opened 2022-12-14 23:00 UTC by brooksmtownsend

Very much WIP, not ready for review, only thing I've done so far is copy/paste and make it compile

2022-12-15 20:27 UTC, thomastaylor312 requested changes
Code looks all good, just some stuff around deps

2022-12-15 20:27 UTC, thomastaylor312 commented on crates/wash-lib/Cargo.toml
> +console = "0.15"
All of these specific generate things should be `optional = true` and enabled when `cli` is specified (unless it is used elsewhere)

2022-12-15 21:45 UTC, connorsmith256 submitted a review, later dismissed

2022-12-16 02:42 UTC, connorsmith256 approved these changes

2022-12-16 17:28 UTC, thomastaylor312 approved these changes

2022-12-16 19:23 UTC, merged