chore: bump wascap
wasmCloud/wash-archive pull request #361
Opened 2023-01-04 17:09 UTC by ricochet

2023-01-04 17:09 UTC, autodidaddict commented
I'm okay with this if @brooksmtownsend and @mattwilkinsonn are.

2023-01-04 17:12 UTC, autodidaddict commented
@ricochet - the DCO requirement needs the commits to be signed

for the curious - this change is significant because anything signed by this version of wash/washlib will _not_ be backwards compatible with old versions of the host (the module hash verification check will fail)

2023-01-04 20:39 UTC, autodidaddict commented
This seems to have broken an integration test. I'm not sure if it's because one of the fixtures is different but there's a claims mismatch

2023-01-05 01:08 UTC, ricochet commented
Ah, this is a good test. 

wash claims inspect output is different. The hashes changed (expected), there is now a version on the claim (expected) but two other diffs look suspect:

```json
{
...
        "capabilities": ["HTTP Server", "Logging"],
        "call_alias": "wasmcloud/logger_onedotzero"
 }
```

```json
{
...
        "capabilities": ["HTTP Server", "wasmcloud:logging"],
         "call_alias": "(Not set)"
}
```

It seems to have lost the call_alias and the logging claim name is odd. I think I prefer the wasmcloud prefix, but why didn't the HTTP Server change? Digging in...

2023-01-05 01:48 UTC, ricochet commented
I think there must be history around naming as this claim is for "wasmcloud:logging" and not "wasmcloud:builtin:logging". "Logging" should now == "wasmcloud:builtin:logging" and not "wasmcloud:logging".

This could be avoided if wascap normalized friendly name capabilities or if friendly names were removed entirely.

2023-01-05 01:59 UTC, autodidaddict commented
Yep we're looking at some scary tissue here from early days when there were a handful of predetermined contract IDs. The upside is this is mostly showing the age in the test and not a big problem with the app itself. 

100% agree that we should be consistent in how we treat this

2023-01-05 03:10 UTC, ricochet commented
I think that mostly leaves call_alias as the key change that I can't explain. I added a test over in wascap and locally also tried with the same string as the one here with success.

I manually ran the integration test with a wash before/after wascap update... and yeah call_alias is gone Jim.

2023-01-05 12:09 UTC, autodidaddict commented
Doing some digging on this. I've verified that doing this manually with the previous/released version of wash works just fine. Looking into some more things

2023-01-06 13:37 UTC, autodidaddict commented
@ricochet if you bump wascap to 0.9.1 now the double-sign test should pass.

2023-01-06 16:25 UTC, autodidaddict requested changes

2023-01-06 16:25 UTC, autodidaddict commented on Cargo.toml
> +wascap = "0.9.0"
this should be 0.9.1 as the washlib one is also using 0.9.1.

2023-01-06 16:26 UTC, ricochet commented on Cargo.toml
> +wascap = "0.9.0"
cargo update betraying me. TY

2023-01-06 16:27 UTC, autodidaddict approved these changes, later dismissed

2023-01-09 17:48 UTC, autodidaddict approved these changes, later dismissed

2023-01-09 20:12 UTC, connorsmith256 approved these changes, later dismissed
Woohoo, tests pass now! 🎉

2023-01-09 20:38 UTC, brooksmtownsend approved these changes, later dismissed

2023-01-10 16:38 UTC, connorsmith256 approved these changes

2023-01-10 17:21 UTC, merged