Bumped to wasmCloud 0.60.0
wasmCloud/wash-archive pull request #381
Opened 2023-02-08 21:54 UTC by brooksmtownsend

This PR bumps to 0.15.0 including the wascap bump from #361 and wasmCloud 0.60.0 which are meant to interact with each other in terms of claims signing on actors.

In a separate commit I also bumped lock deps with `cargo update`, happy to back that out if desired.

2023-02-08 22:00 UTC, connorsmith256 submitted a review, later dismissed

2023-02-09 17:50 UTC, connorsmith256 requested changes

2023-02-09 17:50 UTC, connorsmith256 commented on crates/wash-lib/src/start/wasmcloud.rs
> +        return Ok(dir.as_ref().join(version).join(WASMCLOUD_HOST_BIN));
Nit: we're breaking encapsulation of `is_wasmcloud_installed` by assuming the directory it's checking is `[dir]/[version]/[bin]`. It would be safer to rename the function to something like `find_wasmcloud_binary` and have it return an `Option<Path>` containing the install path

2023-02-09 17:50 UTC, connorsmith256 commented on crates/wash-lib/src/start/wasmcloud.rs
> +            let file_path = dir.as_ref().join(version).join(path);
The doc comment on this function should be updated to specify `[dir]/[version]` will be used as the install dir, rather than just `dir`

2023-02-09 19:23 UTC, thomastaylor312 commented on crates/wash-lib/src/start/wasmcloud.rs
> +        return Ok(dir.as_ref().join(version).join(WASMCLOUD_HOST_BIN));
Ok, this is now addressed

2023-02-09 21:47 UTC, brooksmtownsend reviewed
✅

2023-02-09 21:49 UTC, connorsmith256 approved these changes
🎉

2023-02-09 21:53 UTC, merged