Consolidating claims inspect and par inspect command into a new inspect command
wasmCloud/wash-archive pull request #385
Opened 2023-02-10 21:20 UTC by aish-where-ya

Created a new command named `inspect` that will perform the functionalities of `par inspect` and `claims inspect`.
Added deprecation warnings for `par inspect` and `claims inspect`.
Added unit and integration tests.

2023-02-16 03:33 UTC, mattwilkinsonn requested changes
Hi @aish-where-ya! Thanks for the contribution!

Left some comments below. Let me know if you need more info on any of these.

2023-02-16 03:33 UTC, ghost commented on crates/wash-lib/src/cli/claims.rs
> +    warn!("claims inspect will be deprecated in future versions. Use inspect instead.");
I'd just remove the old command entirely but will defer if anyone has a stronger opinion. I don't think we're at a stage where we need to support deprecated commands

(@brooksmtownsend)

2023-02-16 03:33 UTC, ghost commented on src/inspect.rs
> +
nit - extra newline

2023-02-16 03:33 UTC, ghost commented on src/inspect.rs
> +        bail!("Not enough bytes to be a valid claim file")
Could this just return a bool (with no Result) and the `if input.len() < 4` block return false?

2023-02-16 03:33 UTC, ghost commented on src/inspect.rs
> +pub async fn handle_command(
nit: put this at the top as it's the "entry point" of this command.

2023-02-16 03:33 UTC, ghost commented on src/par.rs
> +    warn!("par inspect will be deprecated in future versions. Use inspect instead.");
Same here, I'd just remove outright unless someone has a stronger opinion

2023-02-16 03:33 UTC, ghost commented on src/inspect.rs
> +use clap::{Parser};
Formatting of imports is a little weird, there's extra commas and spaces. I think rustfmt will fix this stuff?

Also, could you add some top-level comments to the functions? I get what's going on but it might be hard to parse for newer wash developers.

2023-02-16 03:33 UTC, ghost commented on src/inspect.rs
> +    let jwt_only = cmd.jwt_only;
No need to destructure this if you're only using it once

2023-02-16 03:33 UTC, ghost commented on src/inspect.rs
> +        None => bail!("No capabilities discovered in : {}", module_name),
`caps.ok_or_else(|| anyhow!(...))?`

Would make this easier to read IMO

2023-02-16 03:33 UTC, ghost commented on src/inspect.rs
> +    if is_wasm(&buf).is_ok() || jwt_only {
is the `|| jwt_only` necessary?

2023-02-16 03:33 UTC, ghost commented on src/inspect.rs
> +    let cache_path = (!cmd.no_cache).then(|| cached_oci_file(&cmd.module));
TIL about using .then() on bools to create `Option`s! I thought this was a future for a minute and got really confused lol

2023-02-16 03:33 UTC, mattwilkinsonn commented on src/inspect.rs
> +    let friendly_rev = match metadata.rev {
`.map_or("None".to_string(), |rev| rev.to_string())` would be easier to read here.

2023-02-16 14:26 UTC, brooksmtownsend commented on crates/wash-lib/src/cli/claims.rs
> +    warn!("claims inspect will be deprecated in future versions. Use inspect instead.");
I feel like we've got a few scripts or actions laying around that inspect an actor to pull out the public key, I just wouldn't want to break those immediately and I'd rather give a chance to discover scripts that had that command

2023-02-16 23:03 UTC, mattwilkinsonn commented on crates/wash-lib/src/cli/claims.rs
> +    warn!("claims inspect will be deprecated in future versions. Use inspect instead.");
That makes sense. Current behavior looks good then!

2023-02-27 16:29 UTC, brooksmtownsend requested changes
The `inspect` module is looking great! I have a few requests for refactoring opportunities since the code is largely contained in `src/inspect` now, and to remove some duplicate `get_oci_bytes` calls that are inefficient since you already download the bytes in the first step.

2023-02-27 16:29 UTC, brooksmtownsend commented on tests/integration_inspect.rs
> +    // Pull the echo module and push to local registry to test local inspect
nit: we're pulling the httpclient provider here

2023-02-27 16:29 UTC, brooksmtownsend commented on tests/integration_inspect.rs
> +    // Pull the echo module and push to local registry to test local inspect
Additionally, below, some of the variables are still named from the copy-paste from the other tests. For clarity, I think we should rename those to match this provider and test

2023-02-27 16:29 UTC, brooksmtownsend commented on crates/wash-lib/src/cli/claims.rs
> +    warn!("claims inspect will be deprecated in future versions. Use inspect instead.");
I think it would be good at this point to remove the code from `claims inspect` that actually performs the inspect and instead call the function in `src/inspect.rs` that you wrote. That way we only have one piece of code that's performing the inspect, and the `wash claims inspect` here is simply a thin (deprecated) wrapper around `inspect`.

2023-02-27 16:29 UTC, brooksmtownsend commented on src/par.rs
> +pub(crate) async fn handle_par_inspect(cmd: InspectCommand) -> Result<CommandOutput> {
Same comment here as claims, I think the `par inspect` function should just be a thin wrapper around calling the `src/inspect.rs` function that you wrote

2023-02-27 16:29 UTC, brooksmtownsend commented on src/inspect.rs
> +const WASM_MAGIC: [u8; 4] = [0x00, 0x61, 0x73, 0x6D];
A comment indicating where you got this magic number would be helpful for future code readers

2023-02-27 16:29 UTC, brooksmtownsend commented on src/inspect.rs
> +    pub module: String,
nit: this might read better as `Path or OCI URL to signed actor...`

2023-02-27 16:29 UTC, brooksmtownsend commented on src/inspect.rs
> +    pub module: String,
also, it might be better to call this `artifact` or `inspect_target` or something that's actor/provider oci/path agnostic. Happy to entertain suggestions here

2023-02-27 16:29 UTC, brooksmtownsend commented on src/inspect.rs
> +            (!command.no_cache.clone()).then(|| cached_oci_file(&command.module.clone()));
nit: these `.clone()`s are probably not necessary and might drop this down to one line if removed

2023-02-27 16:29 UTC, brooksmtownsend commented on src/inspect.rs
> +                insecure: command.insecure.clone(),
These booleans probably don't need to be cloned

2023-02-27 16:29 UTC, brooksmtownsend commented on src/inspect.rs
> +    let jwt_only = cmd.jwt_only;
@aish-where-ya unresolving this conversation since it seems to be present still

2023-02-27 16:29 UTC, brooksmtownsend commented on src/inspect.rs
> +    )
I think it would be better to pass the bytes down from the initial inspect function to save downloading the OCI artifact twice here

2023-02-27 16:29 UTC, brooksmtownsend commented on src/inspect.rs
> +    .await?;
Let's make the artifact bytes an input for this function since you already pull the bytes down as a part of inspecting the first few to see if it's a Wasm file

2023-02-27 20:47 UTC, aish-where-ya commented on src/inspect.rs
> +    let jwt_only = cmd.jwt_only;
I had destructured this to make the difference between handling actors and providers a bit clearer. But that is okay, I will collate it into a single block.

2023-03-07 04:23 UTC, aish-where-ya commented
This is one of those "the checks run successfully on my local machine" errors.

2023-03-07 18:18 UTC, closed without merging