feat: shell completions
wasmCloud/wash-archive pull request #392
Opened 2023-02-16 16:17 UTC by vados-cosmonic

This PR rebases/rebuilds the work done in https://github.com/wasmCloud/wash/pull/301

The code builds but testing on Windows is still not yet completed (trying this now in a VM)

2023-02-16 18:24 UTC, vados-cosmonic commented
Was able to confirm that the completion works in a VM:

![wash-completion-on-windows](https://user-images.githubusercontent.com/123968127/219454071-c6bf6c3f-bc1a-4419-baf6-dda448454da3.png)

That said -- I'm not sure the amount of documentation there is normal... Are the other steps (execution policy, profile additions, enabling completion/etc) expected knowledge for the average windows command line user? 

Unfortunately Windows is not my forte but I muddled through it -- could use a line or two on the documentation side to make it easier to actually install this functionality. @brooksmtownsend would you mind?

2023-02-23 19:31 UTC, autodidaddict submitted a review, later dismissed

2023-02-24 01:20 UTC, thomastaylor312 requested changes
This is pretty much good to go, blocking purely so we can have a discussion on the non-nit comment here. cc @brooksmtownsend @mattwilkinsonn

2023-02-24 01:20 UTC, thomastaylor312 commented on src/completions.rs
> +            cfg_dir().unwrap().display(),
Nit: I'd just capture the path above `let token` since `.join(TOKEN_FILE)` returns a new `PathBuf`

2023-02-24 01:20 UTC, thomastaylor312 commented on src/main.rs
> +                    // on the first non-error, non-json use of wash, print info about shell completions
Although I find this helpful, I worry about it in cases where someone is installing wash in pipeline and this prints during the first run on every pipeline. The thing I learned from maintaining Helm is no matter how many computer-friendly outputs you have, people will still try to parse plaintext output

2023-02-27 18:26 UTC, vados-cosmonic commented on src/main.rs
> +                    // on the first non-error, non-json use of wash, print info about shell completions
I only refactored and rebased this code, but in the interest of pushing this forward -- @brooksmtownsend @mattwilkinsonn any thoughts?

2023-02-28 15:28 UTC, brooksmtownsend commented on src/main.rs
> +                    // on the first non-error, non-json use of wash, print info about shell completions
I don't have a strong opinion, it's a nice touch cause people probably wouldn't know about it otherwise. I'll defer to @thomastaylor312, to be fair we probably will use `wash` in CI but it's more likely that the proper strategy is to use JSON output

2023-02-28 20:18 UTC, thomastaylor312 commented on src/main.rs
> +                    // on the first non-error, non-json use of wash, print info about shell completions
Since this is just a refactor and rebase, not gonna block on it.

2023-02-28 20:18 UTC, thomastaylor312 approved these changes, later dismissed

2023-02-28 20:19 UTC, thomastaylor312 commented
@vados-cosmonic I'll merge this after rebase!

2023-02-28 21:49 UTC, brooksmtownsend submitted a review, later dismissed

2023-03-01 01:11 UTC, vados-cosmonic commented
@thomastaylor312 done, thanks for taking another look :bow:

2023-03-02 18:48 UTC, brooksmtownsend approved these changes, later dismissed

2023-03-03 05:45 UTC, vados-cosmonic commented
Rebased to match changes on `main`!

2023-03-06 19:41 UTC, thomastaylor312 approved these changes

2023-03-06 19:41 UTC, merged