use client builder to support querying KV bucket directly
wasmCloud/wash-archive pull request #404
Opened 2023-02-23 19:52 UTC by connorsmith256

# Feature or Problem
Wash is currently using v0.22 of the control interface client. v0.23 added support for querying the `LATTICEDATA_{latticeID}` KV bucket, which is now the source of truth for link definitions and claims

# Related Issues
N/A, but I can file one if desired

# Release Information
Soon ™️ / next release ASAP

# Consumer Impact
N/A. This version of the control interface client is backwards-compatible. If the KV bucket doesn't exist, the client falls back on querying the host's control interface topics

# Testing
Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

## Platforms
Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

## Unit Test(s)
I added a unit test to confirm the new `js_domain` flag is picked up.

## Acceptance or Integration
None

## Manual Verification
I ran manual tests of the following form:
```bash
RUST_LOG=debug target/release/wash ctl link query # use default context
RUST_LOG=debug target/release/wash ctl link query --context another-context # override context with js_domain
RUST_LOG=debug target/release/wash ctl link query --js-domain custom-domain # override js_domain specifically
```

`RUST_LOG=debug` causes the control interface client to emit one of two messages after it attempts to construct a KV store:
- `[2023-02-23T19:37:46Z DEBUG wasmcloud_control_interface::kv] Using direct bucket access for lattice metadata queries`
- `[2023-02-23T19:33:28Z DEBUG wasmcloud_control_interface::kv] Using deprecated control interface commands for lattice metadata queries`

I used this output to validate the expected behavior based off the input

2023-02-23 20:25 UTC, brooksmtownsend requested changes, later dismissed
:semver-violation:

2023-02-23 20:25 UTC, brooksmtownsend commented on src/ctl/mod.rs
> +    pub(crate) js_domain: Option<String>,
This here looks like a good ol backwards compatible new functionality minor bump 😉

2023-02-23 20:33 UTC, connorsmith256 commented on src/ctl/mod.rs
> +    pub(crate) js_domain: Option<String>,
🚨 am I going right to jail?

2023-02-24 00:20 UTC, thomastaylor312 commented on src/ctl/mod.rs
> +    pub(crate) js_domain: Option<String>,
![tenor-42137734](https://user-images.githubusercontent.com/4294228/221061203-f5c3a3bf-c03b-4da6-9817-c853b7e3783e.gif)

2023-02-24 00:23 UTC, thomastaylor312 approved these changes

2023-02-24 16:59 UTC, merged