workflow: Makefile improvements/refactoring
wasmCloud/wash-archive pull request #419
Opened 2023-02-27 17:43 UTC by vados-cosmonic

# Feature or Problem
This PR includes some changes to the project `Makefile` that make  a slightly tighter local dev loop (at least it did for me).

# Related Issues
N/A

# Release Information
`next`

# Consumer Impact
Developers of `wash`

# Testing

To test this:
1. Pull `wash`
2. Run the associated `Makefile` targets

Built on platform(s)
- [x] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [x] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

## Unit Test(s)

N/A

## Acceptance or Integration

N/A

## Manual Verification

Verified manually by running the targets locally

2023-02-27 19:18 UTC, thomastaylor312 requested changes
One minor change, but otherwise I think this is fairly clean

2023-02-27 19:18 UTC, thomastaylor312 commented on Makefile
> +	@$(CARGO) watch -x build
This requires an additional cargo cli extension to be added, this would need documentation if we add it in

2023-02-28 02:24 UTC, vados-cosmonic commented on Makefile
> +	@$(CARGO) watch -x build
OH you're right -- I also want to add an entire getting started dev section, will update

2023-02-28 02:26 UTC, vados-cosmonic commented on Makefile
> +	@$(CARGO) watch -x build
Actually @thomastaylor312 I totally forgot, I *already* moved that work off to a separate branch, making a PR for that now

2023-02-28 14:43 UTC, rvolosatovs commented on Makefile
> +				test test-integration test-all clean help
```suggestion
.PHONY: build build-watch test test-integration test-all clean help
```

2023-02-28 14:45 UTC, brooksmtownsend commented on docs/guides/development/README.md
> +[cargo-watch]: https://crates.io/crates/cargo-watch
nit: It might be helpful to add here why it's useful and the `make` command it enables

2023-02-28 14:45 UTC, brooksmtownsend reviewed
Make improvements look good, just one non-blocking suggestion

2023-02-28 15:51 UTC, vados-cosmonic commented on docs/guides/development/README.md
> +[cargo-watch]: https://crates.io/crates/cargo-watch
Yeah that's reasonable, will add!

- [ ] Add explanation of the command used in watch

2023-02-28 19:35 UTC, thomastaylor312 approved these changes
Approval from me. @brooksmtownsend got here first, so I'll let him merge

2023-02-28 19:52 UTC, brooksmtownsend approved these changes

2023-02-28 19:54 UTC, merged