docs: add developer guide, more concise README
wasmCloud/wash-archive pull request #421
Opened 2023-02-28 02:41 UTC by vados-cosmonic

# Feature or Problem
Somewhat subjective improvements to the documentation:

- add collapsible sections for install targets
- tighten copy on what wash is meant to do
- add developer guide

# Related Issues

https://github.com/wasmCloud/wash/pull/419

# Release Information

`next`

# Consumer Impact

Consumers should be able to get a feel for what `wash` is and how it fits in the ecosystem, at a glance.

# Testing

N/A

Built on platform(s)
- [x] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [x] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

## Unit Test(s)
N/A

## Acceptance or Integration
N/A

## Manual Verification
Yes, verified manually

2023-02-28 16:04 UTC, brooksmtownsend requested changes
This is lovely! one nit, and conflicts that might need to be fixed

2023-02-28 16:04 UTC, brooksmtownsend commented on docs/cli/README.md
> +Bootstrap a [wasmCloud][wasmcloud] environment in one easy command, supporting both launching NATS and wasmCloud in the background as well as an "interactive" mode for shorter lived hosts.
nit: this wasmCloud link is broken, should link to the OTP repo

2023-02-28 16:11 UTC, vados-cosmonic commented on docs/cli/README.md
> +Bootstrap a [wasmCloud][wasmcloud] environment in one easy command, supporting both launching NATS and wasmCloud in the background as well as an "interactive" mode for shorter lived hosts.
Ah this actually needs to be made consistent as well -- the link in the front README was to wasmcloud.dev -- will update them both.

2023-02-28 16:14 UTC, vados-cosmonic commented
@brooksmtownsend thanks for the review, just patched up those issues you found! (BTW it definitely removes other people when I re-request a review)

2023-02-28 21:48 UTC, brooksmtownsend requested changes
Just a request for one more broken link and .dev -> .com

2023-02-28 21:48 UTC, brooksmtownsend commented on README.md
> +`wash` is the comprehensive CLI to [wasmCloud][wasmcloud]. `wash` helps you:
i'm not sure how it happens, but this link still takes me to wasmcloud.dev 🤔

2023-02-28 21:48 UTC, brooksmtownsend commented on README.md
> +The easiest way to get started with `wash` is via [`cargo`][cargo]
This link appears to be broken, I think it can either link to Rust or just be `cargo`

2023-02-28 21:48 UTC, brooksmtownsend commented on README.md
> +[wasmcloud]: https://wasmcloud.dev
wow, so that's how! This is a neat way to do links. But this can just change to wasmcloud.com

2023-03-01 00:07 UTC, vados-cosmonic commented on README.md
> +`wash` is the comprehensive CLI to [wasmCloud][wasmcloud]. `wash` helps you:
ah I see you figured out how this works down below!

2023-03-01 00:08 UTC, vados-cosmonic commented on README.md
> +The easiest way to get started with `wash` is via [`cargo`][cargo]
yeah this is my mistake here, it needs to be a HTML link since we're in `<details>`

2023-03-01 00:22 UTC, vados-cosmonic commented on README.md
> +The easiest way to get started with `wash` is via [`cargo`][cargo]
Done! turns out I needed to add a newline in between to get back to regular markdown processing.

2023-03-01 00:22 UTC, vados-cosmonic commented on README.md
> +[wasmcloud]: https://wasmcloud.dev
ah yeah I See you figuredout how this works, will resolve!

2023-03-02 18:01 UTC, vados-cosmonic commented
Hey @mattwilkinsonn  any thoughts on this PR? It seems to now be conflicting with the `README.md` in `main`, but before attempting to resolve the conflicts I wanted to just get your opinion on how it should look at the end.

Here's the [README look that this PR is pushing for](https://github.com/wasmCloud/wash/blob/01acc97e9485f3a917282d665c6626ab37c54d0c/README.md).

I wanted to make the README a bit more concise around the following themes:

- A concise listing of what you can do with `wash`
- Collapsible installation instruction sections
- Only listing commands that are important to people getting started with `wash`, in the order they'd normally be useful -- `wash up`/`wash new` being first, etc.
- A separate CLI reference with all the commands and some extra direction.

Your changes added:

- A ToC at the top
- Development guide document

Which things should I keep/merge over from my README? I'm assuming the collapsible installation section stuff can stay, and *maybe* the concise listing, but are you set on having as many commands listed on the README directly? IMO commands like `par` are not something someone would normally need right away/could be tucked away.

2023-05-16 23:48 UTC, closed without merging