ci: add `nix` CI
wasmCloud/wash-archive pull request #429
Opened 2023-02-28 16:32 UTC by rvolosatovs

- Build, test and upload as artifacts:
    - Statically-linked (towards Musl) x86_64 and aarch64 Linux `wash` binaries
    - Darwin x86_64, aarch64 and "universal" binaries
    - OCI images containing the above
- Lint the `nix` flake
- Run `clippy`, `nextest` and `fmt` via `nix`
- Run a "real" `cargo test` from within the `nix` development shell

# Related Issues

Blocked by #408 

# Release Information

# Consumer Impact

# Testing

Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

## Unit Test(s)

## Acceptance or Integration

## Manual Verification

2023-02-28 17:05 UTC, rvolosatovs commented
```
running 3 tests
test can_stop_detached_host ... FAILED
test doesnt_kill_unowned_nats ... ok

{
  "success": false,
  "error": "Another wasmCloud host is already running on this machine with PID 23342\n"
test integration_up_can_start_wasmcloud_and_actor ... FAILED
}

error: test failed, to rerun pass `--test integration_up`
failures:

---- can_stop_detached_host stdout ----
thread 'can_stop_detached_host' panicked at 'No wasmcloud process should be running', tests/integration_up.rs:121:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- integration_up_can_start_wasmcloud_and_actor stdout ----
thread 'integration_up_can_start_wasmcloud_and_actor' panicked at 'assertion failed: status.success()', tests/integration_up.rs:28:5


failures:
    can_stop_detached_host
    integration_up_can_start_wasmcloud_and_actor

test result: FAILED. 1 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 13.54s
```

Looks like a flake

2023-02-28 17:43 UTC, rvolosatovs commented
Hmm, just a few minutes ago, apparently, something went very wrong upstream in the installation script https://github.com/cachix/cachix-action/issues/138
I've never seen anything like this before in ~3 years of using this action

2023-03-02 17:18 UTC, brooksmtownsend reviewed
I've got a couple questions that I left comments for, but my biggest question is, do we need this _AND_ our other CI?

It seems like this PR quickly builds binaries for a few different OS/arch pairs, are they only useful for users of nix? If this is a solution that we can use to build and distribute `wash`, I would prefer to supplant our current `release` pipelines with something like this, or keep this scoped to just building.

All in all I'm happy to bring this in now, I just want to understand our future CI

2023-03-02 17:18 UTC, brooksmtownsend commented on .github/workflows/nix.yml
> +          # TODO: Run aarch64 binary within OCI
Do these TODOs need to be addressed?

2023-03-02 17:18 UTC, brooksmtownsend commented on .github/workflows/nix.yml
> +  pull_request:
Is this something we should run each and every PR?

2023-03-02 17:18 UTC, brooksmtownsend commented on .github/workflows/nix.yml
> +  push:
Could we restrict this to run only on the `main` branch for pushing?

2023-03-02 17:23 UTC, rvolosatovs commented on .github/workflows/nix.yml
> +          # TODO: Run aarch64 binary within OCI
I'd say it's low priority, but if you have suggestions on how to quickly run an aarch64 OCI (Docker) image on x86_64 host, preferably 0-config, please let me know

2023-03-02 17:24 UTC, rvolosatovs commented on .github/workflows/nix.yml
> +  pull_request:
If we don't, how would we know if a PR breaks it?

2023-03-02 17:24 UTC, rvolosatovs commented on .github/workflows/nix.yml
> +  push:
Sure, but why? What's the concern here?

2023-03-02 17:45 UTC, rvolosatovs commented
> I've got a couple questions that I left comments for, but my biggest question is, do we need this _AND_ our other CI?
> It seems like this PR quickly builds binaries for a few different OS/arch pairs, are they only useful for users of nix? If this is a solution that we can use to build and distribute `wash`, I would prefer to supplant our current `release` pipelines with something like this, or keep this scoped to just building.
> 
> All in all I'm happy to bring this in now, I just want to understand our future CI

This PR builds OCI (docker) images for Linux and Mac, both x86_64 and aarch64, as well as the binaries themselves. All of this is reproducible and portable - it runs on any OS. Please see the PR description for steps on how to try it out.

If you're on a Mac you should be able to download the architecture-appropriate or universal binary archive, unzip and execute `wash`. You can also try to download an OCI (docker) image, it's also documented in the description.

The obvious benefit I see with this PR is that now anyone can press on `nix` CI run on any commit and pull whichever Mac or Linux `wash` binaries or OCI images they need

I'm happy get rid of usage of things like https://github.com/cross-rs/cross, but I am not a maintainer of this repo, so I suppose it's not up to me to decide - I do not know what's the procedure here.

Alternatively, we could enable https://garnix.io/, which is a GitHub app and does not require any config, it parses the `flake.nix` and builds everything it can build e.g. https://github.com/rvolosatovs/nixify/pull/81/checks?check_run_id=11654903212

There would not be any GitHub artifacts uploaded in this case

2023-03-02 23:03 UTC, thomastaylor312 commented on .github/workflows/nix.yml
> +  push:
We don't really need/want to run a CI build for every single push that happens to the repo, particularly when doing something on a feature branch. Most things I've seen on GH do restrict to only a few branches. For us, that means `main`

2023-03-03 02:05 UTC, mattwilkinsonn commented
Seconding what @brooksmtownsend said. I don't think we should be running the same CI twice, once "vanilla" and once in `nix`. If we want adopt `nix` I think we'd need to get rid of the existing CI in favor of it.

So then it comes down to the pros/cons of running CI in `nix` vs in the vanilla way, and how much of the CI process is it replacing. Would we remove the release jobs we currently have for nix? From your comment it sounds like that is an advantage of the tool, but i'm not familiar enough to know what the benefits are

2023-03-08 14:18 UTC, brooksmtownsend requested changes
@rvolosatovs After the quick thread in slack I like the idea of getting this out and watching it for a little while, and eventually trying to replace our CI with these runs. Only request is to restrict the `pull_request` and `push` actions to the main branch given our possible rate limiting that we've run into

2023-03-13 15:37 UTC, brooksmtownsend approved these changes, later dismissed

2023-05-05 18:31 UTC, brooksmtownsend commented
Hey @rvolosatovs this seems super close! Is there anything we can do to push it into main?

2023-05-31 14:17 UTC, connorsmith256 approved these changes
Looking forward to comparing this to the existing action setup 👍

2023-05-31 14:57 UTC, merged