Feat/wash inspect
wasmCloud/wash-archive pull request #452
Opened 2023-03-07 18:46 UTC by aish-where-ya

## Feature or Problem
Created a new command named inspect that will perform the functionalities of par inspect and claims inspect.
Added deprecation warnings for par inspect and claims inspect.
Added unit and integration tests.

## Related Issues
Fixes https://github.com/wasmCloud/wash/issues/369

## Release Information
Next

## Consumer Impact
par inspect and claims inspect work for now but they will be deprecated in future releases

## Testing

Built on platform(s)
- [ ] x86_64-linux
- [x] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [x] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)
Unit Test name : test_inspect_comprehensive
To test the inspect cli command

### Acceptance or Integration
Integration tests for inspect cli

### Manual Verification
Unit and integration tests

2023-03-07 18:47 UTC, aish-where-ya commented
Reopening PR #385 because of git history issues.

2023-03-07 22:22 UTC, thomastaylor312 commented
Heads up to @mattwilkinsonn and @brooksmtownsend since you were reviewing the original PR

2023-03-08 14:35 UTC, brooksmtownsend requested changes
Just one super small nit to bring it across the line, it works great!

2023-03-08 14:35 UTC, brooksmtownsend commented on Makefile
> +	@$(CARGO) nextest run --no-fail-fast -p wash-lib
@mattwilkinsonn since you're familiar with nextest, is this a fine change?

2023-03-08 14:35 UTC, brooksmtownsend commented on Cargo.toml
> +inspect = "0.1.0"
I think you can remove this, this is an upstream crate

2023-03-08 17:10 UTC, brooksmtownsend approved these changes
Can remove `inspect` in a following PR. Great work @aish-where-ya !

2023-03-08 17:10 UTC, merged