Wash up waits for washboard to be up
wasmCloud/wash-archive pull request #508
Opened 2023-04-04 19:36 UTC by aish-where-ya

## Feature or Problem
Feature: Wash up waits for washboard to be run on port 4000

## Related Issues
#430 

## Release Information
next

## Consumer Impact
NA

## Testing
Tested using `make test-all` for flakes

Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)
NA

### Acceptance or Integration
NA

### Manual Verification
Tested for flakes by continuously running `make test-all`

2023-04-04 20:48 UTC, connorsmith256 approved these changes
LGTM! The port constant should be based off an env var/flag in the future, but I think you're actually planning on working on https://github.com/wasmCloud/wash/issues/464 next? 👏

2023-04-04 20:48 UTC, connorsmith256 commented on src/up/config.rs
> +pub(crate) const WASMCLOUD_DASHBOARD_PORT: &str = "4000";
Thought: I feel like this should be a u16 or similar, but I see the NATS port is a `&str` so don't worry about it

2023-04-04 21:16 UTC, aish-where-ya commented
> LGTM! The port constant should be based off an env var/flag in the future, but I think you're actually planning on working on #464 next? 👏

Yes!

2023-04-04 21:29 UTC, connorsmith256 requested changes

2023-04-04 21:29 UTC, connorsmith256 commented on src/up/mod.rs
> +    }
I missed this earlier, but after trying it out myself, I think this needs to be
```rust
wait_for_server(&url, "Washboard").await?;
```

With that change, I get
```
~/.cargo/bin/wash up -d

Ran out of retries waiting for host to start
```

Note that I think we'll also want to call `stop_nats` to clean up the NATS server, otherwise it's left dangling

2023-04-05 20:05 UTC, connorsmith256 approved these changes, later dismissed

2023-04-07 04:23 UTC, connorsmith256 approved these changes

2023-04-07 17:18 UTC, merged

2023-04-07 17:19 UTC, connorsmith256 commented
Resolves https://github.com/wasmCloud/wash/issues/430