Feat/allow file upload
wasmCloud/wash-archive pull request #513
Opened 2023-04-10 16:40 UTC by connorsmith256

## Feature or Problem
Resolves https://github.com/wasmCloud/wash/issues/509 by setting `WASMCLOUD_ALLOW_FILE_LOAD` to true for hosts started via `wash up`

Also fixed a clippy issue

I made the `allow-file-load` flag take an explicit value to account for the default being true. The alternative is to invert the logic in wash and make the flag something like `--disallow-file-load`. If preferred, I can swap that easily

## Related Issues
https://github.com/wasmCloud/wash/issues/509

## Release Information
Next (v0.17.0, since this is a new feature)

## Consumer Impact
After this change, users will be able to `wash up` and then `wash ctl start actor file://foo`

## Testing

### Manual Verification

Started a host with `wash up` and confirmed `WASMCLOUD_ALLOW_FILE_LOAD` was set and `wash ctl start actor file://foo` returned `:enoent`

Started a host with `wash up --allow-file-load true` and confirmed the same behavior

Started a host with `wash up --allow-file-load false` and confirmed the env var was not set and the ctl command returned `actor file loading is disabled`

2023-04-10 16:48 UTC, ricochet commented
We haven't started using the `deny` verb and `allow` fits, so I prefer what you have in the PR.

```bash
./target/debug/wash up -h | grep allow
      --allow-latest
          Determines whether OCI images tagged latest are allowed to be pulled from OCI registries and started [env: WASMCLOUD_OCI_ALLOW_LATEST=]
      --allowed-insecure <ALLOWED_INSECURE>
          A comma-separated list of OCI hosts to which insecure (non-TLS) connections are allowed [env: WASMCLOUD_OCI_ALLOWED_INSECURE=]
      --allow-file-load <ALLOW_FILE_LOAD>
          Denotes if a wasmCloud host should allow starting actors from the file system [env: WASMCLOUD_ALLOW_FILE_LOAD=] [default: true] [possible values: true, false]
```

2023-04-10 16:50 UTC, ricochet approved these changes, later dismissed

2023-04-10 17:39 UTC, ricochet commented
Integration test failure unrelated to these changes (signing go actors) and has been rep'd in other PR's.

2023-04-10 22:06 UTC, brooksmtownsend requested changes
Requesting one ergonomic change. The desired behavior is that it's denied by default, right?

2023-04-10 22:06 UTC, brooksmtownsend commented on src/up/mod.rs
> +    pub(crate) allow_file_load: Option<bool>,
This should just be a bool, it'll default to false

2023-04-10 22:10 UTC, ricochet commented
> Requesting one ergonomic change. The desired behavior is that it's denied by default, right?

The original issue requested enabled by default. https://github.com/wasmCloud/wash/issues/509

2023-04-10 22:37 UTC, connorsmith256 commented on src/up/mod.rs
> +    pub(crate) allow_file_load: Option<bool>,
See @ricochet's comment: I intended this to be allowed by default, per the source issue. Do you think that's a bad idea?

2023-04-12 15:38 UTC, brooksmtownsend approved these changes

2023-04-12 15:54 UTC, merged