Feat: Resurrect multiple wasmcloud hosts
wasmCloud/wash-archive pull request #527
Opened 2023-04-25 07:49 UTC by aish-where-ya

## Feature: Resurrect multiple local wasmcloud hosts successively. 
These hosts can be in detached or interactive mode.
The default NATS port is 4222 and the unless explicitly specified, the hosts will use ports from 4000 to 5000.

Usage: 
To spin a host run `wash up` or `wash up -d`. Specify the host port with `dashboard-port` flag.

To spin a host down, run `wash down --host-id <HOST-ID>` with the respective host-id or `wash down --all` for shutting down all hosts. The host-id can be obtained from `wash ctl get hosts`.

Details:
This host-id is generated using the `WASMCLOUD_HOST_SEED` environment variable. Unless specified by the user, a new n-keys key-pair is generated where the seed is passed on to this variable. A public key is generated and stored as `RELEASE_NODE` which is used to uniquely identify each host. The `RELEASE_NODE` is the host-id that the user gets on running `wash ctl get hosts`. 
When resurrecting consecutive hosts, if a NATS server is already running and a PID file exists, the consecutive hosts attach to this NATS server.

## Related Issues
Fixes #464 

## Release Information
Next

## Consumer Impact
The method to operate `wash up` and `wash down` will change with added options.

## Testing
Locally tested

Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x ] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)
NA

### Acceptance or Integration
NA

### Manual Verification
Manually verified!

2023-04-25 08:05 UTC, aish-where-ya commented
To be discussed:
Consider a host is spun up in interactive mode and consecutive hosts are spun in interactive/detached mode.
When Ctrl+C is hit in the terminal that runs the first interactive host (that also spins NATS), NATS is killed as soon as Ctrl+C is hit. The expected behavior here is for the host to stop but NATS to keep running.

This case is encountered only in this specific case.

This results in zombie processes if the interactive host was the first one to be run and NATS was spawned along with this first host. The zombie processes are the other hosts that were connected to this NATS server. This is because NATS was the initial process and the host was spun using `group_spawn` on UNIX or `spawn` on Windows that returns a child process group or child process respectively. More inspection is needed on this and how do we want the expected/ideal behavior here to be.

2023-04-25 17:49 UTC, connorsmith256 requested changes
So excited for this. Mostly nits, and a few questions

2023-04-25 17:49 UTC, connorsmith256 commented on src/down/mod.rs
> +                tokio::time::sleep(Duration::from_secs(6)).await;
We should find another way to do this. If a user has 3 hosts running, taking ~20s to stop all of them is really slow. Also, if 3 hosts are running, and the user just stops one of them, we don't need to wait at all since we're not going to stop NATS

Why was this necessary? We didn't have this sleep before, right? Was the `host_stopped` event not getting emitted before the NATS server shut down or something?

2023-04-25 17:49 UTC, connorsmith256 commented on src/down/mod.rs
> +            if let Ok(output) = stop_wasmcloud(&host_bin, Some(host.id.to_string())).await {
The following if/else is duplicated 3 times, so it feels like a good candidate for a separate function

2023-04-25 17:49 UTC, connorsmith256 commented on src/down/mod.rs
> +        out_text.push_str("NATS server is still running\n");
I don't think this is right. We shouldn't add `nats_stopped` to the JSON output, and I don't think we need to print "still running" either

2023-04-25 17:49 UTC, connorsmith256 commented on src/down/mod.rs
> +        .env("RELEASE_NODE", host_id.unwrap_or("".to_string()))
Nit: `RELEASE_NODE` should probably be defined as a const. I noticed we have it in `src/up/config.rs`, so you can pull it in from there. We already depend on `up` from `down` for a couple other consts

2023-04-25 17:49 UTC, connorsmith256 commented on src/up/config.rs
> +    other_host_config_values: HashMap<String, String>,
Can we add these to `wasmcloud_opts` instead?

2023-04-25 17:49 UTC, connorsmith256 commented on src/up/config.rs
> +    if let Some(value) = host_config.get("WASMCLOUD_HOST_SEED") {
Nit: use the const here

Also, we should `bail` in an `else` block, since this value needs to exist

2023-04-25 17:49 UTC, connorsmith256 commented on src/up/config.rs
> +        );
Suggestion: a comment here explaining that we're tagging the OTP process with the host's ID so we can find it later would be helpful

2023-04-25 17:49 UTC, connorsmith256 commented on src/up/mod.rs
> +            tokio::net::TcpStream::connect(&nats_listen_address)
Do we need this anymore? We've already checked the TCP connection in `is_nats_running`, right?

2023-04-25 17:49 UTC, connorsmith256 commented on src/up/mod.rs
>      } else {
I think this else block is a bug. `start_only` says
```
/// If enabled, wasmCloud will not be downloaded if it's not installed
```

So I don't understand why we're trying to clean up NATS and return an error whenever this flag is set

Should this else block exist at all?

2023-04-25 17:49 UTC, connorsmith256 commented on src/up/mod.rs
> +        port_number
What if the user supplied a port, but that port is already in use? I think we'll need to confirm the port is open

2023-04-25 17:49 UTC, connorsmith256 commented on src/up/mod.rs
> +                // Find number of hosts running. If they are 0, stop nats
Suggestion: we could get around this cleanup code if we check for an open port before we start the NATS server

2023-04-25 17:49 UTC, connorsmith256 commented on src/up/mod.rs
> +        "WASMCLOUD_DASHBOARD_PORT".to_string(),
Nit: use the const

2023-04-25 17:49 UTC, connorsmith256 commented on src/up/mod.rs
> +            // TODO: check number of hosts before stopping nats
Leftover TODO?

2023-04-25 17:49 UTC, connorsmith256 commented on src/up/mod.rs
> +        if nats_is_running {
What if NATS was started by another command? I think we'll want the same logic we had elsewhere: check if there are zero running hosts before cleaning up. Alternatively, we could only ever clean up the NATS server if it was started by the current command

2023-04-25 17:49 UTC, connorsmith256 commented on src/up/mod.rs
> +            host_env.get("RELEASE_NODE").cloned(),
Nit: use const

2023-04-25 17:49 UTC, connorsmith256 commented on src/up/mod.rs
> +        // The following code does nothing as NATS is killed as soon as Ctrl+C is hit.
Let's just delete this commented code, since it's not needed for the reason you put in the comment

2023-04-25 17:49 UTC, connorsmith256 commented on src/up/mod.rs
> +        let url = format!("{}:{}", "http://localhost", host_port);
Nit: use const

2023-04-25 17:49 UTC, connorsmith256 commented on src/up/mod.rs
> +pub(crate) async fn is_nats_running(
I think this should be moved to `start/nats.rs`

2023-04-25 17:49 UTC, connorsmith256 commented on src/util.rs
> +    let dummy_nats_client = async_nats::ConnectOptions::default()
Why `dummy`?

2023-04-25 17:49 UTC, connorsmith256 commented on src/util.rs
> +pub(crate) async fn get_wasmcloud_hosts<P>(bin_path: P) -> Result<Vec<Host>>
I think this will need to take some args, like the NATS host, NATS port, and JS domain. Those are all in `WasmcloudOpts` so maybe you can just pass that

2023-04-25 17:49 UTC, connorsmith256 commented on src/util.rs
> +        // .js_domain(WASMCLOUD_JS_DOMAIN.to_string()) // accept this as a var from wash up or env vars
This will need to be done

2023-04-25 17:49 UTC, connorsmith256 commented on src/util.rs
> +    for host in hosts {
Nit: instead of a mutable for loop, this could be done with `hosts.iter().filter(|host| is_wasmcloud_running...).collect()`

2023-04-25 17:49 UTC, connorsmith256 commented on src/util.rs
> +        .build()
Optimization: since we're only interested in local hosts, we could potentially set the `auction_timeout` to be lower than the default of 2s. Something in the ballpark of ~500ms might work, possibly even lower (needs testing). That would make `wash down`/ctrl-C go faster

2023-04-25 18:27 UTC, brooksmtownsend requested changes
This is an awesome change and I love how simple the RELEASE_NODE can be configured by using the host public key. Mostly nits and refactoring opportunities

2023-04-25 18:27 UTC, brooksmtownsend commented on crates/wash-lib/src/start/wasmcloud.rs
> +    };
If this environment variable isn't set, then the host will try to start on port `4000`. I think we should still default to `4000` here

2023-04-25 18:27 UTC, brooksmtownsend commented on src/down/mod.rs
> +    } else if let Some(host_id) = _cmd.host_id {
Now that you're using the cmd, I would suggest removing the underscore and just using it as `cmd`

2023-04-25 18:27 UTC, brooksmtownsend commented on src/down/mod.rs
> +        sp.update_spinner_message(format!("Stopping host {}...", host.id));
nit: space between `{}` and `...`

2023-04-25 18:27 UTC, brooksmtownsend commented on src/down/mod.rs
> +                tokio::time::sleep(Duration::from_secs(6)).await;
Since this is used multiple times in these if/else branches, would suggest moving the sleep to right before stopping the NATS server

2023-04-25 18:27 UTC, brooksmtownsend commented on src/down/mod.rs
> +        sp.update_spinner_message(format!("Stopping host {}...", host.id));
nit: space between {} and ...

2023-04-25 18:27 UTC, brooksmtownsend commented on src/down/mod.rs
> +                    stopped_hosts += 1;
Would suggest moving this sleep to right before stopping NATS, we can stop multiple hosts quickly

2023-04-25 18:27 UTC, brooksmtownsend commented on src/down/mod.rs
> +        sp.println("No local wasmCloud hosts detected.");
I think you can `bail` here

2023-04-25 18:27 UTC, brooksmtownsend commented on src/down/mod.rs
> +        .env("RELEASE_NODE", host_id.unwrap_or("".to_string()))
If you don't supply the host_id here, and we try to stop a local host, does it work? Wondering if it's better to only supply the RELEASE_NODE environment variable if the host_id is provided

2023-04-25 18:27 UTC, brooksmtownsend commented on src/up/config.rs
> +        );
If for some reason we cannot create a seed here, we shouldn't insert `None` as I think that will break the host. Double checking

2023-04-25 18:27 UTC, brooksmtownsend commented on src/up/config.rs
> +        );
```
14:07:37.256 [error] Failed to obtain host public key from seed: (None). Generating a new host key instead.
```
It won't break, but it will generate its own

2023-04-25 18:27 UTC, brooksmtownsend commented on src/up/config.rs
> +    }
It might be better to move this block up when you're inserting `WASMCLOUD_HOST_SEED`, since you already have the seed value available if provided by `wasmcloud_opts` or if you generated it on your own

2023-04-25 18:27 UTC, brooksmtownsend commented on src/up/config.rs
> +    }
I think this should be part of `wasmcloud_opts`, and then you can remove the other host config values

2023-04-25 18:27 UTC, brooksmtownsend commented on src/up/mod.rs
> +        if nats_is_running {
We want to make sure we close the NATS server if we launched it as a part of this `wash up` and wasmCloud was set to start only

2023-04-25 18:27 UTC, brooksmtownsend commented on src/up/mod.rs
> +        // }
Hm, so in this case we don't have any control over NATS in the foreground?

I think that's ok, using `wash up` in the foreground to launch NATS isn't the preferred method when you're running multiple hosts, and users should use the detached mode if they want it to be long running. I think you can remove this comment + code, unless you wanted to leave a note that the CTRL+C stopped the NATS server

2023-04-25 18:27 UTC, brooksmtownsend commented on src/up/mod.rs
> +        let url = format!("{}:{}", "http://localhost", host_port);
nit: This should use the `LOCALHOST` variable or just have `http://localhost` in the format string

2023-04-25 18:27 UTC, brooksmtownsend commented on src/up/mod.rs
> +pub(crate) async fn is_nats_running(
A doc comment would be helpful here to detail the different return value meanings

2023-04-25 18:27 UTC, brooksmtownsend commented on src/up/mod.rs
> +        }
nit: could this be simplified with a `.is_err()` check to make it just an if statement?

2023-04-25 18:27 UTC, brooksmtownsend commented on src/util.rs
> +    let dummy_nats_client = async_nats::ConnectOptions::default()
nit: this can just be `nats_client`

2023-04-25 18:27 UTC, brooksmtownsend commented on src/util.rs
> +        // .js_domain(WASMCLOUD_JS_DOMAIN.to_string()) // accept this as a var from wash up or env vars
I don't think the JS domain is needed as long as we're just making the ctl request, so this can be left off

2023-04-25 18:27 UTC, brooksmtownsend commented on src/util.rs
> +pub(crate) async fn get_wasmcloud_hosts<P>(bin_path: P) -> Result<Vec<Host>>
this function will likely have to take some control interface connection variables to ensure you're fetching hosts for the proper Nats server URL, lattice prefix, etc. They should be available on the UpCommand's connectionopts struct, and there should be a util function for creating a NATS client from that struct

2023-04-25 18:27 UTC, brooksmtownsend commented on src/up/mod.rs
> +    );
If you move this section inside of the function that configures the host environment, I think you can avoid having an extra hashmap for the one value

2023-04-25 18:31 UTC, brooksmtownsend commented on src/down/mod.rs
> +        out_text.push_str("NATS server is still running\n");
I like having some indication of what `wash down` took care of, perhaps we can adjust the wording? I'm trying to think of the JSON output as something we could run operationally, then we could assert that after the down that NATS is no longer running

2023-04-25 18:32 UTC, brooksmtownsend commented on src/up/config.rs
> +    }
resolving this as Connor touched on it above

2023-04-25 18:33 UTC, brooksmtownsend commented on src/up/config.rs
> +    if let Some(value) = host_config.get("WASMCLOUD_HOST_SEED") {
Left a comment a little further down, but I think if we move the logic in this `if` branch up to the above if/else, then we'll always know the host seed

2023-04-25 18:34 UTC, brooksmtownsend commented on src/up/mod.rs
>      } else {
So, if we _only_ want to start wasmCloud and not download it, we start NATS and then try to start wasmCloud. If for some reason wasmCloud isn't installed, then we would just have a dangling NATS server if we didn't clean it up here

2023-04-25 18:39 UTC, brooksmtownsend commented on src/up/mod.rs
> +        let url = format!("{}:{}", "http://localhost", host_port);
resolving as Connor said it

2023-04-25 18:39 UTC, brooksmtownsend commented on src/util.rs
> +        // .js_domain(WASMCLOUD_JS_DOMAIN.to_string()) // accept this as a var from wash up or env vars
@connorsmith256 resolving your comment, I think with taking the `ConnectionOpts` the JS domain will come with it but I don't think it's necessary

2023-04-25 18:39 UTC, brooksmtownsend commented on src/util.rs
> +    for host in hosts {
This might be hard, because of the `.await`'s unless we collect into a bunch of futures

2023-04-25 18:41 UTC, brooksmtownsend commented
Regarding this
```
Consider a host is spun up in interactive mode and consecutive hosts are spun in interactive/detached mode.
When Ctrl+C is hit in the terminal that runs the first interactive host (that also spins NATS), NATS is killed as soon as Ctrl+C is hit. The expected behavior here is for the host to stop but NATS to keep running.
```

I think this is actually okay and not much we can do to get around it, the user specifies to run NATS and wasmCloud in the foreground and then they kill it with `CTRL+C`. So I don't think we need to design around this edge case 😄

2023-04-25 23:14 UTC, connorsmith256 commented on src/up/mod.rs
>      } else {
Right, we should clean up the NATS server if we fail to start wasmcloud. But that's not what's happening here. This is just saying "if start_only, stop nats", which I think is a bug

Give `wash up --wasmcloud-start-only` a try. For me it doesn't try to download wasmcloud, it just immediately errors

(Also, since the NATS process is a child of the wash command and not in its own process group, the cleanup happens automatically)

2023-04-25 23:19 UTC, connorsmith256 commented on src/down/mod.rs
> +        .env("RELEASE_NODE", host_id.unwrap_or("".to_string()))
I _think_ this is okay, since _usually_ an empty env var is the same as an env var which isn't present

I just double-checked the `bin/wasmcloud_host` script and it has:
```bash
RELEASE_NAME="${RELEASE_NAME:-"wasmcloud_host"}"
...
RELEASE_NODE="${RELEASE_NODE:-"$RELEASE_NAME"}"
```

So an empty string should be fine here

2023-04-26 17:17 UTC, aish-where-ya commented on src/down/mod.rs
> +                tokio::time::sleep(Duration::from_secs(6)).await;
This sleep was a part of the original code but yes, if this has something to do with the `host_stopped` event being delayed, it can be moved to the part before stopping NATS.

2023-05-04 16:42 UTC, aish-where-ya commented on src/up/mod.rs
>      } else {
You're right. After discussing with @brooksmtownsend , this can be resolved as a separate PR for #492.

2023-05-04 17:43 UTC, brooksmtownsend commented on src/down/mod.rs
> +        out_text.push_str("NATS server is still running\n");
Talked with @connorsmith256 and while this is a little verbose, I think we'll take a little more information here just in case we want to assert `nats_stopped == true` in a future script without worrying about the absence of the field

2023-05-16 18:35 UTC, brooksmtownsend commented
Unfortunately I have to close this PR since the number of conflicts is just a little too great to resolve accurately. Given the outstanding comments as well, I've picked the relevant pieces of this PR into https://github.com/wasmCloud/wash/pull/556/commits/873ddf8027e27af088083e8c7299083ea071fd03 where we'll pick up the work. Thank you @aish-where-ya for getting this ball rolling!

2023-05-16 18:35 UTC, closed without merging