feat(*) wash burrito support
wasmCloud/wash-archive pull request #556
Opened 2023-05-15 19:00 UTC by brooksmtownsend

## Feature or Problem
This PR adds support for running https://github.com/wasmCloud/wasmcloud-otp/pull/616 artifacts (burrito releases) with `wash up`. This will be a significant breaking change and will bump the minimum wasmCloud version that `wash` can manage from `0.57.1` (when we stopped using distillery) to `0.63.0`.

PR action items:
- [x] Add support to launch burrito releases with `wash up`
- [x] Stop burrito-release launched hosts with `wash down`
- [x] Add `maintenance uninstall` to the `wash drain` command (I think this can be done in a separate PR since burritos auto-upgrade)
- [x] Test on multiple platforms (Works on aarch64 mac, aarch64 linux, and x86 Windows)
- [x] General code cleanup, TODOs left around the implementation 

## Related Issues
Fixes https://github.com/wasmCloud/wash/issues/464 after pulling in implementation from #527 
Fixed #492 

## Release Information
`wash` v0.18.0
`wash-lib` v0.9.0

~?? We may need to hold on merging this PR until we can release 0.18 as scheduled~
Changed to v0.18.0 as it makes sense to release this with wadm

## Consumer Impact
Consumers won't notice a difference with running the wasmCloud host, only that the downloaded assets are a single binary `wasmcloud_host` instead of a tarball-ed directory

## Testing

Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)

### Acceptance or Integration

### Manual Verification
As of creation, I've run `cargo run -- up` and `cargo run -- up -d` which worked great. `down` now works by using NATS to tell hosts to stop instead of executing the `mix release`, and I've verified that a variety of scenarios work well.
1. Stopping one host when multiple are running do not stop NATS/wadm
2. Stopping the only host will stop all resources
3. Not specifying a host ID will exit early and display the running hosts to the user
4. Trying to stop a host when nothing is running will clean up NATS and wadm

2023-05-17 16:00 UTC, brooksmtownsend commented on crates/wash-lib/tests/parser/files/withcargotoml/Cargo.toml
> +crate-type = ["cdylib", "rlib"]
note: this change to the test artifact lets people run `cargo install --git <this repo>` again. `cargo` was picking this crate up as a binary you could install

2023-05-22 16:27 UTC, brooksmtownsend commented on src/up/mod.rs
> +            }
don't forget this, whoever opened this PR

2023-05-22 16:28 UTC, brooksmtownsend commented on crates/wash-lib/src/start/wasmcloud.rs
> +    let wasmcloud_host_burrito = reqwest::get(url).await?.bytes().await?.to_vec();
@thomastaylor312 Line 170 is the one that feels weird, in tandem with having to copy it with `.as_slice()`

2023-06-05 21:47 UTC, connorsmith256 requested changes
Just nits and questions

2023-06-05 21:47 UTC, connorsmith256 commented on crates/wash-lib/src/start/wasmcloud.rs
> +    let wasmcloud_host_burrito = reqwest::get(url).await?.bytes().await?.to_vec();
Is there a reason we're calling `reqwest::get(url)` twice?

2023-06-05 21:47 UTC, connorsmith256 commented on crates/wash-lib/src/start/wasmcloud.rs
> -
What happens now if you call the burrito app when one is already running?

2023-06-05 21:47 UTC, connorsmith256 commented on crates/wash-lib/src/start/wasmcloud.rs
> +    let file_checks = vec![metadata(bin_file.clone())];
Under the assumption we're sticking to a single binary from here on out, you could drop the join_all iter stuff

2023-06-05 21:47 UTC, connorsmith256 commented on crates/wash-lib/src/start/wasmcloud.rs
> +        .replace("windows", "windows.exe");
Ah yes, I love running windows.exe as my OS 😜

2023-06-05 21:47 UTC, connorsmith256 commented on src/down/mod.rs
> +                    .map_err(|e| anyhow!(e));
Can we TODONE this and line 176?

2023-06-05 21:47 UTC, connorsmith256 commented on src/up/mod.rs
>          || cmd.nats_opts.nats_remote_url.is_some() && cmd.nats_opts.nats_credsfile.is_some()
This condition is gnarly. The comment helps, but consider simplifying the expression so a comment isn't necessary

2023-06-05 21:47 UTC, connorsmith256 commented on src/up/mod.rs
> +            }
👀

2023-06-05 21:47 UTC, connorsmith256 commented on src/up/mod.rs
I can't comment on line 358, and I know it's not technically related to the burrito stuff, but if you want to fix https://github.com/wasmCloud/wash/issues/492 while you're here.... it's been a thorn in our side for a while

2023-06-05 21:47 UTC, connorsmith256 commented on src/up/mod.rs
> +        for i in 4000..=5000 {
Nit, but if `DEFAULT_DASHBOARD_PORT` were to change, this would become a bug

2023-06-06 14:35 UTC, brooksmtownsend commented on crates/wash-lib/src/start/wasmcloud.rs
> +    let wasmcloud_host_burrito = reqwest::get(url).await?.bytes().await?.to_vec();
Nope! Good catch

2023-06-06 14:35 UTC, brooksmtownsend commented on crates/wash-lib/src/start/wasmcloud.rs
> -
It launches another one, no conflicts on the burrito side (but it will crash if the port is allocated for the washboard)

2023-06-06 14:52 UTC, brooksmtownsend commented on src/down/mod.rs
> +                    .map_err(|e| anyhow!(e));
I think on line 176 it's handled since that one will bubble up, next commit here will have us logging for errors and not including the host IDs

2023-06-06 15:06 UTC, brooksmtownsend commented on src/up/mod.rs
> +            }
I believe in #527 we made the opinion here that if you use `wash up` to start a host + NATS, then start another host, and then kill the foregrounded wash up, then we shouldn't take the action to keep NATS around for the user

2023-06-06 15:59 UTC, connorsmith256 commented on crates/wash-lib/src/start/wasmcloud.rs
> -
Hmm, can you share the error message? It might be okay. This might be an indirect way to make `wash up` idempotent now 😅 I just want to make sure it's not confusing to users

2023-06-06 16:02 UTC, connorsmith256 submitted a review, later dismissed
:shipit:

2023-06-06 21:56 UTC, connorsmith256 commented on src/up/mod.rs
> +            }
Ah right. So should we remove the TODO?

2023-06-07 16:05 UTC, brooksmtownsend commented on crates/wash-lib/src/start/wasmcloud.rs
> -
Well... right now it actually "just works" and launches another host on port 4001

2023-06-07 17:21 UTC, connorsmith256 commented on crates/wash-lib/src/start/wasmcloud.rs
> -
Ah okay, this is captured separately so no worries: https://github.com/wasmCloud/wash/issues/602

2023-06-09 17:22 UTC, connorsmith256 approved these changes, later dismissed

2023-06-12 20:25 UTC, thomastaylor312 requested changes
One really minor change around the default wasmcloud version

2023-06-12 20:25 UTC, thomastaylor312 commented on crates/wash-lib/src/start/wasmcloud.rs
> +const MINIMUM_WASMCLOUD_VERSION: &str = "0.63.0";
Should this be 0.63.1?

2023-06-12 20:25 UTC, thomastaylor312 commented on crates/wash-lib/src/start/wasmcloud.rs
> +        tokio::io::copy(&mut wasmcloud_host_burrito.as_slice(), &mut wasmcloud_file).await?;
You can actually use `bytes_stream` and consume the stream rather than all of this as_slice stuff if you want, but this does work.

If you want to use `bytes_stream` you'll want the [`StreamReader`](https://docs.rs/tokio-util/latest/tokio_util/io/struct.StreamReader.html) type from the tokio util crate

2023-06-12 20:25 UTC, thomastaylor312 commented on crates/wash-lib/src/start/wasmcloud.rs
> +    const WASMCLOUD_VERSION: &str = "v0.63.0";
Don't forget to bump here too

2023-06-12 20:25 UTC, thomastaylor312 commented on src/up/config.rs
> +pub(crate) const WASMCLOUD_HOST_VERSION: &str = "v0.63.0";
Version here too

2023-06-12 20:49 UTC, brooksmtownsend commented on crates/wash-lib/src/start/wasmcloud.rs
> +const MINIMUM_WASMCLOUD_VERSION: &str = "0.63.0";
It should be 0.63.0 for this PR, but I will bump the default to 0.63.1

2023-06-12 20:49 UTC, brooksmtownsend commented on crates/wash-lib/src/start/wasmcloud.rs
> +const MINIMUM_WASMCLOUD_VERSION: &str = "0.63.0";
to clarify: the minimum _burrito_ release is 0.63.0, but the patch that includes something nice for wadm is 0.63.1 so it makes more sense to use that

2023-06-12 20:50 UTC, brooksmtownsend commented on src/up/config.rs
> +pub(crate) const WASMCLOUD_HOST_VERSION: &str = "v0.63.0";
bumping here

2023-06-12 20:50 UTC, brooksmtownsend commented on crates/wash-lib/src/start/wasmcloud.rs
> +    const WASMCLOUD_VERSION: &str = "v0.63.0";
here is ok I think because it's a test, right?

2023-06-12 21:01 UTC, thomastaylor312 approved these changes

2023-06-13 10:03 UTC, merged