Updates to dev container
wasmCloud/wash-archive pull request #559
Opened 2023-05-17 18:38 UTC by lee-orr

## Feature or Problem

This updates the dev container so it has access to all the required development tools (nextest, tinygo) as well as cargo watch, as well as resolving a permission issue with cargo/rust analyzer when using Microsoft's default dev container image as a base.

## Related Issues

## Release Information

## Consumer Impact

## Testing

Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)

### Acceptance or Integration

### Manual Verification

2023-05-17 18:40 UTC, brooksmtownsend requested changes
I had a quick question around the base image, but otherwise this looks fantastic. @lee-orr make sure to sign your commit so we can keep the DCO check passing, you can find details on how to do so if you click **Details** next to the failing action

2023-05-17 18:40 UTC, brooksmtownsend commented on .devcontainer/devcontainer.json
>  	"features": {
@lee-orr I was just considering this earlier today, what do you think about using the Rust base image so that we can skip that step when starting it up?

2023-05-17 18:45 UTC, lee-orr commented on .devcontainer/devcontainer.json
>  	"features": {
Let me give it a test - I seem to remember having some issue with it when I tried in the rusty_dev_containers repo, but I may be remembering incorrectly

2023-05-17 18:48 UTC, brooksmtownsend commented on .devcontainer/devcontainer.json
>  	"features": {
Okay cool, if it doesn't work then that's all good, I just figured we could save ourselves a few seconds of building 😄

2023-05-17 18:54 UTC, lee-orr commented on .devcontainer/devcontainer.json
>  	"features": {
Do you know if this will work with regular go (i.e. no tiny go)? Looks like the lack of a sudo in rust: bullseye is causing issues with the existing tiny go devcontainer feature

2023-05-17 19:00 UTC, brooksmtownsend commented on .devcontainer/devcontainer.json
>  	"features": {
Bleh. Unfortunately at this point Go isn't quite at the point where it can work for our actors, though that's coming in the not-too-far future. I think it's probably better to leave it as bullseye then

2023-05-17 19:00 UTC, brooksmtownsend commented on .devcontainer/devcontainer.json
>  	"features": {
If you want to back that change out I can approve 👍🏻

2023-05-17 19:13 UTC, lee-orr commented on .devcontainer/devcontainer.json
>  	"features": {
I'm just adding tiny go to the now not aptly named rusty_dev_containers repo, and once that builds I'll confirm this all works

2023-05-17 19:27 UTC, lee-orr commented on .devcontainer/devcontainer.json
>  	"features": {
Looks like it works!

2023-05-18 13:28 UTC, brooksmtownsend approved these changes

2023-05-18 13:29 UTC, merged