feat(ux): flatten `wash ctl link` into `wash link`
wasmCloud/wash-archive pull request #569
Opened 2023-05-22 16:18 UTC by vados-cosmonic

## Feature or Problem

Flatten `wash ctl link` into `wash link`. 

Note that *both* ways of accessing this command will exist, until we are ready to go *only* to `wash link` (and update relevant documentation).

## Related Issues

## Release Information

`next`

## Consumer Impact

Customers will be able to use a more streamlined/convenient command structure.

## Testing

Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)

### Acceptance or Integration

An integration test for `wash link` was added which runs `wash link query`

### Manual Verification

2023-05-22 19:00 UTC, thomastaylor312 requested changes
Logic looks good. Just a few fixes needed for tests

2023-05-22 19:00 UTC, thomastaylor312 commented on tests/common.rs
> +        let epoch_secs = SystemTime::now()
It might be better to use a random string here instead. If multiple tests run at the same time, there is a chance they'll get the same number of seconds (since we aren't using millis here)

2023-05-22 19:00 UTC, thomastaylor312 commented on tests/common.rs
> +        let stdout = std::fs::File::create(&log_path)
Nit (as this is a test): Should probably be using tokio file stuff rather than blocking io

2023-05-22 19:00 UTC, thomastaylor312 commented on tests/common.rs
> +    pub async fn destroy(&mut self) -> Result<()> {
Let's make this an implementation of `Drop` instead of requiring the caller to manually destroy resources

2023-05-22 19:22 UTC, thomastaylor312 requested changes
Some additional comments I thought of around putting things in wash-lib

2023-05-22 19:22 UTC, thomastaylor312 commented on src/common/link_cmd.rs
> +pub(crate) struct LinkDelCommand {
Looking at this again, none of this has wash specific env vars, so this whole file should probably live in wash-lib! It will be easier to share/reuse from there

2023-05-22 19:22 UTC, thomastaylor312 commented on src/ctl/mod.rs
> +pub(crate) async fn ctl_client_from_opts(
Nit: This function looks like it could be handy in wash-lib, but it isn't required to move for this PR

2023-05-23 01:05 UTC, vados-cosmonic commented on tests/common.rs
> +        let epoch_secs = SystemTime::now()
Hey so the tests are marked `#[serial]` so this shouldn't happen, *but* I definitely agree with you on using the random name. I'll pull in `rand` and use that

- [ ] use `rand` for random test name with the wash instance

2023-05-23 01:13 UTC, vados-cosmonic commented on tests/common.rs
> +        let stdout = std::fs::File::create(&log_path)
So this actually needed to be a regular file, for two reasons as far as I can see

- [`tokio::process::Command#stdout`](https://docs.rs/tokio/latest/tokio/process/struct.Command.html#method.stdout) takes a regular `Stdio` which is `From<std::fs::File>`. I could do `into_std` here after making the file with the `tokio` version though.

- the `wash()` command is actually not async (most of the tests utilities aren't actually), so I'd need to actually change that to get properly async in the first place.

That said, I can change *both* of those bits to use the `tokio` variants -- been wanting to remove `wash()` anyway -- so I'll do that

[ ] use `tokio::fs::File` and remove use of `wash` (should be able to use cargo ENV var path)

2023-05-23 01:19 UTC, vados-cosmonic commented on tests/common.rs
> +    pub async fn destroy(&mut self) -> Result<()> {
So since there's an `tokio::process::Child` in the Struct, this means I have to do `async` `Drop` -- there are some ways to do it, but [the decent solutions](https://stackoverflow.com/questions/71541765/rust-async-drop) look like they involve a copy + spawn...

Do you have a good pattern that you usually use that I can look at? Otherwise I'll use the

2023-05-23 01:21 UTC, vados-cosmonic commented on src/common/link_cmd.rs
> +pub(crate) struct LinkDelCommand {
Oh great, will move this there!

- [ ] move `link_cmd` to `wash-lib`

2023-05-23 01:21 UTC, vados-cosmonic commented on src/ctl/mod.rs
> +pub(crate) async fn ctl_client_from_opts(
- [ ] move `ctl_client_from_opts` into `wash-lib`

2023-05-23 01:38 UTC, vados-cosmonic commented on tests/common.rs
> +        let stdout = std::fs::File::create(&log_path)
OK, I reworked it a bit and just made sure that `kill_on_drop` was set for the command -- removed the use of `wash()`, but I *did not* update the rest of the code there to avoid this PR getting too big (they're all still `#[test]`s).

2023-05-23 02:02 UTC, vados-cosmonic commented on src/common/link_cmd.rs
> +pub(crate) struct LinkDelCommand {
Hey @thomastaylor312 actually looking at this, this code has a dependency on the `wasmcloud_control_interface` crate -- that's not in `wash-lib` -- is there any reason behind that?

2023-05-23 15:46 UTC, vados-cosmonic commented on src/common/link_cmd.rs
> +pub(crate) struct LinkDelCommand {
Just as an update here, `wasmcloud_control_interface` is OK to add as a dep!

2023-05-23 18:51 UTC, thomastaylor312 requested changes
This is almost there. Clarified one thing I missed before that needs to be address, but the rest of the things are nits you can address or ignore at your leisure

2023-05-23 18:51 UTC, thomastaylor312 commented on crates/wash-lib/src/cli/link.rs
> +pub async fn query_links(wco: WashConnectionOptions) -> Result<LinkDefinitionList> {
Note to ourselves for later: It kinda feels like these methods (like query_links and `delete_link`) could be on the impl of `WashConnectionOptions`, but since they are currently exclusively used for just CLI commands I think this current way of doing things is just fine

2023-05-23 18:51 UTC, thomastaylor312 commented on crates/wash-lib/src/config.rs
> +use crate::context::WashContext;
Nit: Move crate imports to a section below external imports

2023-05-23 18:51 UTC, thomastaylor312 commented on crates/wash-lib/src/config.rs
> +        let ctl_jwt = if self.ctl_jwt.is_some() {
Nit(as I know this is code you didn't write): I think these similar blocks can all be simplified to something like this (not actually tested):

```rust
self.ctl_jwt.or_else(|| self.ctx.as_ref().map(|c| c.ctl_jwt.clone())).unwrap_or_default()
```

Generally it is more idiomatic to not use `is_some` unless it is a guard clause or you aren't using the data in the option

2023-05-23 18:51 UTC, thomastaylor312 commented on crates/wash-lib/src/config.rs
> +        let timeout = tokio::time::Duration::from_millis(self.timeout_ms);
This timeout is for control interface timeout and not nats timeout, do we actually need to return it? It looks like we ignore it everywhere in the rest of the code

2023-05-23 18:51 UTC, thomastaylor312 commented on src/app/mod.rs
> +    let wco: WashConnectionOptions = cmd.opts.try_into()?;
Nit: Might be better to just oneline this rather than having a var you immediately consume

2023-05-23 18:51 UTC, thomastaylor312 commented on src/common/link_cmd.rs
> +pub(crate) struct LinkDelCommand {
@vados-cosmonic I actually think these commands can be moved over to wash-lib as well. That is what I originally meant, but didn't convey very well. You can see another example of this here: https://github.com/wasmCloud/wash/blob/main/crates/wash-lib/src/cli/claims.rs

2023-05-23 18:51 UTC, thomastaylor312 commented on tests/common.rs
> +    pub fn destroy(&mut self) -> Result<()> {
I think this can be removed now that drop is in place. Definitely better than allowing unused here

2023-05-24 01:07 UTC, vados-cosmonic commented on crates/wash-lib/src/config.rs
> +use crate::context::WashContext;
Woops yeah, will move!

- [ ] move crate import

2023-05-24 01:09 UTC, vados-cosmonic commented on crates/wash-lib/src/config.rs
> +        let ctl_jwt = if self.ctl_jwt.is_some() {
yeah I agree -- I didn't change the previous code but since I'm doing another pass anyway, will add this in -- was weird to me as well... Half the setup was one pattern and then the rest did this pattern

2023-05-24 01:16 UTC, vados-cosmonic commented on crates/wash-lib/src/config.rs
> +        let timeout = tokio::time::Duration::from_millis(self.timeout_ms);
Yep saw that, I'm not sure why this code is like this to be honest -- it's like it returns a timeout for the caller to use if they want to, not sure why this is necessary. 

Open to removing it if you'd like

2023-05-24 01:20 UTC, vados-cosmonic commented on src/app/mod.rs
> +    let wco: WashConnectionOptions = cmd.opts.try_into()?;
Yeah that's what I did initially, it turns out to require a pretty ugly type hint:

```rust
    let (client, _timeout) = <ConnectionOpts as TryInto<WashConnectionOptions>>::try_into(cmd.opts)?.into_nats_client().await?;
```

2023-05-24 01:21 UTC, vados-cosmonic commented on src/common/link_cmd.rs
> +pub(crate) struct LinkDelCommand {
Oh sure -- will move these too:

- [ ] move commands into wash-lib

2023-05-24 01:24 UTC, vados-cosmonic commented on crates/wash-lib/src/cli/link.rs
> +pub async fn query_links(wco: WashConnectionOptions) -> Result<LinkDefinitionList> {
Yeah I'd think that should go on something like a `WashInstance`, which maybe has a constructor that takes a `WashConnectionOptions` -- agreed though, would be nice to have these on some consistent object (especially so we can re-use connections).

2023-05-24 01:29 UTC, vados-cosmonic commented on tests/common.rs
> +    pub fn destroy(&mut self) -> Result<()> {
Sure -- `drop` actually uses this (so `allow(unused)` could have been removed probably), but I just moved all this to `drop`

2023-05-24 02:53 UTC, vados-cosmonic commented on src/app/mod.rs
> +    let wco: WashConnectionOptions = cmd.opts.try_into()?;
I've gone ahead and changed all of them to this (though it `fmt`s to a more lines)

2023-05-24 15:36 UTC, connorsmith256 submitted a review, later dismissed
LGTM!

2023-05-24 15:51 UTC, vados-cosmonic commented
@connorsmith256 one more small refactor while I was looking -- removed the `link.rs` file completely!

2023-05-24 15:53 UTC, thomastaylor312 commented on crates/wash-lib/src/config.rs
> +        let timeout = tokio::time::Duration::from_millis(self.timeout_ms);
Let's just remove it, but not gonna block on it here

2023-05-24 15:54 UTC, thomastaylor312 commented on src/app/mod.rs
> +    let wco: WashConnectionOptions = cmd.opts.try_into()?;
You can revert it then, I thought it would be able to type infer here

2023-05-24 15:59 UTC, thomastaylor312 approved these changes

2023-05-24 16:12 UTC, merged