added support for WASH_RPC_HOST, _TIMEOUT, and _PORT to wash ctl
wasmCloud/wash-archive pull request #64
Opened 2021-01-21 15:20 UTC by jsoverson

This PR adds support for the env variables `WASH_RPC_HOST`, `WASH_RPC_TIMEOUT`, and `WASH_RPC_PORT` to `wash ctl`.

These variables are used for `wash up` but were missing for the related flags in `wash ctl`

2021-01-21 18:28 UTC, jsoverson commented
Re:checks: I was getting that build error today as well but, as I didn't change anything between today's build and the last successful build, I reran it with `cargo build --locked` to rule out dep-related issues. That succeeded so I didn't look into it further.

Not that it fixes a dep issue, but should Cargo.lock be checked in? From what I can find, [tracking the cargo lockfile is recommended for binaries](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html).

2021-01-21 20:08 UTC, brooksmtownsend commented
@jsoverson Looks like using `git` dependencies ended up biting us here, `wasmcloud` upstream updated after you checked out the `main` branch. If you want to fix this, you can modify the following line:
https://github.com/wasmCloud/wash/blob/main/src/up.rs#L416
from this:
```
            let host = HostBuilder::new()
                .with_namespace(CTL_NS)
                .with_rpc_client(nc_rpc)
                .with_control_client(nc_control)
                .with_label("repl_mode", "true")
                .oci_allow_latest()
                .oci_allow_insecure()
                .enable_live_updates()
                .build();
```
to this:
```
            let host = HostBuilder::new()
                .with_namespace(CTL_NS)
                .with_rpc_client(nc_rpc)
                .with_control_client(nc_control)
                .with_label("repl_mode", "true")
                .oci_allow_latest()
                .oci_allow_insecure(vec!["localhost:5000"])
                .enable_live_updates()
                .build();
```

`oci_allow_insecure` now just requires a `vec` of allowed insecure registries. Again, not an issue with how you contributed just showing that #41 is high on our list 🙂 . Once you change that, the build will be fine and we can get this merged in!

2021-01-22 13:51 UTC, brooksmtownsend requested changes
See above comment

2021-01-25 20:03 UTC, brooksmtownsend commented
@jsoverson if you pull in `main`, then my requested change should be completed, once you do that this should be good to go

2021-01-27 21:32 UTC, brooksmtownsend approved these changes

2021-01-27 21:32 UTC, merged