[feat] Add Detached Washboard
wasmCloud/wash-archive pull request #643
Opened 2023-07-05 21:43 UTC by lachieh

## Feature or Problem

## Related Issues

## Release Information

## Consumer Impact

## Testing

Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)

### Acceptance or Integration

### Manual Verification

2023-07-10 23:35 UTC, connorsmith256 commented on package.json
Is this needed at the top-level, or should it be part of `packages/package.json`?

2023-07-10 23:35 UTC, connorsmith256 commented on packages/washboard/package.json
Curious if we need `packages/washboard` instead of just `washboard` as a top-level directory?

2023-07-10 23:35 UTC, connorsmith256 commented on packages/washboard/public/.gitkeep
What goes in this dir?

2023-07-10 23:35 UTC, connorsmith256 commented on packages/washboard/src/assets/.gitkeep
Why is this needed?

2023-07-10 23:35 UTC, connorsmith256 commented on packages/washboard/src/lib/utils.ts
> +export function cn(...inputs: ClassValue[]): string {
Nit: idk what `cn` means. Am I out of touch?

EDIT: classname?

2023-07-11 01:44 UTC, lachieh commented on packages/washboard/src/assets/.gitkeep
🗑️✅

2023-07-11 01:45 UTC, lachieh commented on packages/washboard/public/.gitkeep
nada, 🗑️✅

2023-07-11 01:51 UTC, lachieh commented on packages/washboard/src/lib/utils.ts
> +export function cn(...inputs: ClassValue[]): string {
yah, added ts-doc comment

2023-07-11 01:52 UTC, lachieh commented on packages/washboard/package.json
Was thinking that the `LatticeService` class may make it's way out into it's own npm package also in which case this makes it easy to add multiple npm packages/projects in future. Happy to move, though, if it feels weird.

2023-07-11 01:53 UTC, lachieh commented on package.json
yeah, should be part of subfolder 🗑️✅

2023-07-11 01:55 UTC, lachieh commented on packages/washboard/package.json
I will say that this structure is typical for npm/node monorepos

2023-07-11 02:02 UTC, connorsmith256 submitted a review, later dismissed

2023-07-11 02:02 UTC, connorsmith256 commented on packages/washboard/package.json
Thanks for the explanation 👍

2023-07-11 13:36 UTC, brooksmtownsend requested changes
One request, one nit that will probably never apply

2023-07-11 13:36 UTC, brooksmtownsend commented on src/ui/mod.rs
> +    println!("Hit CTRL-C to stop");
nit: can we send this to stderr with `eprintln!`? That way if people are running in JSON output mode it won't break jq

2023-07-11 13:36 UTC, brooksmtownsend commented on src/main.rs
> +        CliCommand::Ui(ui_cli) => ui::handle_command(ui_cli, output_kind).await,
Make sure to gate this behind the experimental flag, if you mention that in the README

2023-07-11 14:01 UTC, lachieh commented on src/main.rs
> +        CliCommand::Ui(ui_cli) => ui::handle_command(ui_cli, output_kind).await,
broader question, should it be experimental? I could go either way

2023-07-11 14:17 UTC, lachieh commented on src/main.rs
> +        CliCommand::Ui(ui_cli) => ui::handle_command(ui_cli, output_kind).await,
Added it anyway to get it in. Easy enough to remove if necessary.

2023-07-11 14:33 UTC, brooksmtownsend approved these changes, later dismissed

2023-07-11 15:17 UTC, brooksmtownsend commented on build.rs
> +    println!("cargo:rerun-if-changed=./packages/washboard/postcss.config.cjs");
@thomastaylor312 is this special syntax to actually not re-run this build if the static assets stay the same? Want to make sure that we aren't recomputing the npm commands each time you build

2023-07-11 19:03 UTC, connorsmith256 submitted a review, later dismissed

2023-07-12 17:37 UTC, rvolosatovs commented on .github/workflows/nix.yml
> +  WASH_CI: true
`nix` does not have access to any env variables by default, so pretty sure this is not effective

2023-07-12 17:37 UTC, rvolosatovs commented on .github/workflows/release.yml
> +  WASH_CI: true
see above

2023-07-12 17:37 UTC, rvolosatovs commented on build.rs
> +        false if running_in_ci => {
I don't think it's good developer experience to have to set `WASI_CI` to build UI changes.
Why not use something more like `WASH_BUILD_UI` ?

2023-07-12 17:37 UTC, rvolosatovs commented on build.rs
> +                    .output()?,
Why not just let the command write to inherited stdio directly?

2023-07-12 17:37 UTC, rvolosatovs commented on build.rs
> +fn handle_output(
This would be redundant if we just used the defaults above

2023-07-12 17:37 UTC, rvolosatovs commented on build.rs
> +            println!("cargo:warning=Wash UI assets not found. Run `make build-ui` from the root of the repo or the `wash ui` command will not work correctly");
This does not work the way you think it does - you can't just log stuff using `println`. At least this should be using `eprintln`, which will only be printed on failure pretty much

2023-07-12 17:37 UTC, rvolosatovs commented on build.rs
> +    let index_html_path = std::path::Path::new("./packages/washboard/dist/index.html");
This script should rerun each time any of the UI source or the generated assets change using https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorerun-if-changedpath

2023-07-12 17:37 UTC, rvolosatovs commented on build.rs
> +        true => Ok(()),
We should either check the env var or check the existence of the file.
This is confusing, why not just always attempt to build if the env var is set?

2023-07-12 21:35 UTC, connorsmith256 approved these changes

2023-07-12 21:36 UTC, connorsmith256 commented
Merging with failing windows build because it's failing everywhere

2023-07-12 21:36 UTC, merged