feature(up): ensure that the wasmcloud-host can be stopped gracefully
wasmCloud/wash-archive pull request #645
Opened 2023-07-06 05:19 UTC by Iceber

## Feature or Problem

## Related Issues

## Release Information

## Consumer Impact

## Testing

Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)

### Acceptance or Integration

### Manual Verification

2023-07-06 05:55 UTC, Iceber commented on src/up/mod.rs
> +        stop_wasmcloud(wasmcloud_child).await?;
Place the `stop_wasmcloud` outside the `run_wasmcloud_interactive` to explicity stop wasmcloud, and the user can see the spinner output first

2023-07-07 14:02 UTC, brooksmtownsend requested changes
A couple nits, and just one question

2023-07-07 14:02 UTC, brooksmtownsend commented on src/up/mod.rs
> +    // TODO(iceber): the timeout for the SIGTERM cloud be added in the future,
nit: typo in `could`

2023-07-07 14:02 UTC, brooksmtownsend commented on src/up/mod.rs
> +    )?;
Instead of the `unwrap` here, I would prefer an `if let Some(id)` statement to ensure we don't panic, even if it's unlikely the PID is null

2023-07-07 14:02 UTC, brooksmtownsend commented on src/up/mod.rs
> +            // wadm and NATS both exit immediately when sent SIGINT
We'll have to double check this behavior, I _think_ wadm, NATS, and wasmCloud all get terminated when CTRL+c is received 🤔 Were you able to verify that your stop_wasmcloud function sends the SIGTERM and that's what stops wasmCloud?

2023-07-07 17:22 UTC, Iceber commented on src/up/mod.rs
> +            // wadm and NATS both exit immediately when sent SIGINT
I haven't verified it carefully, but I found that wadm and nats automatically terminate after receiving ctrl-c, but wasmcloud doesn't, it needs to call  `kill` or `send a signal`

2023-07-07 17:29 UTC, Iceber commented on src/up/mod.rs
> +            // wadm and NATS both exit immediately when sent SIGINT
So for this comment, it's true that only wamd and nats will be exited

2023-07-07 18:46 UTC, connorsmith256 commented on src/up/mod.rs
> +            // wadm and NATS both exit immediately when sent SIGINT
I believe @brooksmtownsend is right and all three child processes are terminated after a CTRL-C. For wasmCloud this is the relevant line (see the "Wait for the user to send Ctrl+C" message above it):
https://github.com/wasmCloud/wash/blob/87033c94bf4f27b7936b5e1191f929562a23554e/src/up/mod.rs#L645

2023-07-08 02:05 UTC, Iceber commented on src/up/mod.rs
> +            // wadm and NATS both exit immediately when sent SIGINT
> I found that wadm and nats automatically terminate after receiving ctrl-c, but wasmcloud doesn't, it needs to call kill or send a signal

@connorsmith256 Sorry, my reply above may not have explained it well.

Yes, all three processes started by wash up will eventually be terminated, but they are not terminated in the same way.
wadm and nats will be **terminated immediately** after wash up receives the ctrl-c signal, while
wasmcloud is not terminated by the ctrl-c signal, but by calling `wasmcloud.kill()` or by using [`stop_wasmcloud`](https://github.com/wasmCloud/wash/pull/645/files#diff-dcf780801376c219d3b5d7f2f9a5a2745c5ccb124b8c621281e13d3c775ed9f3R650)

I moved `stop_wasmcloud` under `spinner.message("CTRL+c received, stopping wasmCloud, wadm, and NATS...".to_string())` to explicitly stop wasmcloud, because there is a short interval between sending the signal to wasmcloud and waiting for wasmcloud to exit, and it would be nice to print spinner.message before then.

After `stop_wasmcloud` is moved under `spinnner.message`, **only wadm and nats are **immediately stopped** by the ctrl-c signal before this comment**, while wasmcloud is still waiting for the stop_wasmcloud call.
so I changed the comment to `wadm and NATS both exit immediately when sent SIGINT`

2023-07-08 04:10 UTC, Iceber commented on src/up/mod.rs
> +    )?;
updated, thanks

2023-07-10 14:51 UTC, Iceber commented
> On unix, because wasmcloud was not stopped gracefully due to the use of SIGKILL, none of the providers it started were stopped and became orphaned processes

@brooksmtownsend @connorsmith256 i updated the descritpiton of pr. This looks like a serious bug, SIGKILL is a dangerous shutdown signal.

2023-07-10 14:54 UTC, brooksmtownsend commented
> > On unix, because wasmcloud was not stopped gracefully due to the use of SIGKILL, none of the providers it started were stopped and became orphaned processes
> 
> @brooksmtownsend @connorsmith256 i updated the descritpiton of pr. This looks like a serious bug, SIGKILL is a dangerous shutdown signal.

@Iceber I remember when initially creating this feature, I couldn't find a great way to spawn a child process and then intercept the CTRL+c because it's sent immediately down to the children of the foreground. I'm not sure if you know a way to do this, since the mechanics of the SIGKILL getting sent to children too isn't something we can control

2023-07-10 15:41 UTC, Iceber commented
> @Iceber I remember when initially creating this feature, I couldn't find a great way to spawn a child process and then intercept the CTRL+c because it's sent immediately down to the children of the foreground. I'm not sure if you know a way to do this, since the mechanics of the SIGKILL getting sent to children too isn't something we can control

CTRL-c is actually sending a SIGINT signal to the process group/session. So `nats` and `wadm` receive SIGINT signals, whereas `wasmcloud` is created in a new process group, and it doesn't receive SIGINT signals, so if we don't call `wasmcloud.kill` to shut it down, it will become an orphaned process, but `wasmcloud.kill` sends SIGKILL signals, which will make the wasmcloud to lose some of its termination operations. So I chose to use SIGTERM instead of SIGKILL signal, and the provider subprocesses created by wasmcloud should be managed by wasmcloud itself, and it is true that when `wasmcloud-host` receives SIGTERM/SIGINT he will terminate all provider processes.

In my opinion, wash up doesn't need to manage the sub-processes created by wasmcloud, it's managed by wasmcloud, what wash up can do is to send a graceful shutdown signal to wasmcloud.

2023-07-10 16:48 UTC, connorsmith256 commented
@Iceber Ah, thank you for the clarification! I think I understand now. I agree we should send SIGTERM to the wasmcloud host, which will give it time to gracefully shut down, including emitting the `host_stopped` event.

However, there's one tricky part of making this work in practice: the NATS server process will be killed immediately after a CTRL-C, before we gracefully shut down the wasmcloud host with SIGTERM. But since the NATS server will be dead already, the host won't be able to emit the `host_stopped` event.

I haven't thought much about this, but perhaps the solution needs to involve moving the NATS server to a new process group as well, so it's not immediately killed with a CTRL-C. Then we could control the shutdown logic and send a SIGTERM to the host before the NATS server process

2023-07-11 09:27 UTC, Iceber commented
@connorsmith256 I'm not sure if I'm overlooking something.
A wash up starts nats and does not connect to external nats, when the wash up receives a ctrl-c, it kills the nats, and any other connections to the nats will not work, it doesn't seem to matter whether or not the wasmcloud of the terminated wash up sends a successful host_stopped on shutdown, it just needs to do other things, such as recycle its provider subprocess. It just needs to do other things, such as reclaiming its provider subprocesses.

2023-07-11 16:01 UTC, connorsmith256 commented
@Iceber There are two important steps for a wasmCloud host to shut down gracefully:
1) stop provider processes
2) emit a `host_stopped` event

Your refactor improves the current behavior by replacing a SIGKILL with a SIGTERM, which allows the host to perform step 1). However, we kill the local NATS server process before 2)

The second step is important in environments where there are multiple wasmCloud hosts running. E.g. if someone is using wadm to distribute an application across hosts, and pressing CTRL-C causes a host to shut down without emitting the `host_stopped` event, then it will take a couple of minutes for wadm to detect the host has become unavailable and attempt to reschedule the application

That being said, fixing 1) is still an improvement! I'm happy to merge this PR as-is, but I don't think we should close https://github.com/wasmCloud/wasmcloud-otp/issues/643 until we also fix 2) (thank you for filing that issue, by the way)

@brooksmtownsend I suggest we move https://github.com/wasmCloud/wasmcloud-otp/issues/643 back to the wash repo, since fixing 1) and 2) above are wash-specific behavior. If the washboard doesn't expire hosts which haven't emitted heartbeats, that feels like a separate bug. Thoughts?

2023-07-18 01:50 UTC, connorsmith256 commented
@Iceber I think all this needs is a rebase and we can merge

2023-07-18 10:17 UTC, Iceber commented
@connorsmith256 @brooksmtownsend I am sorry, I was working on an important feature for another project the other day and I can now continue working on wasmcloud.

Especially in leaf nats mode, we really should be needing to shut down nats last, and maybe we really need to create a new process group for it.

There is also a signal handling issue, does wash up need to be running in a container, `wash up` doesn't handle SIGTERM signals, it only handles SIGINT.

And when `wasm up` receives SIGTERM/SIGINT instead of CTRL-C, it doesn't shut down nats and wadm.

2023-07-18 16:52 UTC, connorsmith256 approved these changes
As discussed, this doesn't entirely solve the problem, but it is a step in the right direction!

Thank you for your contribution @Iceber 🙌

2023-07-18 16:55 UTC, brooksmtownsend approved these changes

2023-07-18 17:14 UTC, merged