feat: build wasi p1 adapter locally in wash-lib
wasmCloud/wash-archive pull request #656
Opened 2023-07-10 16:14 UTC by vados-cosmonic

## Feature or Problem

Build the [WASI preview1 component adapter](https://github.com/bytecodealliance/wasmtime/tree/main/crates/wasi-preview1-component-adapter) inside `wash`

Note that the adapter is *not* built inside `wash-lib` because it requires the unstable `bindeps` feature. 

It seemed somewhat undesirable to require nightly Rust for the `wash` build when it actually doesn't require it directly, so I instead require that the toolchain is *installed*, and build the adapter in a temporary directory and output the path so `wash` can use it (see sections of `build.rs`).

Of course, nightly Rust as a requirement for everyone who uses `wash-lib` is pretty painful, so the code to do the adapting is going to need to go into `wash` (not `wash-lib`).

All this is gated behind the `wasi-p1-adapter` flag which can be enabled when building `wash`.

## Related Issues

#640 

## Release Information

`next`

## Consumer Impact

Consumers will be able to build the p1 adapter locally

## Testing

Built on platform(s)
- [x] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [x] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)

### Acceptance or Integration

### Manual Verification

Verified locally

2023-07-10 16:29 UTC, rvolosatovs requested changes

2023-07-10 16:29 UTC, rvolosatovs commented on build.rs
> +use std::{
Maybe add a reference to the original at the top of the file?

2023-07-10 16:29 UTC, rvolosatovs commented on build.rs
> +        .args(["+nightly", "version"])
Let's not explicitly depend on rustup here, just remove the `+nightly`

2023-07-10 16:29 UTC, rvolosatovs commented on build.rs
> +        .context("cargo nightly version failed, is cargo nightly installed?")?;
This should not be necessary, instead we should select the right version in `rust-toolchain`

2023-07-10 16:29 UTC, rvolosatovs commented on .github/workflows/rust_ci.yml
> +      - run: rustup toolchain install nightly --profile minimal
This should not be necessary, instead we should just use `rust-toolchain.toml`

2023-07-10 16:31 UTC, rvolosatovs reviewed
The built adapter is never actually used anywhere, so what's the purpose of building it at all?

2023-07-10 16:33 UTC, rvolosatovs requested changes

2023-07-10 16:33 UTC, rvolosatovs commented on build.rs
> +    fs::create_dir_all(&tmp_dir).await?;
Why is all of this required?

2023-07-10 16:33 UTC, rvolosatovs commented on build.rs
> +    if fs::try_exists(&output_wasm_path).await.is_err() {
This check is redundant

2023-07-10 16:35 UTC, vados-cosmonic commented on build.rs
> +use std::{
Sure! 

- [ ] Add reference to testing crates

2023-07-10 16:36 UTC, vados-cosmonic commented on build.rs
> +        .args(["+nightly", "version"])
Sure, I'll remove this if `rustup-toolchain.toml` clears all the other issues as mentioned in the other comments!

2023-07-10 16:37 UTC, vados-cosmonic commented on build.rs
> +        .context("cargo nightly version failed, is cargo nightly installed?")?;
Please see the description of this ticket -- `wash` itself doesn't actually require nightly, so it doesn't seem reasonable to make the whole project nightly via `rust-toolchain`.

2023-07-10 16:38 UTC, vados-cosmonic commented on .github/workflows/rust_ci.yml
> +      - run: rustup toolchain install nightly --profile minimal
The CI build was failing, which is why this was added -- please see also [the comment above](https://github.com/wasmCloud/wash/pull/656#discussion_r1258578139) with regards to `rust-toolchain.toml`

2023-07-10 16:38 UTC, vados-cosmonic commented on build.rs
> +    fs::create_dir_all(&tmp_dir).await?;
Please see the description of this PR

2023-07-10 16:41 UTC, vados-cosmonic commented on build.rs
> +    if fs::try_exists(&output_wasm_path).await.is_err() {
Sure, will remove, and will update the function to output the actual path it writes to.

- [ ] remove check for output wasm
- [ ] update fn to return output wasm path

2023-07-10 16:55 UTC, vados-cosmonic commented
Oh also, to address [this comment](https://github.com/wasmCloud/wash/pull/656#pullrequestreview-1522514579) -- this is a stepping stone on the way to using the adapter in #640

2023-07-10 18:06 UTC, vados-cosmonic commented on build.rs
> +    fs::create_dir_all(&tmp_dir).await?;
There is also a [discussion on the wasmcloud slack now](https://wasmcloud.slack.com/archives/C04RVMJJH17/p1689010717433159), please put feedback there!

2023-07-12 19:51 UTC, connorsmith256 reviewed
Looks like the build is still failing, with the super-helpful `No such file or directory (os error 2)`

2023-07-12 19:51 UTC, connorsmith256 commented on crates/wash-lib/build.rs
> +    let output_wasm_path = build_wasi_preview1_adapter(&tmp_dir, &tmp_dir)
This name is confusing, given the function we're in is `build_wasi_p1_adapter`

2023-07-14 17:58 UTC, vados-cosmonic commented on crates/wash-lib/build.rs
> +    let output_wasm_path = build_wasi_preview1_adapter(&tmp_dir, &tmp_dir)
changed this to match the name!

2023-07-17 14:47 UTC, rvolosatovs requested changes

2023-07-17 14:47 UTC, rvolosatovs commented on .gitmodules
> +	url = https://github.com/rvolosatovs/wasmtime
I thought we agreed on using a filtered subtree for this?

2023-07-17 14:47 UTC, rvolosatovs commented on docs/DEVELOPMENT.md
> +git submodule update --init # intiialize the submodules inside wasmtime
```suggestion
git submodule update --init # intialize the submodules inside wasmtime
```

2023-07-17 14:47 UTC, rvolosatovs commented on Cargo.toml
>  [dev-dependencies]
I think that dependency updates are out-of-scope of this PR and belong in a separate one

2023-07-17 14:47 UTC, rvolosatovs commented on README.md
> -
How is this change relevant to the PR?

2023-07-17 14:47 UTC, rvolosatovs commented on docs/DEVELOPMENT.md
> +Due to the use of the as-of-yet unstable [`bindeps` feature][bindeps], `wash` also requires [nightly rust][rust-nightly] to
Does this really still apply? I do not see bindeps being used

2023-07-17 14:47 UTC, rvolosatovs commented on flake.nix
> +          "vendor/wasm/wasi_snapshot_preview1.command.wasm"
I don't understand why these are in-tree, but excluded from the build

2023-07-17 14:47 UTC, rvolosatovs commented on crates/wash-lib/Cargo.toml
> +wasi-p1-adapter = []
What does this feature actually do? Isn't it completely redundant?

2023-07-17 14:49 UTC, rvolosatovs commented
I really do not think we should be committing compiled binaries into the tree

2023-07-17 15:57 UTC, vados-cosmonic commented
Closing in favor of https://github.com/wasmCloud/wash/pull/663 -- going to download the binary at runtime and use from `wash_lib`

2023-07-17 15:57 UTC, closed without merging