feat: support adapting p2 components
wasmCloud/wash-archive pull request #663
Opened 2023-07-14 17:20 UTC by vados-cosmonic

## Feature or Problem

## Related Issues

## Release Information

## Consumer Impact

## Testing

Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)

### Acceptance or Integration

### Manual Verification

2023-07-18 18:16 UTC, rvolosatovs requested changes
Since https://github.com/wasmCloud/wasmCloud/pull/378 https://github.com/wasmCloud/wasmcloud now contains `wasmcloud_component_adapters` crate, which exports the adapters as const byte slices, meaning that there is no need to build the adapters in this repository and also no need to check-in the Wasm files. Could you add (git) dependency on that crate please and use the consts instead?

2023-07-18 18:26 UTC, rvolosatovs commented
I have filed https://github.com/wasmCloud/wash/pull/670, which contains all the necessary Nix changes to make this work.

2023-07-19 17:16 UTC, rvolosatovs commented on Cargo.toml
> +wasmcloud-component-adapters = { git = "https://github.com/wasmCloud/wasmCloud", rev = "a339ede" }
Do we really need the rev here?

2023-07-19 17:16 UTC, rvolosatovs commented on src/build.rs
> +) -> Result<Option<Vec<u8>>> {
When would this ever return a `Ok(None)`? What's the purpose of the `Option` here?

2023-07-19 17:16 UTC, rvolosatovs commented on crates/wash-lib/src/build.rs
> +    adapter_bytes: &Option<impl AsRef<[u8]>>,
```suggestion
    adapter_bytes: impl AsRef<[u8]>,
```

2023-07-19 17:17 UTC, rvolosatovs commented on src/build.rs
> +            wasmcloud_component_adapters::WASI_PREVIEW1_REACTOR_COMPONENT_ADAPTER.into(),
We should make a distinction here whether the component is a "reactor" or "command". I suppose it's fine to leave it out for now, but there should be an issue filed about that

2023-07-19 17:19 UTC, vados-cosmonic commented on Cargo.toml
> +wasmcloud-component-adapters = { git = "https://github.com/wasmCloud/wasmCloud", rev = "a339ede" }
any reason we shouldn't be explicit on which version we're pulling in?

2023-07-19 17:20 UTC, vados-cosmonic commented on crates/wash-lib/src/build.rs
> +    adapter_bytes: &Option<impl AsRef<[u8]>>,
Sometimes, the adapter bytes are not needed

2023-07-19 17:20 UTC, vados-cosmonic commented on src/build.rs
> +            wasmcloud_component_adapters::WASI_PREVIEW1_REACTOR_COMPONENT_ADAPTER.into(),
We don't have anything that uses command

2023-07-19 17:21 UTC, rvolosatovs commented on Cargo.toml
> +wasmcloud-component-adapters = { git = "https://github.com/wasmCloud/wasmCloud", rev = "a339ede" }
Having the `rev` here means we cannot simply `cargo update` anymore and would have to manually check the `rev` and copy-paste it here, which complicates and slows down maintenance

2023-07-19 17:21 UTC, vados-cosmonic commented on src/build.rs
> +) -> Result<Option<Vec<u8>>> {
Ah was for easy use where this function is used, I can remove the option here and add it @ the use site.

- [ ] Remove `Option` from `get_wasi_preivew2_adapter_bytes`

2023-07-19 17:34 UTC, vados-cosmonic commented on src/build.rs
> +) -> Result<Option<Vec<u8>>> {
Looking at this more -- what I'm missing is the `None` case (which represents all the other non-component builds) -- so I'll add that instead

2023-07-19 17:36 UTC, vados-cosmonic commented on src/build.rs
> +) -> Result<Option<Vec<u8>>> {
addressed -- missing case (where you have `None` is there now

2023-07-19 18:09 UTC, rvolosatovs commented on Cargo.toml
> +wasmcloud-component-adapters = { git = "https://github.com/wasmCloud/wasmCloud", rev = "a339ede" }
@vados-cosmonic could you switch to https://github.com/rvolosatovs/wasmcloud-component-adapters (at least temporarily?)
We should move that repo to `wasmCloud` org, but I did not have permissions to do that.

The issue here is that in `cargo vendor` use cases, build can only refer to files within the crate and `flake.lock` in this case is outside of it. Seems that a separate repo is the only reasonable way to handle this case.

2023-07-19 18:22 UTC, vados-cosmonic commented on Cargo.toml
> +wasmcloud-component-adapters = { git = "https://github.com/wasmCloud/wasmCloud", rev = "a339ede" }
Yeah I think we should be able to make that other repo really quick, so I'm fine waiting for that to happen then switching

2023-07-19 18:38 UTC, brooksmtownsend commented on Cargo.toml
> +wasmcloud-component-adapters = { git = "https://github.com/wasmCloud/wasmCloud", rev = "a339ede" }
@rvolosatovs can you give me ownership over your repository? I can initiate the move then

2023-07-20 00:59 UTC, connorsmith256 approved these changes, later dismissed
> yet do not necessarily want the adapters to be included in wash-lib

Can you help me understand reasons for/against including the adapters in wash-lib?

2023-07-20 00:59 UTC, connorsmith256 commented on crates/wash-lib/src/build.rs
> +    adapter_bytes: &Option<impl AsRef<[u8]>>,
Since the adapter bytes are retrieved based off the `config`, does this need to be a separate arg, or can we have `build_actor` be responsible for calling `get_wasi_preview2_adapter_bytes`? That would simplify the call chain

I assume wash-lib could contain the bytes(?)

2023-07-20 02:52 UTC, vados-cosmonic commented on crates/wash-lib/src/build.rs
> +    adapter_bytes: &Option<impl AsRef<[u8]>>,
This was brought up during a previous review which I agree with -- if we can we should avoid `wash-lib` holding the lib, because then every downstream will need to pull in the blobs (which is large, for a regular lib), the PR was written with the intent to avoid pulling in the lib (which required those contortions).

For example `tokio`weighs in at 694kb, and wash lib currently weighs in at 85kb. I'm not sure it's something people will care about that much but given that the adapters are ~100+kb each, that would be a significant increase

2023-07-20 19:58 UTC, connorsmith256 commented on Cargo.toml
> +wasmcloud-test-util = { git = "https://github.com/vados-cosmonic/wasmcloud-test.git", branch = "refactor/remove-smithy-bindgen-dep" }
btw, v0.10 is available now

2023-07-21 00:03 UTC, vados-cosmonic commented on Cargo.toml
> +wasmcloud-test-util = { git = "https://github.com/vados-cosmonic/wasmcloud-test.git", branch = "refactor/remove-smithy-bindgen-dep" }
Oh thanks for the reminder, will use that

2023-07-21 00:03 UTC, vados-cosmonic commented on crates/wash-lib/src/build.rs
> +    adapter_bytes: &Option<impl AsRef<[u8]>>,
after some discussion, the added weight to `wash-lib` doesn't seem to be a huge deal so will refactor to add that

2023-07-21 00:51 UTC, connorsmith256 submitted a review, later dismissed

2023-07-21 02:45 UTC, connorsmith256 approved these changes

2023-07-21 02:58 UTC, merged