fix: docker build and push flow
wasmCloud/wash-archive pull request #727
Opened 2023-08-24 18:09 UTC by vados-cosmonic

## Feature or Problem

Based on the work in [this PR](https://github.com/wasmCloud/wash/pull/720), this PR attempts to update the `docker` build and release process to build for both arm64 and amd64. 

## Related Issues

## Release Information

## Consumer Impact

## Testing

Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)

### Acceptance or Integration

### Manual Verification

2023-09-13 20:19 UTC, brooksmtownsend requested changes
By and large this looks like the correct implementation / transfer of wadm things! Just left a few comments to make this a true multiplatform image and maybe a conditional compile or two we could remove

2023-09-13 20:19 UTC, brooksmtownsend commented on .github/workflows/docker_check.yml
> +          platforms: ${{ matrix.arch.docker_platform }}
Am I missing this variable somewhere?

2023-09-13 20:19 UTC, brooksmtownsend commented on .github/workflows/docker_check.yml
> +            targetPath: "target/aarch64-apple-darwin/release/"
Do we need to build these ones for the docker check? I know windows containers exist, but I wasn't thinking we had to add that quite yet (or as a part of this PR)

2023-09-13 20:19 UTC, brooksmtownsend commented on .github/workflows/release_docker.yml
> +            targetPath: "target/aarch64-apple-darwin/release/"
Same comment re: target building

2023-09-13 20:19 UTC, brooksmtownsend commented on Dockerfile
> +USER $USERNAME
I think building the image in this way will _only_ build it for a single docker architecture, where the wadm implementation conditionally copies either the arm64/amd64 binary based on the `uname -a` in the container, right?

2023-09-13 20:19 UTC, brooksmtownsend commented on .github/workflows/release_docker.yml
> +          context: .
I think here we should pass two binaries, one for amd64 and one for arm64 so the container can properly buildx build a multi-platform image

2023-09-14 10:09 UTC, vados-cosmonic commented on .github/workflows/release_docker.yml
> +            targetPath: "target/aarch64-apple-darwin/release/"
Sure I can remove these other targets -- cut it down to just the linux builds.

- [ ] remove mac, windows builds

2023-09-14 10:09 UTC, vados-cosmonic commented on .github/workflows/docker_check.yml
> +            targetPath: "target/aarch64-apple-darwin/release/"
No I can certainly remove these -- similar to the `release_docker.yml`

2023-09-14 10:10 UTC, vados-cosmonic commented on Dockerfile
> +USER $USERNAME
Yep, but then we are using this `Dockerfile` across a matrix, so both images will get built, tagged and pushed (just separately).

2023-09-14 10:20 UTC, vados-cosmonic commented on .github/workflows/release_docker.yml
> +          context: .
yeah the attempt here was to enable building across the matrix so we could support containers on the other platforms (you can do this with the `docker manifest` command)

Since we're removing the other platforms for now I can revert this to the same way WADM does and we can revisit when adding support for the other platforms.

2023-09-14 10:21 UTC, vados-cosmonic commented on Dockerfile
> +USER $USERNAME
yeah that's how it used to work -- but I realized that only worked for linux based platforms so wanted to build with the matrix and combine later -- but given that we're not going to support the other platforms yet, will revert this!

2023-09-14 10:25 UTC, vados-cosmonic commented on .github/workflows/docker_check.yml
> +          platforms: ${{ matrix.arch.docker_platform }}
Ah this should be removed

- [ ] remove unused `matrix.arch.docker_platform`

2023-09-14 15:51 UTC, brooksmtownsend submitted a review, later dismissed
Awesome stuff @vados-cosmonic ! Sorry, I introduced a merge conflict by merging #804 but if you can rebase then it's good to go 😄

2023-09-14 16:35 UTC, vados-cosmonic commented
Done @brooksmtownsend , thanks for the quick review!

2023-09-14 16:37 UTC, brooksmtownsend approved these changes

2023-09-14 16:55 UTC, merged