chore: improving contributing docs
wasmCloud/wash-archive pull request #735
Opened 2023-08-29 19:21 UTC by yordis

2023-08-29 19:25 UTC, lachieh requested changes

2023-08-29 19:25 UTC, lachieh commented on CONTRIBUTING.md
> +If you have any feature suggestions, find any bugs, or otherwise have a question, please submit an issue[here][0].
```suggestion
If you have any feature suggestions, find any bugs, or otherwise have a question, please submit an issue [here][0].
```

2023-08-29 19:25 UTC, lachieh commented on CONTRIBUTING.md
> +- [Contributing to Washboard Front End](./packages/washboard/CONTRIBUTING.md)
```suggestion
- [Contributing to Washboard UI](./packages/washboard/CONTRIBUTING.md)
```

2023-08-29 19:25 UTC, lachieh commented on packages/washboard/CONTRIBUTING.md
> +
Would be good to add instructions on starting the UI in dev mode also

2023-08-29 19:39 UTC, yordis commented on packages/washboard/CONTRIBUTING.md
> +
check latest

2023-08-29 20:02 UTC, yordis commented
I can not replicate the How-To Contribute Code 😭

2023-08-30 13:05 UTC, lachieh approved these changes

2023-08-30 14:06 UTC, brooksmtownsend approved these changes

2023-08-30 14:06 UTC, merged