TINYGO + WASI + `wash build` = YES PLEASE
wasmCloud/wash-archive pull request #758
Opened 2023-09-01 14:20 UTC by jordan-rash

## Feature or Problem
Trying to solve #512 

## Release Information
This adds the `wasm_target` value to the [tinygo] `wasmcloud.toml` section.  Defaults to `wasm` but excepts wasm or wasi

## Consumer Impact

## Testing
I would definitely not code review this and set to auto-merge...i am highly skilled in Rust and it would be a waste of everyones time................

Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

2023-09-01 14:22 UTC, jordan-rash commented
Disclaimer: if you ask my _why_ I did something, the answer is 99% chance, "I don't know"

2023-09-01 14:44 UTC, ricochet commented on crates/wash-lib/src/parser/mod.rs
> +    #[serde(alias = "wasi", alias = "wasi")]
I thought it was going to be wasip1 everyhwere?

`GOOS=wasip1`

https://github.com/golang/go/issues/58141

2023-09-01 15:53 UTC, jordan-rash commented on crates/wash-lib/src/parser/mod.rs
> +    #[serde(alias = "wasi", alias = "wasi")]
even in tinygo???  If thats true, I missed the update...ill go check

2023-09-01 16:04 UTC, jordan-rash commented on crates/wash-lib/src/parser/mod.rs
> +    #[serde(alias = "wasi", alias = "wasi")]
So, I dont actually know what the difference between these two files would be........
 
```
└─❯ GOARCH=wasm GOOS=wasip1 tinygo build .

└─❯ md5 globby.wasm                       
MD5 (globby.wasm) = a47ea736e647ca485fbacba826dd6211

└─❯ tinygo build -target=wasi .           

└─❯ md5 globby.wasm            
MD5 (globby.wasm) = dc87470c740aa3735dd855c19102a8be
```

2023-09-01 16:04 UTC, ricochet commented on crates/wash-lib/src/parser/mod.rs
> +    #[serde(alias = "wasi", alias = "wasi")]
Looks like it: https://github.com/tinygo-org/tinygo/issues/3685

Do sanity check it before updating

2023-09-01 16:21 UTC, jordan-rash commented on crates/wash-lib/src/parser/mod.rs
> +    #[serde(alias = "wasi", alias = "wasi")]
> I imagine users will probably stubble upon those differences and be confused about why certain functionalities work in one WASI but not the other. I expect we would get questions like "when should we use -target=wasi vs GOOS=wasip1?" and recording those answers will likely reduce the maintenance load.

So, they are supporting both right now, BUT after reading the issues, I can not tell which one is the recommended one.  It seems to me that the target option is the "safest" right now as, from what i gather in those issues, the GOOS solution might not be completely supported.  I think, for the sake of making this available, we go with the target solution now until I can test more, as I know the target solution works.  🤷🏼

2023-09-01 19:07 UTC, ricochet approved these changes, later dismissed

2023-09-01 19:09 UTC, ricochet commented on crates/wash-lib/src/parser/mod.rs
> +    #[serde(alias = "wasi", alias = "wasi")]
With only TinyGo working with bindings right now, that's ok with me but we should definitely revisit so that this works with std golang.

2023-09-01 19:11 UTC, jordan-rash commented on crates/wash-lib/src/parser/mod.rs
> +    #[serde(alias = "wasi", alias = "wasi")]
I agree. I'll keep this on the front of my radar and test all the things in the very near future

2023-09-01 21:01 UTC, brooksmtownsend commented
@jordan-rash looks like it's correctly failing a test, assuming that the target is always going to be `None`, once that's fixed this should be good to go!

2023-09-01 21:01 UTC, brooksmtownsend submitted a review, later dismissed

2023-09-01 21:08 UTC, jordan-rash commented
> @jordan-rash looks like it's correctly failing a test, assuming that the target is always going to be `None`, once that's fixed this should be good to go!

Ha, I'll try and figure that out tonight

2023-09-13 19:57 UTC, brooksmtownsend commented
@jordan-rash bump! 😄

2023-10-04 18:17 UTC, vados-cosmonic commented
Hey @ricochet just checking that you're fine using this by thurs without it merging (IIRC we weren't intending to cut a new release of `wash` for this, right?)

2023-10-05 06:23 UTC, vados-cosmonic commented
Hey @connorsmith256 not sure why this branch is still showing conflicts (I still can't see what they actually are) but it works great on the [PR to wasmcon-workshop](https://github.com/cosmonic/wasmcon-workshop/pull/14).

Will everything survive another rebase? Tune in to the next commit to find out.

2023-10-05 16:57 UTC, connorsmith256 commented
Thanks @vados-cosmonic, I introduced another merge conflict with a different PR

2023-10-05 18:00 UTC, thomastaylor312 requested changes

2023-10-05 18:00 UTC, thomastaylor312 commented on crates/wash-lib/src/parser/mod.rs
> +    /// The WIT world that is implemented by the componet
Spelling: component (blocking as this is crate level docs)

2023-10-05 18:00 UTC, thomastaylor312 commented on crates/wash-lib/tests/parser/main.rs
> +            wit_world: None,
We should be adding a wit world to one of the parser tests just for sanity sake

2023-10-05 18:16 UTC, thomastaylor312 approved these changes, later dismissed

2023-10-05 18:38 UTC, thomastaylor312 approved these changes

2023-10-05 18:38 UTC, merged