Rust host default
wasmCloud/wash-archive pull request #759
Opened 2023-09-01 16:57 UTC by ricochet

## Feature or Problem

## Related Issues

## Release Information

## Consumer Impact

## Testing

Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)

### Acceptance or Integration

### Manual Verification

2023-09-01 17:01 UTC, connorsmith256 requested changes
Real close 🙏

2023-09-01 17:01 UTC, connorsmith256 commented on crates/wash-lib/src/start/mod.rs
> +    // }
We can't remove this logic since we also depend on it for starting the NATS server. Instead, let's remove the `wait_for_server` call specifically for the washboard

2023-09-01 17:01 UTC, connorsmith256 commented on crates/wash-lib/src/start/wasmcloud.rs
> +        .replace("windows", "windows-gnu");
Consider: should we use `std::env::consts::OS` here?

2023-09-01 17:01 UTC, connorsmith256 commented on crates/wash-lib/src/start/wasmcloud.rs
> +        ensure_wasmcloud_for_os_arch_pair("macos", "aarch64", "v0.78.0-rc1", &download_dir)
Nit: use const from above?

2023-09-01 17:01 UTC, connorsmith256 commented on src/up/config.rs
>          host_config.insert(
I can't comment on the right line, but `WASMCLOUD_STRUCTURED_LOG_LEVEL` needs to be `WASMCLOUD_LOG_LEVEL` now

2023-09-01 18:44 UTC, ricochet commented on src/up/config.rs
>          host_config.insert(
The env value was already set to `WASMCLOUD_LOG_LEVEL` but I renamed our const var name to match.

2023-09-01 19:50 UTC, rvolosatovs commented
Looks like tests are still asserting the old version

2023-09-02 01:41 UTC, connorsmith256 submitted a review, later dismissed

2023-09-02 04:13 UTC, connorsmith256 submitted a review, later dismissed

2023-09-02 05:32 UTC, connorsmith256 approved these changes

2023-09-02 05:35 UTC, merged