Drain
wasmCloud/wash-archive pull request #78
Opened 2021-02-05 18:17 UTC by tiptop96

If anyone could give suggestions for the doc comments that would be greatly appreciated. 🥇

2021-02-08 18:46 UTC, brooksmtownsend requested changes
One suggestion, and I threw in what I thought appropriate doc comments would be!

2021-02-08 18:46 UTC, brooksmtownsend commented on src/drain.rs
> +// Hack to get around the fact that we can't have a global 'output' arg.
We should try and leave out `hack` from our code, maybe something like
```
Propagates output selection from CLI to all commands
```

2021-02-08 18:46 UTC, brooksmtownsend commented on src/main.rs
> +    /// TODO
"Manage contents of local wasmCloud cache"

2021-02-08 18:46 UTC, brooksmtownsend commented on src/up.rs
> +    // TODO
"Manage contents of local wasmCloud cache"

2021-02-08 18:46 UTC, brooksmtownsend commented on src/drain.rs
> +    /// TODO
Remove all cached files created by wasmCloud

2021-02-08 18:46 UTC, brooksmtownsend commented on src/drain.rs
> +    /// TODO
Remove cached files downloaded from OCI registries by wasmCloud

2021-02-08 18:46 UTC, brooksmtownsend commented on src/drain.rs
> +    /// TODO
Remove cached binaries extracted from provider archives

2021-02-09 17:32 UTC, tiptop96 commented on src/drain.rs
> +// Hack to get around the fact that we can't have a global 'output' arg.
Yeah, that's a good point 👍

2021-02-12 15:20 UTC, brooksmtownsend approved these changes
Looks great, and works great 😄

2021-02-12 15:20 UTC, brooksmtownsend commented on src/up.rs
> +}
Love how clean the functions are getting now 😄

2021-02-12 15:20 UTC, merged