wash UX improvements, writing up a README
wasmCloud/wash-archive pull request #80
Opened 2021-02-05 20:22 UTC by brooksmtownsend

Fixes #73 
Fixes #71 
Fixes #77 
Fixes #79 

Main feedback I'm looking for here is README 😄 
cc @tiptop96, would love your feedback here!

Since the three UX issues were quick fixes, I thought I'd combine them under a "UX" improvement PR. Also included is a proper README that will better introduce readers to the project. After this PR is merged, I plan to create an issue to "expand the README", as it still doesn't have links to documentation, examples, or installation instructions outside of `cargo`.

Looking for any code feedback, but the biggest change is reducing the timeout for `ctl` commands to 1 second. This was plenty of time to receive acknowledgments from the control interface in my testing, including when cache is cleaned, and it made the experience much smoother without waiting extra time.

@billyoung I changed a few build files to rename `wascc` -> `wasmcloud`, will you make sure I didn't break anything on accident that's tied to packagecloud?

2021-02-05 20:57 UTC, tiptop96 commented
I will read it through more thoroughly and let you know what I think once I'm at my desk. 😊

Right of the bat I notice that the version in `Cargo.toml` has been bumped to `0.1.18` while the install instructions in the docs have only been bumped to `0.1.17`.

2021-02-08 07:23 UTC, tiptop96 commented
This all looks awesome, really starting to look more welcoming. 🔥 

My idea is that the two main purposes of the readme is to attract users and to welcome contributions, to me a big part of that is "ease of access" (because eveyone is lazy (or is it just me?)). So how quickly are users able to get up and running and how easy is it for the community to get engaged.

That said I think that it might be a good idea to write a sentence or two on the `/tools` directory, and possibly another few on starting **one** of the examples? This would allow the user to get thrown into the experience before going of to read the full docs. Basically I'm thinking this part: https://github.com/wasmCloud/wash/blob/ae2f25617fd75d24981a1b8158f70385583a1b39/tools/kvcounter-example.sh#L49-L53
We could mention the script as a whole. However I also think it is beneficial to walk the user through these commands. 

Maybe this would fall under the "expand the README" issue, but I think we could score some cheap point by doing it early and build more on it later!

I just love the linked badge to the `good first issues` this gives a suuuuper welcoming impression to me and makes it abundantly clear that we want to build together.

2021-02-08 15:47 UTC, autodidaddict requested changes

2021-02-08 15:47 UTC, autodidaddict commented on README.md
> +![Good first issues](https://img.shields.io/github/issues/wasmcloud/wash/good%20first%20issue?label=good%20first%20issues)
:+1: I like this a lot.

2021-02-08 15:47 UTC, autodidaddict commented on README.md
> +cargo install --git https://github.com/wasmcloud/wash --tag v0.1.17
this should be .18 if it's supposed to match `Cargo.toml`

2021-02-08 15:47 UTC, autodidaddict commented on README.md
> +If you have any feature suggestions, find any bugs, or otherwise have a question, please open up an issue using Github. Forking & submitting Pull Requests are welcome, and the issues marked as "good
might be nice to have some inline links here to the "new issue" link as well as the link to the good first issue list.

2021-02-08 18:55 UTC, merged