Added par support to wash-lib
wasmCloud/wash-archive pull request #844
Opened 2023-10-02 18:12 UTC by aish-where-ya

## Feature or Problem
Feat: Move `wash par` to `wash-lib`

## Release Information
next

## Consumer Impact
Internal code refactoring.
No impact to existing functionality

## Testing
unit and manual tests

Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)
NA

### Acceptance or Integration
NA

### Manual Verification
manually verified

2023-10-02 20:15 UTC, brooksmtownsend requested changes
One nit, one comment that may not be applicable anymore, but _mostly_ ergonomic changes that feel like they would make the functions here a whole lot simpler if we pushed a little responsibility on the CLI-side. Essentially, I think finding and loading keypairs and files should be the responsibility of the CLI, and the library can just properly take that information and turn it into the appropriate `ProviderArchive` structs that the CLI can then write out

2023-10-02 20:15 UTC, brooksmtownsend commented on crates/wash-lib/src/cli/par.rs
> +    ParCreateArgs {
Since this is in the library I like the idea of calling this something more human-parseable
```suggestion
#[allow(clippy::too_many_arguments)]
pub async fn create_provider_archive(
    ParCreateArgs {
```

2023-10-02 20:15 UTC, brooksmtownsend commented on crates/wash-lib/src/cli/par.rs
> +    pub name: String,
In the future I think we could consider taking these fields out and accepting a Claims struct with provider information in it and then archive options... but there's just so many options for this command I'm fine with the way this is now 👍🏻

2023-10-02 20:15 UTC, brooksmtownsend commented on crates/wash-lib/src/cli/par.rs
> +    f.read_to_end(&mut lib)?;
Instead of opening the file here, let's have the user supply the binary as a `&[u8]` so the CLI can deal with opening the files and the library can just deal with the bytes themself

2023-10-02 20:15 UTC, brooksmtownsend commented on crates/wash-lib/src/cli/par.rs
> +    )?;
Same comment here re: let's just take the issuer/subject as function arguments and let the CLI load the key

2023-10-02 20:15 UTC, brooksmtownsend commented on crates/wash-lib/src/cli/par.rs
> +    )?;
If making this refactor lets you get rid of more arguments, then that's great too!

2023-10-02 20:15 UTC, brooksmtownsend commented on crates/wash-lib/src/cli/par.rs
> +    Ok(outfile)
Instead of writing to the file directly, I think it would be nice to simply return the `ProviderArchive` struct and let the CLI user (in our case, wash) write the provider archive out to a file

2023-10-02 20:15 UTC, brooksmtownsend commented on crates/wash-lib/src/cli/par.rs
> +    };
If you can refactor this function to return the ProviderArchive struct, then you shouldn't need destination or outfile anymore (wash itself can handle those)

2023-10-02 20:15 UTC, brooksmtownsend commented on crates/wash-lib/src/cli/par.rs
> +        .map_err(convert_error)?;
I think this function would be great accepting the mutable provider archive instead of the archive file

2023-10-02 20:15 UTC, brooksmtownsend commented on crates/wash-lib/src/cli/par.rs
> +    )?;
Same comment re: accepting issuer / subject as arguments

2023-10-02 20:15 UTC, brooksmtownsend commented on crates/wash-lib/src/cli/par.rs
> +
If we accept this binary as a `&[u8]` as well, we can simply insert it into the provider archive and then finish

2023-10-02 20:17 UTC, brooksmtownsend commented on crates/wash-lib/src/cli/par.rs
> +pub async fn handle_par_insert(
With the refactors we can rename this too
```suggestion
pub async fn insert_provider_binary(
```

2023-10-03 15:22 UTC, aish-where-ya commented
I think I managed to address all the review comments here. Pulling stuff out from the library into the CLI definitely helped in reducing some of the function arguments and also removing the function argument struct for the `insert_provider_binary`, thus reducing a lot of clutter.

2023-10-03 15:25 UTC, brooksmtownsend reviewed
Looks really clean 👍🏻 One tiny request to rename function but looks good to me

2023-10-03 15:25 UTC, brooksmtownsend commented on crates/wash-lib/src/cli/par.rs
> +pub async fn insert_provider_archive(
I think this should be named `insert_provider_binary` to be specific

2023-10-03 15:26 UTC, aish-where-ya commented on crates/wash-lib/src/cli/par.rs
> +pub async fn insert_provider_archive(
oopsies

2023-10-03 15:29 UTC, aish-where-ya commented on crates/wash-lib/src/cli/par.rs
> +pub async fn insert_provider_archive(
done

2023-10-03 15:51 UTC, brooksmtownsend approved these changes

2023-10-03 15:54 UTC, merged