refactor: embed component metadata
wasmCloud/wash-archive pull request #848
Opened 2023-10-03 14:46 UTC by vados-cosmonic

## Feature or Problem

This refactors the existing branch implementing Go WASI p2 components with code to embed component metadata.

## Related Issues

https://github.com/wasmCloud/wash/issues/512

## Release Information

## Consumer Impact

Consumers will be able to build WASI preview2 components from Go with `wash build`

## Testing

Built on platform(s)
- [x] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [x] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)

### Acceptance or Integration

### Manual Verification

Verified manually locally w/ the [wasmcon golang codebase](https://github.com/cosmonic/wasmcon-workshop/tree/main/hello-cosmo-go)

2023-10-03 14:50 UTC, ricochet commented on crates/wash-lib/src/build.rs
> -        || actor_config.wasm_target == WasmTarget::TinyGoWasiPreview1
So essentially if it has not been configured for Preview2 we do not adapt. This avoids the situation @jordan-rash pointed out where you need to target wasi to build wasm-only (no js glue) tiny-go modules.

2023-10-03 14:54 UTC, ricochet commented on crates/wash-lib/src/build.rs
> +/// Embed the WIT inside a given WASM binary, in-place.
OK this is the nittiest of nits:
https://www.w3.org/TR/wasm-core/intro/introduction.html#wasm

A contraction of “WebAssembly”, not an acronym, hence not using all-caps.

2023-10-03 14:55 UTC, vados-cosmonic commented on crates/wash-lib/src/build.rs
> -        || actor_config.wasm_target == WasmTarget::TinyGoWasiPreview1
Yup, that's absolutely right -- so right now, while we embed component metadata whether you target p1 or p2, we only *adapt* if you target p2 (to take you from p1 to p2).

The `wasmcloud.toml` in the wasmcon demo when modified looks like this:

```
name = "hello-cosmo-go"
language = "tinygo"
type = "actor"
version = "0.1.0"

[actor]
claims = ["wasmcloud:httpserver", "wasmcloud:keyvalue", "wasmcloud:builtin:logging"]
wasm_target = "wasm32-wasi-preview2"
wit_world = "hello-cosmo"
```

2023-10-03 15:03 UTC, ricochet approved these changes

2023-10-03 15:03 UTC, vados-cosmonic commented on crates/wash-lib/src/build.rs
> +/// Embed the WIT inside a given WASM binary, in-place.
Absolutely will fix, thank you, thanks for spotting this

2023-10-03 21:55 UTC, connorsmith256 requested changes

2023-10-03 21:55 UTC, connorsmith256 commented on crates/wash-lib/src/build.rs
> +    log::info!("successfully loaded WIT @ [{}]", wit_dir.display());
Nit: debug level? I don't think users need to see this every time they `wash build`

(Same with the other logs in this function)

2023-10-04 02:12 UTC, vados-cosmonic commented on crates/wash-lib/src/build.rs
> +    log::info!("successfully loaded WIT @ [{}]", wit_dir.display());
Ah so the default level is *above* info -- it's error. Also, I think info is the right level for these messages -- they don't touch on the really deep "how", and they mostly say when something happened successfully/happy path. 

In my mind debug messages generally cover the before, during and end of some operation (so we can debug) where as informational stuff just lets you know general outcomes from time to time.

2023-10-04 02:20 UTC, connorsmith256 commented on crates/wash-lib/src/build.rs
> +    log::info!("successfully loaded WIT @ [{}]", wit_dir.display());
I don't think I realized until this moment that info wasn't the default level 😮 my bad!

2023-10-04 02:23 UTC, merged