WIP [FEAT] Update wash to use max_concurrent control interface
wasmCloud/wash-archive pull request #862
Opened 2023-10-05 15:45 UTC by brooksmtownsend

## Feature or Problem
This PR is updating `wash` to use the latest control interface that supports max scale instead of counts.

## Related Issues
RFC https://github.com/wasmCloud/wasmCloud/issues/696

## Release Information
v0.21.0

## Consumer Impact
As designed, this version of `wash` will remain completely compatible with older versions of the host and work for newer released versions.

## Testing

Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)

### Acceptance or Integration

### Manual Verification

2023-10-06 18:14 UTC, mattwilkinsonn requested changes
Are you able to add integration tests for the new commands?

2023-10-06 20:44 UTC, brooksmtownsend commented
> Are you able to add integration tests for the new commands?

Good call, they aren't new commands but we should definitely have an integration test for it at least basic. I've tested with a few manual cases so I'll just turn that into an integration test :)

2023-10-06 21:21 UTC, connorsmith256 reviewed
Looks great, just a couple nits, and 👍 to updating tests

2023-10-06 21:21 UTC, connorsmith256 commented on crates/wash-lib/src/actor.rs
>          .start_actor(host_id, actor_ref, count, None)
Can we update this to use scale under the hood?

2023-10-06 21:21 UTC, connorsmith256 commented on crates/wash-lib/src/actor.rs
> +        .stop_actor(host_id, actor_id, annotations)
Can we also update this to use scale under the hood?

2023-10-06 21:21 UTC, connorsmith256 commented on src/up/config.rs
> +pub(crate) const WASMCLOUD_HOST_VERSION: &str = "v0.78.0";
Should we be hesitant about bumping to 0.79.0-rc3?

2023-10-06 21:25 UTC, brooksmtownsend commented on crates/wash-lib/src/actor.rs
> +        .stop_actor(host_id, actor_id, annotations)
Oh yes, this was leftover from before scale Some(0) == stop. Will do

2023-10-06 21:26 UTC, brooksmtownsend commented on src/up/config.rs
> +pub(crate) const WASMCLOUD_HOST_VERSION: &str = "v0.78.0";
Don't believe so, but I wanted to first ensure all of this worked for the current version of the host and then go from there to 0.79

2023-10-10 17:30 UTC, brooksmtownsend commented on crates/wash-lib/src/actor.rs
>          .start_actor(host_id, actor_ref, count, None)
I wanted to leave this as `start` so that previous versions of the host would maintain the same behavior, since the host has enough information to "start" more actors

I could alternatively here query the hosts inventory and increment that number before sending scale

2023-10-10 17:39 UTC, brooksmtownsend commented on crates/wash-lib/src/actor.rs
> +        .stop_actor(host_id, actor_id, annotations)
Actually, I don't know if I want to do this quite yet. Scale accepts an actor reference but stop accepts an actor ID, so it would be a decently breaking change to do this

2023-10-10 17:40 UTC, brooksmtownsend commented on crates/wash-lib/src/actor.rs
> +        .stop_actor(host_id, actor_id, annotations)
Ideally what I would like to do is make it so that scale can take an actor ID instead of an image reference if scaling down but that introduces weird edge cases

2023-10-10 19:53 UTC, connorsmith256 commented on crates/wash-lib/src/actor.rs
>          .start_actor(host_id, actor_ref, count, None)
Ah okay, replying to this and the other thread here: I guess I'm wondering what will happen when we actually remove support for start/stop from the control interface. At that point wash _has_ to change its logic. Are you saying we just wait a while until we can reasonably assume all hosts will be running with the new scale logic, and update the wash logic at that time?

2023-10-10 19:57 UTC, brooksmtownsend commented on crates/wash-lib/src/actor.rs
>          .start_actor(host_id, actor_ref, count, None)
Yep that's the plan
1. wash works the same as before while hosts have old operations <-- you are here
2. wash removes old operations
3. host removes support for old operations

2023-10-10 19:58 UTC, connorsmith256 commented on crates/wash-lib/src/actor.rs
>          .start_actor(host_id, actor_ref, count, None)
Sounds good 👍

2023-10-10 19:58 UTC, connorsmith256 approved these changes, later dismissed

2023-10-10 20:49 UTC, brooksmtownsend commented
Failing tests because of a DNS error... will try again tomorrow

2023-10-10 20:57 UTC, brooksmtownsend commented
> Failing tests because of a DNS error... will try again tomorrow

Failing tests because I didn't exclude them from the nix suite :)

2023-10-12 19:57 UTC, connorsmith256 submitted a review, later dismissed
Approved with a suggestion :)

2023-10-12 19:57 UTC, connorsmith256 commented on Cargo.toml
> +wasmcloud-control-interface = "0.29"
Can we bump to 0.30 or are there breaking changes?

2023-10-12 20:25 UTC, connorsmith256 approved these changes

2023-10-12 20:26 UTC, brooksmtownsend commented on Cargo.toml
> +wasmcloud-control-interface = "0.29"
done!

2023-10-13 13:24 UTC, brooksmtownsend commented
@mattwilkinsonn added integration tests and ready for re-review

2023-10-13 13:46 UTC, mattwilkinsonn approved these changes

2023-10-13 13:46 UTC, merged