Allow tui logger to scroll
wasmCloud/wash-archive pull request #95
Opened 2021-02-19 15:36 UTC by brooksmtownsend

With the upgrade of tui_logger to `0.6.0`, we had to modify our terminal backend from crossterm to termion, which accounts for most of the code in this PR.

The important new features are:
- Added ALT+UP/DOWN / PageUp + PageDown handlers to the output pane and tui logger, which will scroll the appropriate pane depending on the current focus
- Added indicator of REPL focus, if focused on the input panel (e.g. typing commands) the REPL and Output window titles will be bold, if focused on the tui panel (e.g. scrolling through logs) the Tui panel will be bold.
- Using channels to send events to asynchronously draw REPL (modification needed as crossterm provided a way to asynchronously poll for events, rather than blocking iteration of events)

Because of the change from crossterm to termion, we no longer have support for SHIFT modified keycodes. Because of this, and changing to ALT, this will change the wash REPL API and we will need to bump to `0.3.0`

Before this is merged in, the following must be tested:
- [ ] ALT / PgUp / PgDown commands work on Windows and Linux
- [ ] Return (Enter) works on Windows and Linux

2021-02-21 22:47 UTC, stevelr commented
Thank you for working on the log scrolling. I tried wash (0.3.0 from the tui-log-update branch and have some feedback:

- scrolling the Output window with Alt+UP/DOWN and Tui Log with PgUp/PgDown works.

- if you type 'help' in REPL, it pastes help output into the Tui Log, and then it seems to lose the history of logs before the help output, and there is only one line of scrollback buffer.  If you don't type 'help', and the TuiLog has more than a screenful of regular log messages, the messages do scroll back further.

- In wash 0.2.0, I used to be able to select text in the output window but can't now. When you're doing the very first steps in the getting started tutorial, you do 'ctl get hosts', then 'ctl get inventory ...' and that's where I would double-click on the Host Id and paste it into the REPL window to complete the inventory command.  I can't select text anymore (in any of the four panes). This is kind of a big deal for new users (how do you do it btw?). I tried typing the first few letters, to see if it matches an unambiguous prefix, but that didn't seem to work. I did find [this tui crate issue](https://github.com/fdehau/tui-rs/issues/260) where one user couldn't select and the response was 

> "If you use input::MouseTerminal from termion then your application will intercept all mouse events and thus disabling the "normal" behavior of your terminal of choice in response to mouse click or drag events"

Since you're more familiar with the codebase I won't try to debug this further.

2021-02-22 13:41 UTC, brooksmtownsend commented
Thank you @stevelr, glad to hear it's working and thank you for doing some more extensive testing on your end. I can reproduce the `help` text and the selection on my end, I changed the terminal backend from crossterm to termion as a part of this upgrade so I bet that the mouse events are being intercepted when they weren't before. Planning to investigate further today and when I have any update's I'll let you know

2021-02-24 21:57 UTC, brooksmtownsend commented
Good news @stevelr , I was able to resolve both issues that you mentioned. You should now be able to scroll past the help text and use your mouse to highlight the identifiers, which is a must-have. Let me know if you do further testing here, otherwise I plan to do a few more tests and get this merged 🙂

2021-03-02 16:45 UTC, brooksmtownsend commented
Fixes #95

2021-03-04 14:17 UTC, autodidaddict requested changes
just make clippy happy.

2021-03-04 14:17 UTC, autodidaddict commented on src/up.rs
> +                ()
This triggers a clippy warning on an unneeded unit expression.

2021-03-04 14:17 UTC, autodidaddict commented on src/up.rs
> +                ()
Same as previous comment.

2021-03-04 14:17 UTC, autodidaddict commented on src/up.rs
> +        f
clippy: you don't need to assign the block to `f`, you can just return the block value.

2021-03-04 14:17 UTC, autodidaddict commented on src/up.rs
> +                .title(Span::styled(format!(" REPL "), style)),
wow.. clippy does not like you. Unnecessary format.

2021-03-04 21:35 UTC, autodidaddict approved these changes

2021-03-04 21:41 UTC, merged