feat: support specifying tags in actor config for use when signing
wasmCloud/wash-archive pull request #951
Opened 2023-10-27 02:05 UTC by vados-cosmonic

## Feature or Problem

The signing process enabled by the wasmCloud ecosystem can confer tags on to generated artifacts. This helps in adding metadata to actors and other artifacts produced by wash.

This commit adds the ability to specify tags in `wasmcloud.toml` to `wash`, so users can more easily tag generated & signed actors

## Related Issues

## Release Information

## Consumer Impact

## Testing

Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)

### Acceptance or Integration

### Manual Verification

2023-10-27 15:44 UTC, connorsmith256 requested changes
LGTM with one nit. Marking as "request changes" to prevent merges while https://github.com/wasmCloud/wasmCloud/pull/807 is in flight. Once that lands, let's re-open this PR against wasmCloud/wasmCloud

2023-10-27 15:44 UTC, connorsmith256 commented on crates/wash-lib/src/build.rs
> +        tags.push(WASMCLOUD_WASM_TAG_EXPERIMENTAL.into());
Edge case: what if a user has already specified `experimental` as a tag name? We should check for duplicates

2023-10-30 17:42 UTC, vados-cosmonic commented on crates/wash-lib/src/build.rs
> +        tags.push(WASMCLOUD_WASM_TAG_EXPERIMENTAL.into());
This is fixed, but going to re-open this against `wasmcloud/wasmcloud`.

2023-10-30 19:42 UTC, connorsmith256 commented
@vados-cosmonic would you mind opening this against the main repo? I'm working on archiving this repo

2023-10-30 19:44 UTC, closed without merging

2023-10-30 19:44 UTC, vados-cosmonic commented
Will do!